---

- platform: template
  switches:

    alarm_next_day:
      friendly_name: Alarm
      value_template: "{{ states('binary_sensor.alarm_next_day') }}"
      turn_on:
        service: input_boolean.turn_on
        data_template:
          entity_id: "input_boolean.alarm_weekday_{{ (now().weekday() + 1) % 7 }}"
      turn_off:
        service: input_boolean.turn_off
        data_template:
          entity_id: "input_boolean.alarm_weekday_{{ (now().weekday() + 1) % 7 }}"

    alarm_in_6_days:
      value_template: "{{ states('binary_sensor.alarm_in_6_days') }}"
      turn_on:
        service: input_boolean.turn_on
        data_template:
          entity_id: "input_boolean.alarm_weekday_{{ (now().weekday() + 6) % 7 }}"
      turn_off:
        service: input_boolean.turn_off
        data_template:
          entity_id: "input_boolean.alarm_weekday_{{ (now().weekday() + 6) % 7 }}"
