---

- platform: template
  switches:

    alarm_next_day:
      friendly_name: Alarm
      value_template: >
        {%- if now().weekday() + 1 == 1 -%}
        {{ states('input_boolean.alarm_weekday_1') }}
        {%- elif now().weekday() + 1== 2 -%}
        {{ states('input_boolean.alarm_weekday_2') }}
        {%- elif now().weekday() + 1 == 3 -%}
        {{ states('input_boolean.alarm_weekday_3') }}
        {%- elif now().weekday() + 1 == 4 -%}
        {{ states('input_boolean.alarm_weekday_4') }}
        {%- elif now().weekday() + 1 == 5 -%}
        {{ states('input_boolean.alarm_weekday_5') }}
        {%- elif now().weekday() + 1 == 6 -%}
        {{ states('input_boolean.alarm_weekday_6') }}
        {% else %}
        {{ states('input_boolean.alarm_weekday_0') }}
        {% endif %}
      turn_on:
        service: input_boolean.turn_on
        data_template:
          entity_id: "input_boolean.alarm_weekday_{{ (now().weekday() + 1) % 7}}"
      turn_off:
        service: input_boolean.turn_off
        data_template:
          entity_id: "input_boolean.alarm_weekday_{{ (now().weekday() + 1) % 7}}"
