---

- platform: template
  switches:

    alarm_next_day:
      friendly_name: Alarm
      value_template: >
        {%- if now().weekday() + 1 == 1 -%}
        {{ states('input_boolean.alarm_tuesday') }}
        {%- elif now().weekday() + 1== 2 -%}
        {{ states('input_boolean.alarm_wednesday') }}
        {%- elif now().weekday() + 1 == 3 -%}
        {{ states('input_boolean.alarm_thursday') }}
        {%- elif now().weekday() + 1 == 4 -%}
        {{ states('input_boolean.alarm_friday') }}
        {%- elif now().weekday() + 1 == 5 -%}
        {{ states('input_boolean.alarm_saturday') }}
        {%- elif now().weekday() + 1== 6 -%}
        {{ states('input_boolean.alarm_sunday') }}
        {% else %}
        {{ states('input_boolean.alarm_monday') }}
        {% endif %}
      turn_on:
        service: input_boolean.turn_on
        data_template:
          entity_id: >
            {%- if now().weekday() + 1 == 1 -%}
            input_boolean.alarm_tuesday
            {%- elif now().weekday() + 1== 2 -%}
            input_boolean.alarm_wednesday
            {%- elif now().weekday() + 1 == 3 -%}
            input_boolean.alarm_thursday
            {%- elif now().weekday() + 1 == 4 -%}
            input_boolean.alarm_friday
            {%- elif now().weekday() + 1 == 5 -%}
            input_boolean.alarm_saturday
            {%- elif now().weekday() + 1== 6 -%}
            input_boolean.alarm_sunday
            {% else %}
            input_boolean.alarm_monday
            {% endif %}
      turn_off:
        service: input_boolean.turn_off
        data_template:
          entity_id: >
            {%- if now().weekday() + 1 == 1 -%}
            input_boolean.alarm_tuesday
            {%- elif now().weekday() + 1== 2 -%}
            input_boolean.alarm_wednesday
            {%- elif now().weekday() + 1 == 3 -%}
            input_boolean.alarm_thursday
            {%- elif now().weekday() + 1 == 4 -%}
            input_boolean.alarm_friday
            {%- elif now().weekday() + 1 == 5 -%}
            input_boolean.alarm_saturday
            {%- elif now().weekday() + 1== 6 -%}
            input_boolean.alarm_sunday
            {% else %}
            input_boolean.alarm_monday
            {% endif %}
