---

- platform: circadian_lighting
  lights_ct:
    - light.living_room_lamp
    - light.living_room_tv
    - light.study_floor_lamp
  lights_xy:
    - light.study_shelf
    - light.bedroom_wardrobe
    - light.corridor_sideboard

  initial_transition: 0
  disable_brightness_adjust: true
  disable_entity: light.bedroom_wardrobe
  disable_state: 'off'
