---

- platform: circadian_lighting
  lights_ct:
    - light.living_room_lamp
    - light.living_room_tv
    - light.study_floor_lamp
  lights_rgb:
    - light.study_shelf
    - light.bedroom_wardrobe
    - light.corridor_sideboard

  sleep_entity: light.bedroom_wardrobe
  sleep_state: 'off'
  sleep_brightness: 50
