---

- platform: circadian_lighting
  lights_ct:
    - light.living_room_lamp
    - light.living_room_tv
    - light.study_floor_lamp
  lights_xy:
    - light.study_shelf
    - light.bedroom_wardrobe
    - light.corridor_sideboard

  disable_brightness_adjust: true
  disable_entity: input_boolean.disable_circadian_lighting
  disable_state: 'on'
