---

- platform: template
  switches:

    home_office_mode:
      friendly_name: Home Office Mode
      value_template: "{{ states('input_boolean.home_office_mode') }}"
      turn_on:
        service: input_boolean.turn_on
        entity_id: input_boolean.home_office_mode
      turn_off:
        service: input_boolean.turn_off
        entity_id: input_boolean.home_office_mode

    guest_mode:
      friendly_name: Guest Mode
      value_template: "{{ states('input_boolean.guest_mode') }}"
      turn_on:
        - service: media_player.volume_mute
          entity_id: media_player.study
          data:
            is_volume_muted: true
        - service: input_boolean.turn_on
          entity_id: input_boolean.guest_mode
        - service: input_boolean.turn_off
          entity_id: input_boolean.home_office_mode
      turn_off:
        - service: media_player.volume_mute
          entity_id: media_player.study
          data:
            is_volume_muted: false
        - service: input_boolean.turn_off
          entity_id: input_boolean.guest_mode

    party_mode:
      friendly_name: Party Mode
      value_template: "{{ states('input_boolean.party_mode') }}"
      turn_on:
        service: input_boolean.turn_on
        entity_id: input_boolean.party_mode
      turn_off:
        service: input_boolean.turn_off
        entity_id: input_boolean.party_mode

    summer_mode:
      friendly_name: Summer Mode
      value_template: "{{ states('input_boolean.summer_mode') }}"
      turn_on:
        - service: switch.turn_off
          entity_id: switch.climate_all
        - service: input_boolean.turn_on
          entity_id: input_boolean.summer_mode
      turn_off:
        - service: switch.turn_on
          entity_id: switch.climate_all
        - service: input_boolean.turn_off
          entity_id: input_boolean.summer_mode
