---

- platform: template
  switches:

    summer_mode:
      friendly_name: Summer Mode
      value_template: "{{ states('input_boolean.summer_mode') }}"
      turn_on:
        - service: switch.turn_on
          entity_id: switch.climate_all
        - service: input_boolean.turn_on
          entity_id: input_boolean.summer_mode
      turn_off:
        - service: switch.turn_off
          entity_id: switch.climate_all
        - service: input_boolean.turn_off
          entity_id: input_boolean.summer_mode

    guest_mode:
      friendly_name: Guest Mode
      value_template: "{{ is_state_attr('media_player.study', 'is_volume_muted', true) }}"
      turn_on:
        service: media_player.volume_mute
        entity_id: media_player.study
        data:
          is_volume_muted: true
      turn_off:
        service: media_player.volume_mute
        entity_id: media_player.study
        data:
          is_volume_muted: false
