---

- platform: template
  switches:

    remote_off:
      value_template: "{{ is_state_attr('remote.living_room', 'current_activity', 'PowerOff') }}"
      turn_on:
        - service: remote.turn_off
          entity_id: remote.living_room
        - service: media_player.turn_off
          entity_id: media_player.lg_webos_smart_tv
      turn_off:
        - service: remote.turn_off
          entity_id: remote.living_room
        - service: media_player.turn_off
          entity_id: media_player.lg_webos_smart_tv
