---

- platform: template
  switches:

    remote_off:
      value_template: "{{ is_state_attr('remote.living_room', 'current_activity', 'PowerOff') }}"
      turn_on:
        service: remote.turn_off
        data:
          entity_id: remote.living_room
      turn_off:
        service: remote.turn_off
        data:
          entity_id: remote.living_room
