---

- platform: template
  switches:

    display_tab_corridor:
      friendly_name: Display Tab
      value_template: "{{ states('binary_sensor.wake_corridor_tab') }}"
      turn_on:
        service: mqtt.publish
        data:
          topic: wallpanel/corridor/command
          payload: '{"wake":true,"wakeTime":3600}'
      turn_off:
        service: mqtt.publish
        data:
          topic: wallpanel/corridor/command
          payload: '{"wake":false, "relaunch": true}'
