---

- platform: command_line
  switches:
    updater:
      command_on: >
        curl -X PUT \
        # API Key injected by docker-compose as environment variable
        -H X-Api-key:$UPDATER_API_KEY \
        # API of separate service capable of updating home-assistant docker container
        # https://github.com/pkissling/home-assistant-updater
        localhost:5000/docker/containers/home-assistant/update"
