---
- platform: template
  switches:

    vacuum_start:
      value_template: "{{ is_state('vacuum.xiaomi_vacuum_cleaner', 'cleaning') }}"
      turn_on:
        service: vacuum.start
        data:
          entity_id: vacuum.xiaomi_vacuum_cleaner
      turn_off:
        service: vacuum.pause
        data:
          entity_id: vacuum.xiaomi_vacuum_cleaner
    
    vacuum_dock:
      value_template: >
        {{ 
          is_state('vacuum.xiaomi_vacuum_cleaner', 'docked')
            or
          is_state('vacuum.xiaomi_vacuum_cleaner', 'charging')
            or
          is_state('vacuum.xiaomi_vacuum_cleaner', 'returning')
        }}
      turn_on:
      - service: vacuum.pause
        data:
          entity_id: vacuum.xiaomi_vacuum_cleaner
      - delay: '00:00:00'
      - service: vacuum.return_to_base
        data:
          entity_id: vacuum.xiaomi_vacuum_cleaner
      turn_off:
        service: vacuum.pause
        data:
          entity_id: vacuum.xiaomi_vacuum_cleaner

