---
- platform: template
  switches:

    vacuum_start:
      value_template: "{{ is_state('vacuum.xiaomi_vacuum_cleaner', 'cleaning') }}"
      turn_on:
        service: vacuum.start
        entity_id: vacuum.xiaomi_vacuum_cleaner
      turn_off:
        service: vacuum.pause
        entity_id: vacuum.xiaomi_vacuum_cleaner

    vacuum_pause:
      value_template: "{{ is_state('vacuum.xiaomi_vacuum_cleaner', 'idle') }}"
      turn_on:
        service: vacuum.pause
        entity_id: vacuum.xiaomi_vacuum_cleaner
      turn_off:
        service: vacuum.start
        entity_id: vacuum.xiaomi_vacuum_cleaner

    vacuum_dock:
      value_template: >
        {{
          is_state('vacuum.xiaomi_vacuum_cleaner', 'docked')
            or
          is_state('vacuum.xiaomi_vacuum_cleaner', 'charging')
            or
          is_state('vacuum.xiaomi_vacuum_cleaner', 'returning')
        }}
      turn_on:
        service: vacuum.return_to_base
        entity_id: vacuum.xiaomi_vacuum_cleaner
      turn_off:
        service: vacuum.pause
        entity_id: vacuum.xiaomi_vacuum_cleaner
