language: python
python:
  - "3.6"
install:
  - pip3 install homeassistant
script:
  - hass -c . --script check_config
before_install:
  - mv secrets_dummy.yaml secrets.yaml
  - mkdir ssl
  - touch ssl/fullchain.pem
  - touch ssl/privkey.pem