
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Includes
automation: !include automations.yaml
device_tracker: !include device_tracker.yaml
group: !include groups.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# Integrations
tado: !include tado.yaml 
vacuum: !include vacuum.yaml

# Enable HTTPS
http:
  base_url: https://192.168.0.40:8123
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key