
# Core config
default_config:
discovery: !include includes/discovery.yaml
homeassistant: !include includes/homeassistant.yaml
http: !include includes/http.yaml
logger: !include includes/logger.yaml
person: !include includes/persons.yaml

# Include files with lists
automation: !include_dir_merge_list automations

# Include files with dictionaries
input_text: !include_dir_merge_named input_texts 

# Include root dir yamls
binary_sensor: !include binary_sensors.yaml
group: !include groups.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# Include 'includes' dir yamls
device_tracker: !include includes/device_trackers.yaml
notify: !include includes/notify.yaml
tado: !include includes/tado.yaml 
vacuum: !include includes/vacuum.yaml
yeelight: !include includes/yeelight.yaml