
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
device_tracker: !include device_tracker.yaml
tado: !include tado.yaml 

# Enable HTTPS
http:
  base_url: https://192.168.0.40:8123
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key