
# Core config
default_config:
homeassistant: !include includes/homeassistant.yaml
http: !include includes/http.yaml
discovery: !include includes/discovery.yaml
person: !include includes/persons.yaml

# Include root dir yamls
automation: !include automations.yaml
binary_sensor: !include binary_sensors.yaml
group: !include groups.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# Include 'includes' dir yamls
device_tracker: !include includes/device_trackers.yaml
notify: !include includes/notify.yaml
tado: !include includes/tado.yaml 
vacuum: !include includes/vacuum.yaml
yeelight: !include includes/yeelight.yaml