
# Core config
default_config:
discovery: !include includes/discovery.yaml
homeassistant: !include includes/homeassistant.yaml
http: !include includes/http.yaml
media_extractor: !include includes/media_extractor.yaml
logger: !include includes/logger.yaml
person: !include includes/persons.yaml

# Include files with lists
automation: !include_dir_merge_list automations
script: !include_dir_merge_list scripts
sensor: !include_dir_merge_list sensors
switch: !include_dir_merge_list switches
  
# Include files with dictionaries
input_boolean: !include_dir_merge_named input_booleans
input_datetime: !include_dir_merge_named input_datetimes
input_text: !include_dir_merge_named input_texts

# Include root dir yamls
binary_sensor: !include binary_sensors.yaml
group: !include groups.yaml
scene: !include scenes.yaml

# Include 'includes' dir yamls
device_tracker: !include includes/device_trackers.yaml
light: !include includes/lights.yaml
notify: !include includes/notify.yaml
tado: !include includes/tado.yaml 
vacuum: !include includes/vacuum.yaml
yeelight: !include includes/yeelight.yaml