---

# Core config
default_config:
frontend: !include includes/frontend.yaml
homeassistant: !include includes/homeassistant.yaml
http: !include includes/http.yaml
logger: !include includes/logger.yaml
lovelace: !include includes/lovelace.yaml
media_extractor: !include includes/media_extractor.yaml
wake_on_lan:

# Include files with lists
automation: !include_dir_merge_list automations
binary_sensor: !include_dir_merge_list binary_sensors
sensor: !include_dir_merge_list sensors
switch: !include_dir_merge_list switches

# Include files with dictionaries
command_line: !include_dir_merge_named command_lines
group: !include_dir_merge_named groups
input_boolean: !include_dir_merge_named input_booleans
input_datetime: !include_dir_merge_named input_datetimes
input_number: !include_dir_merge_named input_numbers
input_text: !include_dir_merge_named input_texts
script: !include_dir_merge_named scripts

# Include 'includes' dir yamls
adaptive_lighting: !include includes/adaptive_lighting.yaml
google_assistant: !include includes/google_assistant.yaml
influxdb: !include includes/influxdb.yaml
ios: !include includes/ios.yaml
light: !include includes/lights.yaml
mqtt: !include mqtt/mqtt.yaml
notify: !include includes/notify.yaml
pyscript: !include includes/pyscript.yaml
recorder: !include includes/recorder.yaml
tts: !include includes/tts.yaml
yahoofinance: !include includes/yahoo_finance.yaml
