---

# Core config
default_config:
discovery: !include includes/discovery.yaml
frontend:
  themes: !include_dir_merge_named themes
homeassistant: !include includes/homeassistant.yaml
logger: !include includes/logger.yaml
lovelace: !include includes/lovelace.yaml
media_extractor: !include includes/media_extractor.yaml
person: !include includes/persons.yaml

# Include files with lists
automation: !include_dir_merge_list automations
binary_sensor: !include_dir_merge_list binary_sensors
sensor: !include_dir_merge_list sensors
switch: !include_dir_merge_list switches

# Include files with dictionaries
group: !include_dir_merge_named groups
input_boolean: !include_dir_merge_named input_booleans
input_datetime: !include_dir_merge_named input_datetimes
input_text: !include_dir_merge_named input_texts
input_select: !include_dir_merge_named input_select
script: !include_dir_merge_named scripts

# Include 'includes' dir yamls
device_tracker: !include includes/device_trackers.yaml
light: !include includes/lights.yaml
notify: !include includes/notify.yaml
pi_hole: !include includes/pi_hole.yaml
spotcast: !include includes/spotcast.yaml
synology_dsm: !include includes/synology_dsm.yaml
tado: !include includes/tado.yaml
vacuum: !include includes/vacuum.yaml
yeelight: !include includes/yeelight.yaml
