---

background: var(--background-image)

custom_header:
  background: 'rgba(155, 155, 155, 0.25)'
  compact_mode: false
  button_text:
    options: '{{ hours24 }}:{{ minutesLZ }}'

views:
  - id: home
    name: Home
    icon: mdi:home
    cards:

      # Lights
      - type: entities
        entities:
          - type: custom:fold-entity-row
            head:
              entity: light.bedroom
            entities:
              - light.lightstrip
          - type: custom:fold-entity-row
            head:
              entity: light.living_room
            entities:
              - light.lamp
              - light.tv

      # Weather
      - type: weather-forecast
        name: Weather
        entity: weather.home

      # Toggle Modes
      - type: entities
        show_header_toggle: false
        entities:
          - switch.summer_mode
          - switch.guest_mode

      # TV Remote
      - type: custom:stack-in-card
        mode: vertical
        cards:
          - type: horizontal-stack
            cards:
              - entity: switch.remote_tv
                icon: 'mdi:television'
                type: 'custom:button-card'
                color: var(--switch-checked-color)
                show_name: false
                styles:
                  card:
                    - height: 70px
              - color: var(--switch-checked-color)
                entity: switch.remote_chromecast
                icon: 'mdi:cast'
                type: 'custom:button-card'
                show_name: false
                styles:
                  card:
                    - height: 70px
              - color: var(--switch-checked-color)
                entity: switch.remote_kodi
                icon: 'mdi:kodi'
                type: 'custom:button-card'
                show_name: false
                styles:
                  card:
                    - height: 70px
          - type: horizontal-stack
            cards:
              - color: var(--switch-checked-color)
                entity: switch.remote_speakers
                icon: 'mdi:cast-audio'
                type: 'custom:button-card'
                show_name: false
                styles:
                  card:
                    - height: 70px
              - color: var(--switch-checked-color)
                entity: switch.remote_smart_tv
                icon: 'mdi:netflix'
                type: 'custom:button-card'
                show_name: false
                styles:
                  card:
                    - height: 70px
              - color: '#ff8c8a'
                entity: switch.remote_off
                icon: 'mdi:power'
                type: 'custom:button-card'
                show_name: false
                styles:
                  card:
                    - height: 70px

      # Music Control
      - type: entities
        entities:
          - type: custom:fold-entity-row
            head:
              type: custom:mini-media-player
              entity: media_player.home_group
              group: true
              info: scroll
              hide:
                volume: true
                progress: true
                name: true
                controls: true
                power: true
              shortcuts:
                columns: 2
                buttons:
                  - type: service
                    name: NRJ
                    id: media_player.play_media
                    data:
                      entity_id: media_player.home_group
                      media_content_id: http://nrj.de/muenchen
                      media_content_type: music
                  - type: service
                    icon: mdi:power
                    id: media_player.turn_off
                    data:
                      entity_id: all
            entities:
              - type: custom:mini-media-player
                entity: media_player.chromecast
                group: true
                hide:
                  controls: true
                  source: true
                  progress: true
                  info: true
                  power: true
              - type: custom:mini-media-player
                entity: media_player.kitchen
                group: true
                hide:
                  controls: true
                  source: true
                  progress: true
                  info: true
                  power: true
              - type: custom:mini-media-player
                entity: media_player.study
                group: true
                hide:
                  controls: true
                  source: true
                  progress: true
                  info: true
                  power: true
              - type: custom:mini-media-player
                entity: media_player.bathroom
                group: true
                hide:
                  controls: true
                  source: true
                  progress: true
                  info: true
                  power: true
              - type: custom:mini-media-player
                entity: media_player.bedroom
                group: true
                hide:
                  controls: true
                  source: true
                  progress: true
                  info: true
                  power: true
              - type: custom:mini-media-player
                entity: media_player.balcony
                group: true
                hide:
                  controls: true
                  source: true
                  progress: true
                  info: true
                  power: true

      # Vacuum
      - type: custom:stack-in-card
        mode: vertical
        cards:
          - type: entities
            show_header_toggle: false
            entities:
              - input_boolean.vacuum_daily_cleanup
              - entity: sensor.vacuum_battery
                name: Battery
              - input_select.vacuum_room_cleanup
          - type: horizontal-stack
            cards:
              - type: custom:button-card
                icon: mdi:play
                color: var(--switch-checked-color)
                show_name: false
                entity: switch.vacuum_start
                styles:
                  card:
                    - height: 40px
              - type: custom:button-card
                icon: mdi:home
                show_name: false
                entity: switch.vacuum_dock
                color: var(--switch-checked-color)
                styles:
                  card:
                    - height: 40px
              - type: custom:button-card
                icon: mdi:trash-can
                color: var(--switch-checked-color)
                show_name: false
                entity: switch.vacuum_dust_bin
                styles:
                  card:
                    - height: 40px

      # Open Windows
      - type: entity-filter
        entities:
          - group.window_study
          - group.window_living_room
          - group.window_kitchen
          - group.window_bedroom
          - group.window_toilet
          - group.window_bathroom
        state_filter:
          - 'on'
        card:
          type: glance
          title: Open Windows
          show_state: false
          show_icon: true
          show_name: false
          columns: 2
        show_empty: false

      # Motion Sensors
      - type: entity-filter
        entities:
          - group.motion_study
        state_filter:
          - 'on'
        card:
          type: glance
          title: Motion sensor
          show_state: false
          show_icon: true
          show_name: false
          columns: 2
        show_empty: false

      # People at home
      - type: glance
        show_name: false
        entities:
          - !secret person1_entity_id
          - !secret person2_entity_id

      # Alarm Clock
      - type: entities
        entities:
          - type: custom:fold-entity-row
            entities:
              - input_boolean.alarm_weekday_0
              - input_boolean.alarm_weekday_1
              - input_boolean.alarm_weekday_2
              - input_boolean.alarm_weekday_3
              - input_boolean.alarm_weekday_4
              - input_boolean.alarm_weekday_5
              - input_boolean.alarm_weekday_6
            head:
              entity: switch.alarm
          - entity: input_datetime.wakeup_time

      # Temperature
      - type: custom:config-template-card
        entities:
          - climate.bathroom
          - climate.study
          - climate.living_room
          - climate.bedroom
          - climate.kitchen
        card:
          type: custom:bar-card
          entities:
            - entity: sensor.living_room_temperature
              icon: mdi:sofa
              target: "${states['climate.living_room'].state == 'auto' || states['climate.living_room'].state == 'heat' ? states['climate.living_room'].attributes.temperature : ''}"
              color: "${states['climate.living_room'].state == 'auto' || states['climate.living_room'].state == 'heat' ? 'var(--primary-color)' : 'var(--light-primary-color)'}"
              tap_action:
                action: call-service
                service: switch.toggle
                service_data:
                  entity_id: switch.climate_living_room
            - entity: sensor.kitchen_temperature
              icon: mdi:stove
              target: "${states['climate.kitchen'].state == 'auto' || states['climate.kitchen'].state == 'heat' ? states['climate.kitchen'].attributes.temperature : ''}"
              color: "${states['climate.kitchen'].state == 'auto' || states['climate.kitchen'].state == 'heat' ? 'var(--primary-color)' : 'var(--light-primary-color)'}"
              tap_action:
                action: call-service
                service: switch.toggle
                service_data:
                  entity_id: switch.climate_kitchen
            - entity: sensor.bathroom_temperature
              icon: mdi:shower
              target: "${states['climate.bathroom'].state == 'auto' || states['climate.bathroom'].state == 'heat' ? states['climate.bathroom'].attributes.temperature : ''}"
              color: "${states['climate.bathroom'].state == 'auto' || states['climate.bathroom'].state == 'heat' ? 'var(--primary-color)' : 'var(--light-primary-color)'}"
              tap_action:
                action: call-service
                service: switch.toggle
                service_data:
                  entity_id: switch.climate_bathroom
            - entity: sensor.bedroom_temperature
              icon: mdi:bed-king-outline
              target: "${states['climate.bedroom'].state == 'auto' || states['climate.bedroom'].state == 'heat' ? states['climate.bedroom'].attributes.temperature : ''}"
              color: "${states['climate.bedroom'].state == 'auto' || states['climate.bedroom'].state == 'heat' ? 'var(--primary-color)' : 'var(--light-primary-color)'}"
              tap_action:
                action: call-service
                service: switch.toggle
                service_data:
                  entity_id: switch.climate_bedroom
            - entity: sensor.study_temperature
              icon: mdi:desk-lamp
              target: "${states['climate.study'].state == 'auto' || states['climate.study'].state == 'heat' ? states['climate.study'].attributes.temperature : ''}"
              color: "${states['climate.study'].state == 'auto' || states['climate.study'].state == 'heat' ? 'var(--primary-color)' : 'var(--light-primary-color)'}"
              tap_action:
                action: call-service
                service: switch.toggle
                service_data:
                  entity_id: switch.climate_study
          min: 15
          max: 25
          decimal: 1
          positions:
            name: off  # yamllint disable-line rule:truthy

      # Calendar
      - type: custom:atomic-calendar-revive
        name: Calendar
        entities:
          - calendar.s_p
          - calendar.holidays_in_germany
        showWeekDay: true
        showMonth: true
        showLocation: false
        showLoader: false

  - id: monitoring
    name: Monitoring
    icon: mdi:server-security
    cards:

      # Pi-hole monitoring
      - type: custom:stack-in-card
        mode: vertical
        title: Pi-hole
        cards:
          - type: horizontal-stack
            cards:
              - type: custom:mini-graph-card
                entities:
                  - sensor.pi_hole_cpu_temp
                decimals: 0
                show:
                  points: false
                  labels: false
                  name: false
              - type: custom:mini-graph-card
                entities:
                  - sensor.pi_hole_cpu_usage
                decimals: 0
                show:
                  points: false
                  labels: false
                  name: false
              - type: custom:mini-graph-card
                entities:
                  - sensor.pi_hole_memory_usage
                decimals: 0
                show:
                  points: false
                  labels: false
                  name: false
          - type: horizontal-stack
            cards:
              - type: custom:button-card
                entity: binary_sensor.pi_hole_healthcheck
                show_name: false
                state:
                  - value: 'off'
                    color: '#ff8c8a'
                    icon: mdi:heart-broken
                  - value: 'on'
                    color: var(--switch-checked-color)
                    icon: mdi:heart
                styles:
                  card:
                    - height: 72px
              - type: custom:button-card
                entity: sensor.pi_hole_uptime
                show_name: false
                show_state: true
                show_icon: false
                styles:
                  card:
                    - height: 72px
              - type: custom:button-card
                entity: binary_sensor.pi_hole_ping
                show_name: false
                state:
                  - value: 'off'
                    color: '#ff8c8a'
                    icon: mdi:lan-disconnect
                  - value: 'on'
                    color: var(--switch-checked-color)
                    icon: mdi:lan-connect
                styles:
                  card:
                    - height: 72px

      # Kodi monitoring
      - type: custom:stack-in-card
        mode: vertical
        title: Kodi
        cards:
          - type: horizontal-stack
            cards:
              - type: custom:mini-graph-card
                entities:
                  - sensor.kodi_cpu_temp
                decimals: 0
                show:
                  points: false
                  labels: false
                  name: false
              - type: custom:mini-graph-card
                entities:
                  - sensor.kodi_cpu_usage
                decimals: 0
                show:
                  points: false
                  labels: false
                  name: false
              - type: custom:mini-graph-card
                entities:
                  - sensor.kodi_memory_usage
                decimals: 0
                show:
                  points: false
                  labels: false
                  name: false
          - type: horizontal-stack
            cards:
              - type: custom:button-card
                entity: binary_sensor.kodi_healthcheck
                show_name: false
                state:
                  - value: 'off'
                    color: '#ff8c8a'
                    icon: mdi:heart-broken
                  - value: 'on'
                    color: var(--switch-checked-color)
                    icon: mdi:heart
                styles:
                  card:
                    - height: 72px
              - type: custom:button-card
                entity: sensor.kodi_uptime
                show_name: false
                show_state: true
                show_icon: false
                styles:
                  card:
                    - height: 72px
              - type: custom:button-card
                entity: binary_sensor.kodi_ping
                show_name: false
                state:
                  - value: 'off'
                    color: '#ff8c8a'
                    icon: mdi:lan-disconnect
                  - value: 'on'
                    color: var(--switch-checked-color)
                    icon: mdi:lan-connect
                styles:
                  card:
                    - height: 72px

      # Synology
      - type: custom:stack-in-card
        title: Synology
        mode: vertical
        cards:
          - type: horizontal-stack
            cards:
              - type: custom:mini-graph-card
                entities:
                  - sensor.synology_temp_1
                  - sensor.synology_temp_2
                  - sensor.synology_temp_4
                show:
                  points: false
                  labels: false
                  name: false
                  legend: false
              - type: custom:mini-graph-card
                entities:
                  - sensor.synology_cpu_load_total
                show:
                  points: false
                  labels: false
                  name: false
              - type: custom:mini-graph-card
                entities:
                  - sensor.synology_memory_usage_real
                show:
                  points: false
                  labels: false
                  name: false
          - type: custom:bar-card
            entity: sensor.synology_volume_used_volume_2
            positions:
              name: off  # yamllint disable-line rule:truthy
          - type: entities
            entities:
              - sensor.synology_uptime
