---

views:
  - path: home
    icon: mdi:home
    cards:
      # Clock / weather
      - type: custom:clock-weather-card
        entity: weather.home
        date_pattern: dd.MM.yyyy
        forecast_days: 6

      # Vacuum
      - type: custom:vacuum-card
        entity: vacuum.xiaomi_vacuum_cleaner
        style: |
          ha-card {
            --vc-background: none;
            --vc-toolbar-background: none;
          }
        show_name: false
        compact_view: true
        stats:
          default:
            - entity_id: sensor.vacuum_filter_left
              unit: h
              subtitle: Filter
            - entity_id: sensor.vacuum_side_brush_left
              unit: h
              subtitle: Brush
            - entity_id: sensor.vacuum_main_brush_left
              unit: h
              subtitle: Roller
            - entity_id: sensor.vacuum_sensor_dirty_left
              unit: h
              subtitle: Sensors
            - entity_id: sensor.vacuum_next_emptying
              unit: m²
              subtitle: Bin
          cleaning:
            - entity_id: sensor.vacuum_current_clean_duration
              subtitle: Cleaning time
              unit: minutes
            - entity_id: sensor.vacuum_current_clean_area
              unit: m²
              subtitle: Cleaning area
        shortcuts:
          - name: Living room
            icon: mdi:sofa
            service: xiaomi_miio.vacuum_clean_segment
            service_data:
              entity_id: vacuum.xiaomi_vacuum_cleaner
              segments: 20
          - name: Kitchen
            icon: mdi:stove
            service: xiaomi_miio.vacuum_clean_segment
            service_data:
              entity_id: vacuum.xiaomi_vacuum_cleaner
              segments: 21
          - name: Corridor
            icon: mdi:shoe-print
            service: xiaomi_miio.vacuum_clean_segment
            service_data:
              entity_id: vacuum.xiaomi_vacuum_cleaner
              segments: 16
          - name: Bedroom
            icon: mdi:bed-king-outline
            service: xiaomi_miio.vacuum_clean_segment
            service_data:
              entity_id: vacuum.xiaomi_vacuum_cleaner
              segments: 19
          - name: Study
            icon: mdi:desk-lamp
            service: xiaomi_miio.vacuum_clean_segment
            service_data:
              entity_id: vacuum.xiaomi_vacuum_cleaner
              segments: 18
          - name: Toilet
            icon: mdi:toilet
            service: xiaomi_miio.vacuum_clean_segment
            service_data:
              entity_id: vacuum.xiaomi_vacuum_cleaner
              segments: 17
          - name: Bathroom
            icon: mdi:shower
            service: xiaomi_miio.vacuum_clean_segment
            service_data:
              entity_id: vacuum.xiaomi_vacuum_cleaner
              segments: 1
          - name: Tash
            icon: mdi:trash-can
            service: script.vacuum_dust_bin


      # Departures
      - type: glance
        entities:
          - sensor.departure_s7_to_hauptbahnhof
          - sensor.departure_u6_to_sendlinger_tor

      # Sun card
      - type: custom:sun-card
        darkMode: true
        timeFormat: 24h

      # Toggle Modes
      - type: entities
        entities:
          - switch.summer_mode
          - switch.guest_mode
          - input_boolean.home_office_mode
          - switch.party_mode
          - input_boolean.tv_mode
          - switch.detached_light
          - input_boolean.vacuum_daily_cleanup

      # Media
      - type: entities
        entities:
          - type: custom:mini-media-player
            entity: media_player.all_speakers
            group: hide
            info: scroll
            toggle_power: false
            hide:
              volume: true
              progress: true
          - input_number.volume_offset
          - type: custom:paper-buttons-row
            styles:
              "--pbs-button-color": "--var(primary-text-color)"
            base_config:
              layout: icon_name
            buttons:
              - icon: mdi:guitar-acoustic
                entity: switch.radio_unplugged
              - icon: mdi:city
                entity: switch.radio_nrj
              - icon: mdi:pulse
                entity: switch.radio_puls
          - type: custom:paper-buttons-row
            styles:
              "--pbs-button-color": "--var(primary-text-color)"
            base_config:
              layout: icon_name
            buttons:
              - icon: mdi:television
                entity: switch.living_room_tv
                name: TV
              - icon: mdi:cast
                entity: switch.living_room_chromecast
                name: Chromecast
              - icon: mdi:power
                entity: switch.remote_off
                name: 'Off'

      # Lights
      - type: entities
        entities:
          - type: custom:fold-entity-row
            head:
              entity: light.bedroom
            entities:
              - light.bedroom_wardrobe
          - type: custom:fold-entity-row
            head:
              entity: light.living_room
            entities:
              - light.living_room_lamp
              - light.living_room_couch
              - light.living_room_tv
          - type: custom:fold-entity-row
            head:
              entity: light.study
            entities:
              - light.study_desk
              - light.study_shelf
              - light.study_floor_lamp
          - type: custom:fold-entity-row
            head:
              entity: light.corridor
            entities:
              - light.corridor_sideboard

      # Alarm Clock
      - type: entities
        entities:
          - type: custom:fold-entity-row
            entities:
              - input_boolean.alarm_weekday_0
              - input_boolean.alarm_weekday_1
              - input_boolean.alarm_weekday_2
              - input_boolean.alarm_weekday_3
              - input_boolean.alarm_weekday_4
              - input_boolean.alarm_weekday_5
              - input_boolean.alarm_weekday_6
            head:
              entity: switch.alarm
          - entity: input_datetime.wakeup_time

      # Temperature
      - type: custom:thermostat-bar-card
        entities:
          - entity_id: climate.bathroom
            icon: mdi:shower
            window_sensor: binary_sensor.window_bathroom_contact
          - entity_id: climate.toilet
            icon: mdi:toilet
            window_sensor: binary_sensor.window_toilet_contact
          - entity_id: climate.living_room
            icon: mdi:sofa
            window_sensor: binary_sensor.window_living_room_contact
          - entity_id: climate.kitchen
            icon: mdi:stove
            window_sensor: binary_sensor.window_kitchen_contact
          - entity_id: climate.study
            icon: mdi:desk-lamp
            window_sensor: binary_sensor.window_study_contact
          - entity_id: climate.bedroom
            icon: mdi:bed-king-outline
            window_sensor: binary_sensor.window_bedroom_contact

      # Actions
      - type: entities
        entities:
          - type: custom:paper-buttons-row
            styles:
              "--pbs-button-color": "--var(primary-text-color)"
            base_config:
              layout: icon_name
            buttons:
              - icon: mdi:weather-night
                entity: script.good_night
                name: Good Night
              - icon: mdi:weather-sunset-up
                entity: script.good_morning
                name: Good Morning
              - icon: mdi:exit-run
                entity: script.im_leaving
                name: I'm leaving

      # People at home
      - type: entities
        entities:
          - person.patrick
          - person.sandra
          - input_boolean.person_guest
