---

background: var(--background-image)

views:
  # home
  - path: home
    icon: mdi:home
    cards:
      !include lovelace/home.yaml

  # misc
  - path: misc
    icon: mdi:regex
    cards:
      !include lovelace/misc.yaml

  # monitoring
  - path: monitoring
    icon: mdi:server-security
    cards:
      !include lovelace/monitoring.yaml

  # battery
  - path: battery
    icon: mdi:battery
    cards:
      !include lovelace/battery.yaml

  # plants
  - path: plants
    icon: mdi:leaf
    cards:
      !include lovelace/plants.yaml

  # dev
  - path: dev
    icon: mdi:bolt
    cards:
      !include lovelace/dev.yaml
