---

background: var(--background-image)

custom_header:
  background: var(--sidebar-background-color)
  compact_mode: true
  button_text:
    options: '{{ hours24 }}:{{ minutesLZ }}'

views:
  # home
  - path: home
    icon: mdi:home
    cards:
      !include lovelace/home.yaml

  # monitoring
  - path: monitoring
    icon: mdi:server-security
    cards:
      !include lovelace/monitoring.yaml

  # battery
  - path: battery
    icon: mdi:battery
    cards:
      !include lovelace/battery.yaml
