---

background: var(--background-image)

resources:
  - url: /hacsfiles/bar-card/bar-card.js
    type: module
  - url: /hacsfiles/button-card/button-card.js
    type: module
  - url: /hacsfiles/config-template-card/config-template-card.js
    type: module
  - url: /hacsfiles/custom-header/custom-header.js
    type: module
  - url: /hacsfiles/lovelace-fold-entity-row/fold-entity-row.js
    type: module
  - url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
    type: module
  - url: /hacsfiles/mini-media-player/mini-media-player-bundle.js
    type: module
  - url: /hacsfiles/stack-in-card/stack-in-card.js
    type: js

custom_header:
  background: 'rgba(155, 155, 155, 0.25)'
  compact_mode: false
  button_text:
    options: '{{ hours24 }}:{{ minutesLZ }}'

views:
  - id: 0
    name: Home
    icon: mdi:home
    cards:

      # Lights
      - type: entities
        entities:
          - type: custom:fold-entity-row
            head:
              entity: light.bedroom
            entities:
              - light.lightstrip
          - type: custom:fold-entity-row
            head:
              entity: light.living_room
            entities:
              - light.lamp
              - light.tv

      # Weather
      - type: weather-forecast
        name: Weather
        entity: weather.home

      # Toggle Modes
      - type: entities
        show_header_toggle: false
        entities:
          - entity: switch.summer_mode
            icon: mdi:weather-sunny

      # TV Remote
      - type: custom:stack-in-card
        mode: vertical
        cards:
          - type: horizontal-stack
            cards:
              - entity: switch.remote_tv
                icon: 'mdi:television'
                type: 'custom:button-card'
                color: '#30d257'
                show_name: false
                styles:
                  card:
                    - height: 70px
              - color: '#30d257'
                entity: switch.remote_chromecast
                icon: 'mdi:cast'
                type: 'custom:button-card'
                show_name: false
                styles:
                  card:
                    - height: 70px
              - color: '#30d257'
                entity: switch.remote_kodi
                icon: 'mdi:kodi'
                type: 'custom:button-card'
                show_name: false
                styles:
                  card:
                    - height: 70px
          - type: horizontal-stack
            cards:
              - color: '#30d257'
                entity: switch.remote_speakers
                icon: 'mdi:cast-audio'
                type: 'custom:button-card'
                show_name: false
                styles:
                  card:
                    - height: 70px
              - color: '#30d257'
                entity: switch.remote_ps4
                icon: 'mdi:playstation'
                type: 'custom:button-card'
                show_name: false
                styles:
                  card:
                    - height: 70px
              - color: '#ff8c8a'
                entity: switch.remote_off
                icon: 'mdi:power'
                type: 'custom:button-card'
                show_name: false
                styles:
                  card:
                    - height: 70px

      # Music Control
      - type: entities
        entities:
          - type: custom:fold-entity-row
            head:
              type: custom:mini-media-player
              entity: media_player.home_group
              group: true
              info: scroll
              hide:
                volume: true
                progress: true
                name: true
                controls: true
                power: true
              shortcuts:
                columns: 2
                buttons:
                  - type: service
                    name: NRJ
                    id: media_player.play_media
                    data:
                      entity_id: media_player.home_group
                      media_content_id: http://nrj.de/muenchen
                      media_content_type: music
                  - type: service
                    icon: mdi:power
                    id: media_player.turn_off
                    data:
                      entity_id: all
            entities:
              - type: custom:mini-media-player
                entity: media_player.chromecast
                group: true
                hide:
                  controls: true
                  source: true
                  progress: true
                  info: true
                  power: true
              - type: custom:mini-media-player
                entity: media_player.kitchen_speaker
                group: true
                hide:
                  controls: true
                  source: true
                  progress: true
                  info: true
                  power: true
              - type: custom:mini-media-player
                entity: media_player.study_speaker
                group: true
                hide:
                  controls: true
                  source: true
                  progress: true
                  info: true
                  power: true
              - type: custom:mini-media-player
                entity: media_player.bathroom_speaker
                group: true
                hide:
                  controls: true
                  source: true
                  progress: true
                  info: true
                  power: true
              - type: custom:mini-media-player
                entity: media_player.bedroom_display
                group: true
                hide:
                  controls: true
                  source: true
                  progress: true
                  info: true
                  power: true


      # Vacuum
      - type: custom:stack-in-card
        mode: vertical
        cards:
          - type: entities
            show_header_toggle: false
            entities:
              - input_boolean.vacuum_daily_cleanup
              - entity: sensor.vacuum_battery
                name: Battery
          - type: horizontal-stack
            cards:
              - icon: 'mdi:home'
                show_name: false
                entity: switch.vacuum_dock
                type: 'custom:button-card'
                color: '#30d257'
                styles:
                  card:
                    - height: 40px
              - type: 'custom:button-card'
                icon: 'mdi:play'
                color: '#30d257'
                show_name: false
                entity: switch.vacuum_start
                styles:
                  card:
                    - height: 40px

      # Open Windows
      - type: entity-filter
        entities:
          - group.window_study
          - group.window_living_room
          - group.window_kitchen
          - group.window_bedroom
          - group.window_toilet
          - group.window_bathroom
        state_filter:
          - 'on'
        card:
          type: glance
          title: Open Windows
          show_state: false
          show_icon: true
          show_name: false
          columns: 2
        show_empty: false

      # Motion Sensors
      - type: entity-filter
        entities:
          - group.motion_study
        state_filter:
          - 'on'
        card:
          type: glance
          title: Motion sensor
          show_state: false
          show_icon: true
          show_name: false
          columns: 2
        show_empty: false

      # People at home
      - type: entities
        entities:
          - !secret person1_entity_id
          - !secret person2_entity_id

      # Alarm Clock
      - type: entities
        entities:
          - type: custom:fold-entity-row
            entities:
              - input_boolean.alarm_weekday_0
              - input_boolean.alarm_weekday_1
              - input_boolean.alarm_weekday_2
              - input_boolean.alarm_weekday_3
              - input_boolean.alarm_weekday_4
              - input_boolean.alarm_weekday_5
              - input_boolean.alarm_weekday_6
            head:
              entity: switch.alarm_next_day
          - entity: input_datetime.wakeup_time

      # Synology
      - type: custom:stack-in-card
        mode: vertical
        cards:
          - type: horizontal-stack
            cards:
              - type: custom:mini-graph-card
                entities:
                  - sensor.synology_cpu_load_total
                name: CPU
                show:
                  points: false
                  labels: false
              - type: custom:mini-graph-card
                entities:
                  - sensor.synology_memory_usage_real
                name: Memory
                show:
                  points: false
                  labels: false
          - type: custom:bar-card
            entity: sensor.synology_volume_used_volume_2
            positions:
              name: off  # yamllint disable-line rule:truthy

      # Temperature
      - type: custom:config-template-card
        entities:
          - climate.bathroom
          - climate.study
          - climate.living_room
          - climate.bedroom
          - climate.kitchen
        card:
          type: custom:bar-card
          entities:
            - entity: sensor.living_room_temperature
              icon: mdi:sofa
              target: "${states['climate.living_room'].state == 'off' ? '' : states['climate.living_room'].attributes.temperature}"
              color: "${states['climate.living_room'].state == 'off' ? 'var(--light-primary-color)' : 'var(--primary-color)'}"
              tap_action:
                action: call-service
                service: switch.toggle
                service_data:
                  entity_id: switch.climate_living_room
            - entity: sensor.kitchen_temperature
              icon: mdi:stove
              color: "${states['climate.kitchen'].state == 'off' ? 'var(--light-primary-color)' : 'var(--primary-color)'}"
              target: "${states['climate.kitchen'].state == 'off' ? '' : states['climate.kitchen'].attributes.temperature}"
              tap_action:
                action: call-service
                service: switch.toggle
                service_data:
                  entity_id: switch.climate_kitchen
            - entity: sensor.bathroom_temperature
              icon: mdi:shower
              color: "${states['climate.bathroom'].state == 'off' ? 'var(--light-primary-color)' : 'var(--primary-color)'}"
              target: "${states['climate.bathroom'].state == 'off' ? '' : states['climate.bathroom'].attributes.temperature}"
              tap_action:
                action: call-service
                service: switch.toggle
                service_data:
                  entity_id: switch.climate_bathroom
            - entity: sensor.bedroom_temperature
              icon: mdi:bed-king-outline
              color: "${states['climate.bedroom'].state == 'off' ? 'var(--light-primary-color)' : 'var(--primary-color)'}"
              target: "${states['climate.bedroom'].state == 'off' ? '' : states['climate.bedroom'].attributes.temperature}"
              tap_action:
                action: call-service
                service: switch.toggle
                service_data:
                  entity_id: switch.climate_bedroom
            - entity: sensor.study_temperature
              icon: mdi:desk-lamp
              color: "${states['climate.study'].state == 'off' ? 'var(--light-primary-color)' : 'var(--primary-color)'}"
              target: "${states['climate.study'].state == 'off' ? '' : states['climate.study'].attributes.temperature}"
              tap_action:
                action: call-service
                service: switch.toggle
                service_data:
                  entity_id: switch.climate_study
          min: 15
          max: 25
          decimal: 1
          positions:
            name: off  # yamllint disable-line rule:truthy
