---


- platform: template
  sensors:

    departure_s7_to_hauptbahnhof:
      friendly_name: S7 - Hauptbahnhof
      value_template: >
        {% set departure = state_attr('sensor.harras_munchen_to_hauptbahnhof_munchen', 'departure') %}
        {% set delay = state_attr('sensor.harras_munchen_to_hauptbahnhof_munchen', 'delay') %}
        {{ departure }} (+{{ delay }}) & {{ state_attr('sensor.harras_munchen_to_hauptbahnhof_munchen', 'next') }}
    departure_u6_to_sendlinger_tor:
      friendly_name: U6 - Sendlinger Tor
      value_template: >
        {% set departure = state_attr('sensor.harras_munchen_to_sendlinger_tor_munchen', 'departure') %}
        {% set delay = state_attr('sensor.harras_munchen_to_sendlinger_tor_munchen', 'delay') %}
        {{ departure }} (+{{ delay }}) & {{ state_attr('sensor.harras_munchen_to_sendlinger_tor_munchen', 'next') }}
