---


- platform: min_max
  name: Motion Study Lightlevel
  type: mean
  entity_ids:
    - sensor.motion_study_ceiling_lightlevel
    - sensor.motion_study_shelf_lightlevel

- platform: min_max
  name: Motion Corridor Lightlevel
  type: mean
  entity_ids:
    - sensor.motion_corridor_left_lightlevel
    - sensor.motion_corridor_right_lightlevel
