---

- platform: template
  sensors:
    motion_corridor_lightlevel:
      value_template: >
        {{
          float(states.sensor.motion_corridor_left_lightlevel.state)
            +
          float(states.sensor.motion_corridor_left_lightlevel.state)
            / 2 |
          round(2)
        }}
      unit_of_measurement: lx
