---

- platform: template
  sensors:
    motion_study_lightlevel:
      friendly_name: Study
      value_template: "{{ states('sensor.motion_study_shelf_lightlevel') }}"
      unit_of_measurement: lx

- platform: average
  name: Motion Corridor Lightlevel
  duration:
    minutes: 20
  precision: 0
  entities:
    - sensor.motion_corridor_left_lightlevel
    - sensor.motion_corridor_right_lightlevel
