---


- platform: min_max
  name: Motion Study Illuminance Lux
  type: mean
  entity_ids:
    - sensor.motion_study_ceiling_illuminance_lux
    - sensor.motion_study_shelf_illuminance_lux

- platform: min_max
  name: Motion Corridor Illuminance Lux
  type: mean
  entity_ids:
    - sensor.motion_corridor_left_illuminance_lux
    - sensor.motion_corridor_right_illuminance_lux
