---


- platform: average
  name: Motion Study Lightlevel
  duration:
    minutes: 5
  precision: 0
  entities:
    - sensor.motion_study_ceiling_lightlevel
    - sensor.motion_study_shelf_lightlevel

- platform: average
  name: Motion Corridor Lightlevel
  duration:
    minutes: 5
  precision: 0
  entities:
    - sensor.motion_corridor_left_lightlevel
    - sensor.motion_corridor_right_lightlevel
