---

- platform: mvglive
  nextdeparture:
    - station: Harras
      name: S7 - Höhenkirchen
      lines: [S7]
      destinations: [Höhenkirchen-Siegertsbrunn]
      timeoffset: 10
      number: 3
    - station: Harras
      name: U6 - Garching
      lines: [U6]
      destinations: [Garching-Forschungszentrum]
      timeoffset: 12
      number: 3
