---

- platform: template
  sensors:

    # patrick
    parqet_api_patrick_overall:
      friendly_name: Absolute Value
      value_template: >
        {{
          states('sensor.parqet_api_patrick_crypto') | float +
          states('sensor.parqet_api_patrick_depot') | float
        }}
      unit_of_measurement: Euro
      icon_template: mdi:cash
    parqet_api_patrick_overall_returns_since_start_abs:
      friendly_name: Since start
      value_template: >
        {{
          states('sensor.parqet_api_patrick_returns_since_start_abs') | float
            +
          states('sensor.parqet_api_patrick_overall_realized_since_start_abs') | float
            +
          states('sensor.parqet_api_patrick_overall_dividends_since_start_abs') | float
        }}
      unit_of_measurement: Euro
      icon_template: mdi:trending-up
    parqet_api_patrick_overall_returns_since_start_rel:
      friendly_name: Since start
      value_template: >
        {% set current_value = states('sensor.parqet_api_patrick_value_since_start_abs') | float + states('sensor.parqet_api_patrick_overall_realized_since_start_abs') | float + states('sensor.parqet_api_patrick_overall_dividends_since_start_abs') | float %}
        {% set initial_investment = states('sensor.parqet_api_patrick_invested_since_start') | float %}
        {{ ((current_value - initial_investment) / initial_investment * 100) | round(2) }}
      unit_of_measurement: '%'
      icon_template: mdi:sack-percent

    # sandra
    parqet_api_sandra_overall:
      friendly_name: Absolute Value
      value_template: "{{ states('sensor.parqet_api_sandra_depot') }}"
      unit_of_measurement: Euro
      icon_template: mdi:cash
    parqet_api_sandra_overall_returns_since_start_abs:
      friendly_name: Since start
      value_template: >
        {{
          states('sensor.parqet_api_sandra_returns_since_start_abs') | float
            +
          states('sensor.parqet_api_sandra_overall_realized_since_start_abs') | float
            +
          states('sensor.parqet_api_sandra_overall_dividends_since_start_abs') | float
        }}
      unit_of_measurement: Euro
      icon_template: mdi:trending-up
    parqet_api_sandra_overall_returns_since_start_rel:
      friendly_name: Since start
      value_template: >
        {% set current_value = states('sensor.parqet_api_sandra_value_since_start_abs') | float + states('sensor.parqet_api_sandra_overall_realized_since_start_abs') | float + states('sensor.parqet_api_sandra_overall_dividends_since_start_abs') | float %}
        {% set initial_investment = states('sensor.parqet_api_sandra_invested_since_start') | float %}
        {{ ((current_value - initial_investment) / initial_investment * 100) | round(2) }}
      unit_of_measurement: '%'
      icon_template: mdi:sack-percent

    # overall
    parqet_api_overall:
      friendly_name: Both
      value_template: >
        {{
          states('sensor.parqet_api_patrick_overall') | float +
          states('sensor.parqet_api_sandra_overall') | float
        }}
      unit_of_measurement: Euro
      icon_template: mdi:account-group
    parqet_api_overall_plus_realized_since_start:
      friendly_name: Both
      value_template: >
        {{
          states('sensor.parqet_api_patrick_invested_since_start') | float +
          states('sensor.parqet_api_patrick_overall_returns_since_start_abs') | float +
          states('sensor.parqet_api_sandra_invested_since_start') | float +
          states('sensor.parqet_api_sandra_overall_returns_since_start_abs') | float
        }}
      unit_of_measurement: Euro
      icon_template: mdi:account-group
    parqet_api_overall_invested_since_start:
      friendly_name: Both invested
      value_template: >
        {{
          states('sensor.parqet_api_patrick_invested_since_start') | float +
          states('sensor.parqet_api_sandra_invested_since_start') | float
        }}
      unit_of_measurement: Euro
      icon_template: mdi:account-group
