---


- platform: mqtt
  unique_id: plug_kitchen_dishwasher
  name: Plug Kitchen Dishwasher
  state_topic: shellies/shellyplug-s-B49BB4/relay/0/power
  unit_of_measurement: W

- platform: mqtt
  unique_id: plug_living_room_amplifier
  name: Plug Living Room Amplifier
  state_topic: shellies/shellyplug-s-9A3C76/relay/0/power
  unit_of_measurement: W

- platform: mqtt
  unique_id: plug_study_monitor
  name: Plug Study Monitor
  state_topic: shellies/shellyplug-s-9D9424/relay/0/power
  unit_of_measurement: W
