---

- platform: integration
  source: sensor.plug_kitchen_dishwasher
  name: plug_kitchen_dishwasher_energy

- platform: integration
  source: sensor.plug_living_room_amplifier
  name: plug_living_room_amplifier_energy

- platform: integration
  source: sensor.plug_study_monitor
  name: plug_study_monitor_energy

- platform: integration
  source: sensor.plug_living_room_home_server
  name: plug_living_room_home_server_energy
