---

- platform: synologydsm
  host: 192.168.0.40
  port: 5551
  username: !secret synology_username
  password: !secret synology_password
  monitored_conditions:
    - cpu_total_load
    - memory_real_usage
    - network_up
    - network_down
    - volume_status
    - volume_percentage_used
