---

- platform: template
  sensors:
    vacuum_battery:
      value_template: "{{ state_attr('vacuum.xiaomi_vacuum_cleaner', 'battery_level') }}"
      unit_of_measurement: '%'
      icon_template: "{{ state_attr('vacuum.xiaomi_vacuum_cleaner', 'battery_icon') }}"

    vacuum_next_emptying:
      value_template: >
        {% set last_emptying = states('input_text.vacuum_last_emptying') | int %}
        {% set next_emptying = last_emptying + 500 %}
        {% set current = states('sensor.xiaomi_vacuum_cleaner_total_clean_area') | int %}
        {{ next_emptying - current }}
      unit_of_measurement: m²
