---

- platform: template
  sensors:
    vacuum_battery:
      value_template: "{{ state_attr('vacuum.roborock', 'battery_level') }}"
      unit_of_measurement: '%'
      icon_template: "{{ state_attr('vacuum.roborock', 'battery_icon') }}"

    vacuum_next_emptying:
      value_template: >
        {% set m2_since_last_emptying = states('input_text.vacuum_cleaned_m2_since_last_emptying') | int %}
        {{ 400 - m2_since_last_emptying }}
      unit_of_measurement: m²

    vacuum_filter_left:
      value_template: "{{ (states('sensor.roborock_filter_left') | float(0) / 3600) | round(0) }}"
      unit_of_measurement: h

    vacuum_side_brush_left:
      value_template: "{{ (states('sensor.roborock_side_brush_left') | float(0) / 3600) | round(0) }}"
      unit_of_measurement: h

    vacuum_main_brush_left:
      value_template: "{{ (states('sensor.roborock_main_brush_left') | float(0) / 3600) | round(0) }}"
      unit_of_measurement: h

    vacuum_sensor_dirty_left:
      value_template: "{{ (states('sensor.roborock_sensor_dirty_left') | float(0) / 3600) | round(0) }}"
      unit_of_measurement: h

    vacuum_current_clean_duration:
      value_template: "{{ (states('sensor.roborock_current_clean_duration') | float(0) / 60) | round(0) }}"
      unit_of_measurement: m

    vacuum_current_clean_area:
      value_template: "{{ states('sensor.roborock_current_clean_area') | round(0) }}"
      unit_of_measurement: m
