---

- platform: template
  sensors:

    volume_kitchen:
      value_template: >
        {% set volume = states('sensor.volume_kitchen_without_offset') | float(default=0) + states('input_number.volume_offset') | int / 100 | float %}
        {{ 0 if volume < 0 else volume }}
    volume_kitchen_without_offset:
      value_template: >
        {% set default_volume = 0.1 %}
        {% if is_state_attr('media_player.kitchen', 'media_content_id', 'https://dispatcher.rndfnk.com/br/puls/live/aac/low') %}
          {{ default_volume + 0.15 }}
        {% elif is_state_attr('media_player.kitchen', 'media_content_id', 'https://stream.regenbogen.de/unplugged/aac-128/tunein') %}
          {{ default_volume }}
        {% elif is_state_attr('media_player.kitchen', 'media_content_id', 'https://nrj.de/muenchen') %}
          {{ default_volume }}
        {% elif is_state_attr('media_player.kitchen', 'app_name', 'Spotify') or is_state_attr('media_player.kitchen', 'media_title', ' Streaming from Music Assistant') %}
          {{ default_volume + 0.20 }}
        {% elif 'google_translate' in (state_attr('media_player.kitchen', 'media_content_id') or []) %}
          {{ default_volume + 0.25 }}
        {% elif is_state_attr('media_player.kitchen', 'app_name', 'Google News') %}
          {{ default_volume + 0.15 }}
        {% else %}
          {{ default_volume }}
        {% endif %}

    volume_bathroom:
      value_template: >
        {% set volume = states('sensor.volume_bathroom_without_offset') | float(default=0) + states('input_number.volume_offset') | int / 100 | float %}
        {{ 0 if volume < 0 else volume }}
    volume_bathroom_without_offset:
      value_template: >
        {% set default_volume = 0.1 %}
        {% if is_state_attr('media_player.bathroom', 'media_content_id', 'https://dispatcher.rndfnk.com/br/puls/live/aac/low') %}
          {{ default_volume + 0.15 }}
        {% elif is_state_attr('media_player.bathroom', 'media_content_id', 'https://stream.regenbogen.de/unplugged/aac-128/tunein') %}
          {{ default_volume }}
        {% elif is_state_attr('media_player.bathroom', 'media_content_id', 'https://nrj.de/muenchen') %}
          {{ default_volume }}
        {% elif is_state_attr('media_player.bathroom', 'app_name', 'Spotify') or is_state_attr('media_player.bathroom', 'media_title', ' Streaming from Music Assistant') %}
          {{ default_volume + 0.20 }}
        {% elif 'google_translate' in (state_attr('media_player.bathroom', 'media_content_id') or []) %}
          {{ default_volume + 0.25 }}
        {% elif is_state_attr('media_player.bathroom', 'app_name', 'Google News') %}
          {{ default_volume + 0.15 }}
        {% else %}
          {{ default_volume }}
        {% endif %}

    volume_bedroom:
      value_template: >
        {% set volume = states('sensor.volume_bedroom_without_offset') | float(default=0) + states('input_number.volume_offset') | int / 100 | float %}
        {{ 0 if volume < 0 else volume }}
    volume_bedroom_without_offset:
      value_template: >
        {% set default_volume = 0.3 %}
        {% if is_state_attr('media_player.bedroom', 'media_content_id', 'https://dispatcher.rndfnk.com/br/puls/live/aac/low') %}
          {{ default_volume - 0.05 }}
        {% elif is_state_attr('media_player.bedroom', 'media_content_id', 'https://stream.regenbogen.de/unplugged/aac-128/tunein') %}
          {{ default_volume - 0.20 }}
        {% elif is_state_attr('media_player.bedroom', 'media_content_id', 'https://nrj.de/muenchen') %}
          {{ default_volume - 0.2 }}
        {% elif is_state_attr('media_player.bedroom', 'app_name', 'Spotify') or is_state_attr('media_player.bedroom', 'media_title', ' Streaming from Music Assistant') %}
          {{ default_volume }}
        {% elif 'google_translate' in (state_attr('media_player.bedroom', 'media_content_id') or []) %}
          {{ default_volume }}
        {% elif is_state_attr('media_player.bedroom', 'app_name', 'Google News') %}
          {{ default_volume }}
        {% else %}
          {{ default_volume }}
        {% endif %}

    volume_living_room:
      value_template: >
        {% set volume = states('sensor.volume_living_room_without_offset') | float(default=0) + states('input_number.volume_offset') | int / 100 | float %}
        {{ 0 if volume < 0 else volume }}
    volume_living_room_without_offset:
      value_template: >
        {% set default_volume = 0.1 %}
        {% if is_state_attr('media_player.living_room', 'media_content_id', 'https://dispatcher.rndfnk.com/br/puls/live/aac/low') %}
          {{ default_volume + 0.15 }}
        {% elif is_state_attr('media_player.living_room', 'media_content_id', 'https://stream.regenbogen.de/unplugged/aac-128/tunein') %}
          {{ default_volume }}
        {% elif is_state_attr('media_player.living_room', 'media_content_id', 'https://nrj.de/muenchen') %}
          {{ default_volume }}
        {% elif is_state_attr('media_player.living_room', 'app_name', 'Spotify') or is_state_attr('media_player.living_room', 'media_title', ' Streaming from Music Assistant') %}
          {{ default_volume + 0.20 }}
        {% elif 'google_translate' in (state_attr('media_player.living_room', 'media_content_id') or []) %}
          {{ default_volume + 0.25 }}
        {% elif is_state_attr('media_player.living_room', 'app_name', 'Google News') %}
          {{ default_volume + 0.15 }}
        {% else %}
          {{ default_volume }}
        {% endif %}

    volume_study:
      value_template: >
        {% set volume = states('sensor.volume_study_without_offset') | float(default=0) + states('input_number.volume_offset') | int / 100 | float %}
        {{ 0 if volume < 0 else volume }}
    volume_study_without_offset:
      value_template: >
        {% set default_volume = 0.1 %}
        {% if is_state('input_boolean.guest_mode', 'on') %}
          0
        {% elif is_state_attr('media_player.study', 'media_content_id', 'https://dispatcher.rndfnk.com/br/puls/live/aac/low') %}
          {{ default_volume + 0.15 }}
        {% elif is_state_attr('media_player.study', 'media_content_id', 'https://stream.regenbogen.de/unplugged/aac-128/tunein') %}
          {{ default_volume }}
        {% elif is_state_attr('media_player.study', 'media_content_id', 'https://nrj.de/muenchen') %}
          {{ default_volume }}
        {% elif is_state_attr('media_player.study', 'app_name', 'Spotify') or is_state_attr('media_player.study', 'media_title', ' Streaming from Music Assistant') %}
          {{ default_volume + 0.25 }}
        {% elif 'google_translate' in (state_attr('media_player.study', 'media_content_id') or []) %}
          {{ default_volume + 0.25 }}
        {% elif is_state_attr('media_player.study', 'app_name', 'Google News') %}
          {{ default_volume + 0.15 }}
        {% else %}
          {{ default_volume }}
        {% endif %}

    volume_chromecast:
      value_template: >
        {% set volume = states('sensor.volume_chromecast_without_offset') | float(default=0) + states('input_number.volume_offset') | int / 100 | float %}
        {{ 0 if volume < 0 else volume }}
    volume_chromecast_without_offset:
      value_template: >
        {% set default_volume = 0.5 %}
        {% if is_state_attr('media_player.chromecast', 'media_content_id', 'https://dispatcher.rndfnk.com/br/puls/live/aac/low') %}
          {{ default_volume + 0.2 }}
        {% elif is_state_attr('media_player.chromecast', 'media_content_id', 'https://stream.regenbogen.de/unplugged/aac-128/tunein') %}
          {{ default_volume }}
        {% elif is_state_attr('media_player.chromecast', 'media_content_id', 'https://nrj.de/muenchen') %}
          {{ default_volume }}
        {% elif is_state_attr('media_player.chromecast', 'app_name', 'Spotify') or is_state_attr('media_player.chromecast', 'media_title', ' Streaming from Music Assistant') %}
          {{ default_volume + 0.35 }}
        {% elif 'google_translate' in (state_attr('media_player.chromecast', 'media_content_id') or []) %}
          {{ default_volume + 0.2 }}
        {% elif is_state_attr('media_player.chromecast', 'app_name', 'Google News') %}
          {{ default_volume + 0.2 }}
        {% else %}
          {{ default_volume }}
        {% endif %}
