---
- platform: template
  sensors:

    alarm_today:
      value_template: >
        {%- if now().weekday() == 1 -%}
          {{ is_state('input_boolean.alarm_weekday_1', 'on') }}
        {%- elif now().weekday() == 2 -%}
          {{ is_state('input_boolean.alarm_weekday_2', 'on') }}
        {%- elif now().weekday() == 3 -%}
          {{ is_state('input_boolean.alarm_weekday_3', 'on') }}
        {%- elif now().weekday() == 4 -%}
          {{ is_state('input_boolean.alarm_weekday_4', 'on') }}
        {%- elif now().weekday() == 5 -%}
          {{ is_state('input_boolean.alarm_weekday_5', 'on') }}
        {%- elif now().weekday() == 6 -%}
          {{ is_state('input_boolean.alarm_weekday_6', 'on') }}
        {% else %}
          {{ is_state('input_boolean.alarm_weekday_0', 'on') }}
        {% endif %}
