---

- platform: template
  sensors:
    night_light:
      value_template: >
        {{
          is_state('binary_sensor.sun', 'off')
            and
          ((now().hour >= 23) or (now().hour <= 6)) and now().minute < 30
        }}
