---

- platform: template
  sensors:
    lightlevel_study_dark:
      value_template: >
        {% if is_number(states('sensor.motion_study_lightlevel')) %}
          {{ states('sensor.motion_study_lightlevel') | int < 25 }}
        {% else %}
          {{ is_state('sun.sun', 'below_horizon') }}
        {% endif %}
