---

- platform: template
  sensors:
    lightlevel_study_dark:
      value_template: >
        {% if not is_state('sensor.motion_study_lightlevel', 'unknown') %}
          {{ states('sensor.motion_study_lightlevel') | int < 25 }}
        {% else %}
          false
        {% endif %}
