---

- platform: template
  sensors:
    lightlevel_study_dark:
      delay_off:
        minutes: 5
      value_template: >
        {% if is_number(states('sensor.motion_study_illuminance_lux')) %}
          {{ states('sensor.motion_study_illuminance_lux') < 70 }}
        {% else %}
          {{ is_state('sun.sun', 'below_horizon') }}
        {% endif %}
