---

- platform: template
  sensors:

    motion_corridor_occupancy:
      friendly_name: Corridor
      value_template: >
        {{
          is_state('binary_sensor.motion_corridor_right_occupancy', 'on')
            or
          is_state('binary_sensor.motion_corridor_left_occupancy', 'on')
            or
          is_state('binary_sensor.motion_corridor_tab_occupancy', 'on')
            or
          is_state('binary_sensor.door_corridor_contact', 'on')
        }}

    motion_study_occupancy:
      friendly_name: Study
      value_template: >
        {{
          is_state('binary_sensor.motion_study_desk_occupancy', 'on')
            or
          is_state('binary_sensor.motion_study_shelf_occupancy', 'on')
            or
          is_state('binary_sensor.motion_study_main_occupancy', 'on')
        }}

    motion_study_desk_occupancy:
      friendly_name: Study
      value_template: >
        {{
          is_state('binary_sensor.motion_study_desk_1_occupancy', 'on')
            or
          is_state('binary_sensor.motion_study_desk_2_occupancy', 'on')
        }}
