---

- platform: template
  sensors:

    motion_corridor:
      value_template: >
        {{
          is_state('binary_sensor.motion_corridor_right', 'on')
            or
          is_state('binary_sensor.motion_corridor_left', 'on')
        }}
