---

- platform: ping
  name: pi_hole_ping
  host: localhost

- platform: command_line
  name: pi_hole_healthcheck
  device_class: connectivity
  command: 'nslookup -timeout=1 -retry=3 google.com localhost > /dev/null && echo ON || echo OFF'
  scan_interval: 10  # seconds
