---

- platform: ping
  name: pi_hole_ping
  host: pihole

- platform: command_line
  name: pi_hole_healthcheck
  command: curl -m 3 -s http://pihole/admin/api.php?summary > /dev/null && echo ON || echo OFF
