---

- platform: ping
  name: pi_hole_ping
  host: pihole

- platform: command_line
  name: pi_hole_healthcheck
  device_class: connectivity
  command: 'nslookup google.com pihole > /dev/null && echo ON || echo OFF'
