---

- platform: template
  sensors:
    sun:
      value_template: >
        {{
          states('sensor.motion_corridor_lightlevel') | int > 40
            or
          '08:55' < states('sensor.time') < '15:55'
        }}
      delay_on: 00:05:00
      delay_off: 00:05:00
