---

- platform: template
  sensors:
    sun:
      value_template: >
        {% set actual_sunrise_time = (as_timestamp(state_attr('sun.sun' , 'next_rising')) + (60 * 60)) | timestamp_custom('%H:%M') %}
        {% if actual_sunrise_time < '08:00' %}
          {% set sunrise_time = '08:00' %}
        {% else %}
          {% set sunrise_time = actual_sunrise_time %}
        {% endif %}

        {% set actual_sunset_time = (as_timestamp(state_attr('sun.sun' , 'next_setting')) - (60 * 60)) | timestamp_custom('%H:%M') %}
        {% if actual_sunset_time > '17:00' %}
          {% set sunset_time = '17:00' %}
        {% else %}
          {% set sunset_time = actual_sunset_time %}
        {% endif %}

        {% if is_number(states('sensor.motion_study_illuminance_lux')) %}
          {{
            sunrise_time <= states('sensor.time')
              and
            (
              states('sensor.motion_study_illuminance_lux') | int > 50
                or
              states('sensor.time') < sunset_time
            )
          }}
        {% else %}
          {{ is_state('sun.sun', 'above_horizon') }}
        {% endif %}
