---

- platform: template
  sensors:
    sun:
      value_template: >
        {% if not is_state('sensor.motion_corridor_lightlevel', 'unknown') and not is_state('sensor.motion_corridor_lightlevel', 'unavailable') %}
          {{
            states('sensor.motion_corridor_lightlevel') | int > 40
              or
            '08:55' < states('sensor.time') < '15:55'
          }}
        {% else %}
          {{ is_state('sun.sun', 'above_horizon') }}
        {% endif %}
      delay_on: 00:05:00
      delay_off: 00:05:00
