---

- platform: template
  sensors:
    sun:
      value_template: >
        {% if is_number(states('sensor.motion_corridor_lightlevel')) %}
          {{
            states('sensor.motion_corridor_lightlevel') | int > 40
              or
            '09:00' < states('sensor.time') < '16:00'
          }}
        {% else %}
          {{ is_state('sun.sun', 'above_horizon') }}
        {% endif %}
