---

- platform: template
  sensors:
    sun:
      value_template: >
        {% set actual_sunrise_time = (as_timestamp(state_attr('sun.sun', 'next_rising')) + 3600) | timestamp_custom('%H:%M') %}
        {% set latest_light_off_time = '09:00' if is_state('input_boolean.summer_mode', 'off') else '08:00' %}
        {% set sunrise_time = max(actual_sunrise_time, latest_light_off_time) %}

        {% set actual_sunset_time = (as_timestamp(state_attr('sun.sun', 'next_setting')) - 3600) | timestamp_custom('%H:%M') %}
        {% set earliest_light_on_time = '16:00' if is_state('input_boolean.summer_mode', 'off') else '17:00' %}
        {% set sunset_time = min(actual_sunset_time, earliest_light_on_time) %}

        {% if states('sensor.gw1100a_solar_lux') | is_number %}
          {{
            is_state('binary_sensor.outside_dark', 'off')
              or
            sunrise_time <= states('sensor.time') < sunset_time
          }}
        {% else %}
          {{ is_state('sun.sun', 'above_horizon') }}
        {% endif %}
