---

- platform: template
  sensors:

    thermostat_kitchen:
      value_template: >
        {{
          is_state('climate.kitchen', 'heat')
            or
          is_state('climate.kitchen', 'auto')
        }}

    thermostat_living_room:
      value_template: >
        {{
          is_state('climate.living_room', 'heat')
            or
          is_state('climate.living_room', 'auto')
        }}

    thermostat_bathroom:
      value_template: >
        {{
          is_state('climate.bathroom', 'heat')
            or
          is_state('climate.bathroom', 'auto')
        }}

    thermostat_study:
      value_template: >
        {{
          is_state('climate.study', 'heat')
            or
          is_state('climate.study', 'auto')
        }}

    thermostat_bedroom:
      value_template: >
        {{
          is_state('climate.bedroom', 'heat')
            or
          is_state('climate.bedroom', 'auto')
        }}

    thermostat_living_room_warning:
      value_template: >
        {{
          is_state('binary_sensor.thermostat_living_room', 'on')
            and
          is_state('group.window_living_room', 'on')
        }}

    thermostat_kitchen_warning:
      value_template: >
        {{
          is_state('binary_sensor.thermostat_kitchen', 'on')
            and
          is_state('group.window_kitchen', 'on')
        }}

    thermostat_bedroom_warning:
      value_template: >
        {{
          is_state('binary_sensor.thermostat_bedroom', 'on')
            and
          is_state('group.window_bedroom', 'on')
        }}

    thermostat_study_warning:
      value_template: >
        {{
          is_state('binary_sensor.thermostat_study', 'on')
            and
          is_state('group.window_study', 'on')
        }}

    thermostat_bathroom_warning:
      value_template: >
        {{
          is_state('binary_sensor.thermostat_bathroom', 'on')
            and
          is_state('group.window_bathroom', 'on')
        }}
