---

- platform: template
  sensors:

    thermostat_kitchen:
      value_template: >
        {{
          is_state('climate.kitchen', 'heat')
            or
          is_state('climate.kitchen', 'auto')
        }}

    thermostat_living_room:
      value_template: >
        {{
          is_state('climate.living_room', 'heat')
            or
          is_state('climate.living_room', 'auto')
        }}

    thermostat_bathroom:
      value_template: >
        {{
          is_state('climate.bathroom', 'heat')
            or
          is_state('climate.bathroom', 'auto')
        }}

    thermostat_study:
      value_template: >
        {{
          is_state('climate.study', 'heat')
            or
          is_state('climate.study', 'auto')
        }}

    thermostat_bedroom:
      value_template: >
        {{
          is_state('climate.bedroom', 'heat')
            or
          is_state('climate.bedroom', 'auto')
        }}
