---

- platform: template
  sensors:

    window_study:
      friendly_name: Window Study
      value_template: >
        {{
          is_state('binary_sensor.window_study_right_r', 'on')
            or
          is_state('binary_sensor.window_study_right_l', 'on')
            or
          is_state('binary_sensor.window_study_left_r', 'on')
            or
          is_state('binary_sensor.window_study_left_l', 'on')
        }}

    window_bedroom:
      friendly_name: Window Bedroom
      value_template: >
        {{
          is_state('binary_sensor.window_bedroom_left', 'on')
            or
          is_state('binary_sensor.window_bedroom_right', 'on')
        }}
