---

- platform: template
  sensors:

    window_bedroom_contact:
      friendly_name: Window Bedroom
      value_template: >
        {{
          is_state('binary_sensor.window_bedroom_left_contact', 'on')
            or
          is_state('binary_sensor.window_bedroom_right_contact', 'on')
        }}

    window_study_contact:
      friendly_name: Window Study
      value_template: >
        {{
          is_state('binary_sensor.window_study_right_r_contact', 'on')
            or
          is_state('binary_sensor.window_study_right_l_contact', 'on')
            or
          is_state('binary_sensor.window_study_left_r_contact', 'on')
            or
          is_state('binary_sensor.window_study_left_l_contact', 'on')
        }}
