---

- alias: Actions - Good Night - Fired
  trigger:
    platform: event
    event_type: ios.action_fired
    event_data:
      actionName: Good Night
  action:
    service: script.turn_on
    entity_id: script.good_night

- alias: Actions - Play Radio - Fired
  trigger:
    platform: event
    event_type: ios.action_fired
    event_data:
      actionName: Play Radio
  action:
    service: switch.turn_on
    entity_id: switch.radio_puls

- alias: Actions - Start Vacuum - Fired
  trigger:
    platform: event
    event_type: ios.action_fired
    event_data:
      actionName: Start Vacuum
  action:
    service: vacuum.start
    entity_id: vacuum.roborock
