---

- alias: Adaptive Lighting - Bedroom - Turn on when bedroom light off
  trigger:
    platform: state
    entity_id: light.bedroom
    to: 'off'
  action:
    service: switch.turn_on
    entity_id:
      - switch.adaptive_lighting_sleep_mode_corridor
      - switch.adaptive_lighting_sleep_mode_living_room

- alias: Adaptive Lighting - Bedroom - Turn off when bedroom light on
  trigger:
    platform: state
    entity_id: light.bedroom
    to: 'on'
  action:
    service: switch.turn_off
    entity_id:
      - switch.adaptive_lighting_sleep_mode_corridor
      - switch.adaptive_lighting_sleep_mode_living_room

- alias: Adaptive Lighting - Study - Turn off when Home Office Mode on
  trigger:
    platform: state
    entity_id: input_boolean.home_office_mode
    to: 'on'
  action:
    - service: switch.turn_off
      entity_id: switch.adaptive_lighting_study

- alias: Adaptive Lighting - Study - Turn on when Home Office Mode off
  trigger:
    platform: state
    entity_id: input_boolean.home_office_mode
    to: 'off'
  action:
    - service: switch.turn_on
      entity_id: switch.adaptive_lighting_study
    - service: adaptive_lighting.apply
      data:
        entity_id: switch.adaptive_lighting_study
        lights: light.study
        adapt_brightness: false

