---

- alias: Alarm - Morning Routine - Sunrise Lights
  trigger:
    platform: template
    value_template: >
      {% set current_time = (now().hour * 60 + now().minute) * 60 %}
      {% set wakeup_time = state_attr('input_datetime.wakeup_time', 'timestamp') %}
      {{ current_time == wakeup_time - (15 * 60) }}
  condition:
    - condition: state
      entity_id: switch.alarm
      state: 'on'
    - condition: state
      entity_id: group.residents
      state: home
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.night_light_mode
    - service: adaptive_lighting.set_manual_control
      entity_id: switch.adaptive_lighting_bedroom
      data:
        manual_control: true
    - service: light.turn_on
      entity_id: light.bedroom
      data:
        brightness: 200
        transition: 900  # 15 min
    - delay:
        minutes: 30
    - service: adaptive_lighting.set_manual_control
      entity_id: switch.adaptive_lighting_bedroom
      data:
        manual_control: false

- alias: Alarm - Morning Routine - News and Radio
  trigger:
    platform: time
    at: input_datetime.wakeup_time
  condition:
    - condition: state
      entity_id: switch.alarm
      state: 'on'
    - condition: state
      entity_id: group.residents
      state: home
  action:
    service: switch.turn_on
    entity_id: switch.radio_puls

- alias: Alarm - Toggle alarm when alarm needs adjustment due to workday
  trigger:
    platform: time
    at: '12:00:00'
  condition:
    condition: template
    value_template: "{{ states('binary_sensor.workday_sensor') != states('input_boolean.alarm_weekday_' ~ now().weekday()) }}"
  action:
    - service: input_boolean.toggle
      data:
        entity_id: "input_boolean.alarm_weekday_{{ now().weekday() }}"
    - service: notify.patrick
      data:
        title: Alarm Clock
        message: >
          {% set days = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"] %}
          Alarm for next {{ days[now().weekday()] }} turned {{ states('binary_sensor.workday_sensor') }}.
