---

- alias: Door - Main Door - Enable guest mode on door open
  trigger:
    - platform: state
      entity_id: binary_sensor.door_corridor
      from: 'off'
      to: 'on'
  condition:
    condition: state
    entity_id: group.residents
    state: not_home
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.person_guest
    - wait_template: >
        {{
          is_state('person.patrick', 'home')
            or
          is_state('person.sandra', 'home')
        }}
      timeout: 01:00:00
    - service: input_boolean.turn_off
      entity_id: input_boolean.person_guest
