---

- alias: Door - Main Door - Enable guest mode if resident not home
  trigger:
    - platform: state
      entity_id: binary_sensor.door_corridor
      from: 'off'
      to: 'on'
  condition:
    condition: state
    entity_id: group.residents
    state: not_home
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.person_guest
    - wait_template: >
        {{
          is_state('person.patrick', 'home')
            or
          is_state('person.sandra', 'home')
        }}
      timeout: 01:00:00
    - service: input_boolean.turn_off
      entity_id: input_boolean.person_guest

- alias: Door - Main Door - Turn on lights if resident is home
  trigger:
    - platform: state
      entity_id: binary_sensor.door_corridor
      from: 'off'
      to: 'on'
  condition:
    condition: state
    entity_id: group.residents
    state: home
  action:
    service: script.light_ambient_turn_on
    data:
      light_entity: light.corridor_sideboard
      motion_sensor_entity: binary_sensor.motion_corridor

- alias: Door - Main Door - Turn on tab on door open
  trigger:
    - platform: state
      entity_id: binary_sensor.door_corridor
      from: 'off'
      to: 'on'
  action:
    - service: switch.turn_on
      entity_id: switch.display_tab_corridor
    - wait_for_trigger:
        platform: state
        entity_id: binary_sensor.motion_corridor
        to: 'off'
        for:
          minutes: 2
      timeout: '00:30:00'
    - service: switch.turn_off
      entity_id: switch.display_tab_corridor
