---

- alias: Lights - Ambient - Turn on when sunset
  trigger:
    platform: state
    entity_id: binary_sensor.sun
    to: 'off'
  condition:
    - condition: state
      entity_id: group.residents
      state: home
  action:
    service: script.lights_ambient_turn_on
    data:
      transition: 1800  # 30 min

- alias: Lights - Ambient - Turn off after sunrise
  trigger:
    platform: state
    entity_id: binary_sensor.sun
    to: 'on'
  condition:
    - condition: state
      entity_id: light.ambient
      state: 'on'
  action:
    service: script.light_ambient_turn_off
    data:
      transition: 60  # 1 min

- alias: Lights - Ambient - Turn on when somebody came home
  trigger:
    platform: state
    entity_id: group.residents
    from: not_home
    to: home
  condition:
    condition: state
    entity_id: binary_sensor.sun
    state: 'off'
  action:
    service: script.lights_ambient_turn_on

- alias: Light - Ambient - Force off when sunlight
  trigger:
    platform: state
    entity_id: light.ambient
    to: 'on'
    for:
      minutes: 30
  condition:
    - condition: state
      entity_id: binary_sensor.sun
      state: 'on'
    - condition: time
      after: '08:00:00'
  action:
    service: script.light_ambient_turn_off
    data:
      transition: 60  # 1 min

- alias: Light - Study Desk - Turn on when home office mode on and dark
  trigger:
    - platform: state
      entity_id: input_boolean.home_office_mode
      to: 'on'
    - platform: state
      entity_id: binary_sensor.lightlevel_study_dark
      to: 'on'
      for:
        minutes: 5
  condition:
    - condition: state
      entity_id: input_boolean.home_office_mode
      state: 'on'
    - condition: state
      entity_id: group.residents
      state: home
    - condition: state
      entity_id: binary_sensor.lightlevel_study_dark
      state: 'on'
    - "{{ not is_state('vacuum.xiaomi_vacuum_cleaner', 'cleaning') }}"
    - "{{ not is_state('vacuum.xiaomi_vacuum_cleaner', 'returning') }}"
  action:
    service: switch.turn_on
    entity_id: switch.study_lamp

- alias: Light - Study Desk - Turn off when home office mode off
  trigger:
    - platform: state
      entity_id: input_boolean.home_office_mode
      to: 'off'
    - platform: state
      entity_id: binary_sensor.lightlevel_study_dark
      to: 'off'
      for:
        minutes: 30
  action:
    service: switch.turn_off
    entity_id: switch.study_lamp

- alias: Light - Study Shelf - Increase brightness on motion
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_study
      to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.guest_mode
      state: 'off'
  action:
    service: script.light_ambient_turn_on
    data:
      light_entity: light.study_shelf
      motion_sensor_entity: binary_sensor.motion_study
      dim_from_full_after_mins: 15

- alias: Light - Study Floor Lamp - Turn off when no motion for 15 mins
  trigger:
    platform: state
    entity_id: binary_sensor.motion_study
    to: 'off'
    for:
      minutes: 15
  condition:
    - condition: state
      entity_id: light.study_floor_lamp
      state: 'on'
    - condition: state
      entity_id: input_boolean.guest_mode
      state: 'off'
  action:
    service: light.turn_off
    entity_id: light.study_floor_lamp

- alias: Light - Corridor Sideboard - Increase brightness on motion
  trigger:
    platform: state
    entity_id: binary_sensor.motion_corridor
    to: 'on'
  action:
    service: script.light_ambient_turn_on
    data:
      light_entity: light.corridor_sideboard
      motion_sensor_entity: binary_sensor.motion_corridor

- alias: Light - Living Room - Turn on night light
  trigger:
    platform: state
    entity_id: binary_sensor.motion_corridor
    to: 'on'
  condition:
    - condition: state
      entity_id: light.living_room
      state: 'off'
    - condition: state
      entity_id: input_boolean.guest_mode
      state: 'off'
  action:
    service: script.light_ambient_turn_on
    data:
      light_entity: light.living_room
      motion_sensor_entity: binary_sensor.motion_corridor
