---

- alias: Lights - Ambient - Turn on when sunset
  mode: restart
  trigger:
    platform: state
    entity_id: binary_sensor.sun
    to: 'off'
  condition:
    condition: state
    entity_id: group.residents
    state: home
  action:
    service: script.lights_ambient_turn_on
    data:
      transition: 1800  # 30 min

- alias: Lights - Ambient - Turn off after sunrise
  mode: restart
  trigger:
    platform: state
    entity_id: binary_sensor.sun
    to: 'on'
  condition:
    condition: state
    entity_id: light.ambient
    state: 'on'
  action:
    service: script.lights_ambient_turn_off
    data:
      transition: 60  # 1 min

- alias: Lights - Ambient - Turn on when somebody came home
  trigger:
    platform: state
    entity_id: group.residents
    from: not_home
    to: home
  condition:
    condition: state
    entity_id: binary_sensor.sun
    state: 'off'
  action:
    service: script.lights_ambient_turn_on

- alias: Light - Ambient - Force off when sunlight
  mode: restart
  trigger:
    platform: state
    entity_id: light.ambient
    to: 'on'
    for:
      minutes: 30
  condition:
    - condition: state
      entity_id: binary_sensor.sun
      state: 'on'
    - condition: time
      after: '08:00:00'
  action:
    service: script.lights_ambient_turn_off
    data:
      transition: 60  # 1 min

- alias: Light - Study Desk - Turn on when home office mode on and dark
  trigger:
    - platform: state
      entity_id: input_boolean.home_office_mode
      to: 'on'
      variables:
        transition: 5
    - platform: state
      entity_id: binary_sensor.lightlevel_study_dark
      to: 'on'
      for:
        minutes: 5
      variables:
        transition: 60
  condition:
    - condition: state
      entity_id: input_boolean.home_office_mode
      state: 'on'
    - condition: state
      entity_id: group.residents
      state: home
    - condition: state
      entity_id: binary_sensor.lightlevel_study_dark
      state: 'on'
    - condition: state
      entity_id: switch.detached_light
      state: 'off'
    - "{{ not is_state('vacuum.xiaomi_vacuum_cleaner', 'cleaning') }}"
    - "{{ not is_state('vacuum.xiaomi_vacuum_cleaner', 'returning') }}"
  action:
    service: light.turn_on
    entity_id: light.study_desk
    data:
      transition: "{{ transition }}"
      brightness: 255

- alias: Light - Study Desk - Turn off when home office mode off
  trigger:
    - platform: state
      entity_id: input_boolean.home_office_mode
      to: 'off'
      variables:
        transition: 5
    - platform: state
      entity_id: binary_sensor.lightlevel_study_dark
      to: 'off'
      for:
        minutes: 30
      variables:
        transition: 60
  condition:
    condition: state
    entity_id: switch.detached_light
    state: 'off'
  action:
    service: light.turn_off
    entity_id: light.study_desk
    data:
      transition: "{{ transition }}"

- alias: Light - Study - Increase brightness on motion
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_study_occupancy
      to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.guest_mode
      state: 'off'
  action:
    service: pyscript.light_ambient_turn_on
    data:
      light_entity_id: light.study_shelf
      motion_sensor_entity_id: binary_sensor.motion_study_occupancy

- alias: Light - Study Floor Lamp - Turn off when no motion for 15 mins
  trigger:
    platform: state
    entity_id: binary_sensor.motion_study_occupancy
    to: 'off'
    for:
      minutes: 15
  condition:
    - condition: state
      entity_id: light.study_floor_lamp
      state: 'on'
    - condition: state
      entity_id: input_boolean.guest_mode
      state: 'off'
  action:
    service: light.turn_off
    entity_id: light.study_floor_lamp

- alias: Light - Study Desk - Turn off when no motion for 5 mins
  trigger:
    platform: state
    entity_id: binary_sensor.motion_study_occupancy
    to: 'off'
    for:
      minutes: 5
  condition:
    - condition: state
      entity_id: light.study_desk
      state: 'on'
    - condition: state
      entity_id: input_boolean.home_office_mode
      state: 'off'
    - condition: state
      entity_id: switch.detached_light
      state: 'off'
  action:
    service: light.turn_off
    entity_id: light.study_desk

- alias: Light - Corridor Sideboard - Increase brightness on motion
  trigger:
    platform: state
    entity_id: binary_sensor.motion_corridor_occupancy
    to: 'on'
  action:
    service: pyscript.light_ambient_turn_on
    data:
      light_entity_id: light.corridor_sideboard
      motion_sensor_entity_id: binary_sensor.motion_corridor_occupancy

- alias: Light - Living Room - Turn on night light
  trigger:
    platform: state
    entity_id: binary_sensor.motion_corridor_occupancy
    to: 'on'
  condition:
    - condition: state
      entity_id: light.living_room
      state: 'off'
    - condition: state
      entity_id: input_boolean.guest_mode
      state: 'off'
  action:
    service: pyscript.light_ambient_turn_on
    data:
      light_entity_id: light.living_room
      motion_sensor_entity_id: binary_sensor.motion_corridor_occupancy

- alias: Light - Study Shelf - Turn on night light
  trigger:
    platform: state
    entity_id: binary_sensor.motion_corridor_occupancy
    to: 'on'
  condition:
    - condition: state
      entity_id: light.study_shelf
      state: 'off'
    - condition: state
      entity_id: input_boolean.guest_mode
      state: 'off'
  action:
    service: pyscript.light_ambient_turn_on
    data:
      light_entity_id: light.study_shelf
      motion_sensor_entity_id: binary_sensor.motion_corridor_occupancy

- alias: Light - Bedroom Wardrobe - Reset after 45 mins
  trigger:
    platform: numeric_state
    entity_id: light.bedroom_wardrobe
    attribute: brightness
    above: 100
    for:
      minutes: 45
  condition:
    condition: time
    after: '12:00:00'
  action:
    service: light.turn_on
    entity_id: light.bedroom_wardrobe
    data:
      brightness: 100
      transition: 60  # 1 minute

- alias: Light - Study Shelf - Adaptive light on when home office mode off
  trigger:
    platform: state
    entity_id: input_boolean.home_office_mode
    to: 'off'
  condition:
    condition: state
    entity_id: light.study
    state: 'on'
  action:
    service: adaptive_lighting.set_manual_control
    entity_id: switch.adaptive_lighting_study
    data:
      lights: light.study
      manual_control: false

- alias: Light - Ambient - Turn off when no motion in Corridor for two hours
  trigger:
    platform: state
    entity_id: binary_sensor.motion_corridor_occupancy
    to: 'off'
    for:
      hours: 2
  condition:
    - condition: state
      entity_id: light.bedroom
      state: 'off'
    - condition: state
      entity_id: light.ambient
      state: 'on'
  action:
    service: light.turn_off
    entity_id: light.ambient
    data:
      transition: 60

- alias: Light - Study Desk - Sync color temperature with sensor
  trigger:
    platform: template
    value_template: >
      {{
        (states('sensor.light_study_color_temp') != state_attr('light.study', 'color_temp_kelvin'))
          and
        is_state('switch.adaptive_lighting_study', 'off')
          and
        is_state('light.study_desk', 'on')
      }}
  action:
    service: light.turn_on
    entity_id: light.study_desk
    data:
      transition: 2
      kelvin: "{{ states('sensor.light_study_color_temp') }}"

- alias: Light - Study Shelf - Sync color temperature with sensor
  trigger:
    platform: template
    value_template: >
      {{
        (states('sensor.light_study_color_temp') != state_attr('light.study', 'color_temp_kelvin'))
          and
        is_state('switch.adaptive_lighting_study', 'off')
          and
        is_state('light.study_shelf', 'on')
      }}
  action:
    service: light.turn_on
    entity_id: light.study_shelf
    data:
      transition: 2
      kelvin: "{{ states('sensor.light_study_color_temp') }}"

- alias: Light - Study Floor Lamp - Sync color temperature with sensor
  trigger:
    platform: template
    value_template: >
      {{
        (states('sensor.light_study_color_temp') != state_attr('light.study', 'color_temp_kelvin'))
          and
        is_state('switch.adaptive_lighting_study', 'off')
          and
        is_state('light.study_floor_lamp', 'on')
      }}
  action:
    service: light.turn_on
    entity_id: light.study_floor_lamp
    data:
      transition: 2
      kelvin: "{{ states('sensor.light_study_color_temp') }}"
