---

- alias: Lights - Turn on when sunset
  trigger:
    - platform: sun
      event: sunset
      offset: '-00:30:00'
  condition:
    - condition: state
      entity_id: group.residents
      state: home
  action:
    service: script.light_ambient_turn_on
    data:
      transition: 1800  # 30 min

- alias: Lights - Turn off after sunrise or 8 am
  trigger:
    - platform: sun
      offset: '+00:30:00'
      event: sunrise
    - platform: time
      at: '08:00:00'
  condition:
    - condition: state
      entity_id: light.ambient
      state: 'on'
    - condition: sun
      after_offset: '+00:30:00'
      after: sunrise
    - condition: time
      after: '08:00'
  action:
    service: script.light_ambient_turn_off
    data:
      transition: 60  # 1 min

- alias: Lights - Turn on when somebody came home
  trigger:
    platform: state
    entity_id: group.residents
    from: not_home
    to: home
  condition:
    - condition: sun
      after: sunset
      after_offset: '-00:30:00'
  action:
    service: script.light_ambient_turn_on
    data:
      transition: 10  # seconds

- alias: Light - Turn off when sunlight
  trigger:
    platform: state
    entity_id: light.ambient
    to: 'on'
    for:
      minutes: 30
  condition:
    - condition: sun
      before: sunset
      before_offset: '-00:30:00'
    - condition: sun
      after: sunrise
      after_offset: '00:30:00'
    - condition: time
      after: '08:00:00'
  action:
    service: script.light_ambient_turn_off
    data:
      transition: 60  # 1 min

- alias: Light Study Desk - Turn on when home office mode on and dark
  trigger:
    - platform: state
      entity_id: switch.home_office_mode
      to: 'on'
    - platform: state
      entity_id: binary_sensor.lightlevel_study_dark
      to: 'on'
      for:
        minutes: 5
  condition:
    - condition: state
      entity_id: switch.home_office_mode
      state: 'on'
    - condition: state
      entity_id: group.residents
      state: home
    - condition: state
      entity_id: binary_sensor.lightlevel_study_dark
      state: 'on'
    - "{{ not is_state('vacuum.xiaomi_vacuum_cleaner', 'cleaning') }}"
    - "{{ not is_state('vacuum.xiaomi_vacuum_cleaner', 'returning') }}"
  action:
    service: switch.turn_on
    entity_id: switch.study_lamp

- alias: Light Study Desk - Turn off when home office mode off
  trigger:
    - platform: state
      entity_id: switch.home_office_mode
      to: 'off'
    - platform: state
      entity_id: binary_sensor.lightlevel_study_dark
      to: 'off'
      for:
        minutes: 30
  action:
    service: switch.turn_off
    entity_id: switch.study_lamp

- alias: Light Study Shelf - Increase brightness on motion
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_study
      to: 'on'
  condition:
    - condition: state
      entity_id: light.study_shelf
      state: 'on'
    - "{{ not is_state('vacuum.xiaomi_vacuum_cleaner', 'cleaning') }}"
    - "{{ not is_state('vacuum.xiaomi_vacuum_cleaner', 'returning') }}"
  action:
    service: light.turn_on
    entity_id: light.study_shelf
    data:
      brightness: 200

- alias: Light Study Shelf - Decrease brightness when no motion for 30 minutes
  trigger:
    platform: state
    entity_id: binary_sensor.motion_study
    to: 'off'
    for:
      minutes: 15
  condition:
    - condition: state
      entity_id: light.study_shelf
      state: 'on'
  action:
    service: light.turn_on
    entity_id: light.study_shelf
    data:
      transition: 60  # 1 min
      brightness: 50
