---

- alias: Media Player - Stop casting on Home Group when TV on
  trigger:
    - platform: state
      entity_id: remote.living_room
      attribute: current_activity
      to: TV
    - platform: state
      entity_id: remote.living_room
      attribute: current_activity
      to: Smart TV
  condition:
    condition: not
    conditions:
      condition: state
      entity_id: media_player.home_group
      state: 'off'
  action:
    service: media_player.turn_off
    entity_id: all

- alias: Media Player - Chromecast Full Volume
  trigger:
    platform: state
    entity_id: media_player.chromecast
    from: 'off'
  condition:
    condition: numeric_state
    entity_id: media_player.chromecast
    attribute: volume_level
    below: 1
  action:
    service: media_player.volume_set
    entity_id: media_player.chromecast
    data:
      volume_level: 1.0

- alias: Media Player - Stop casting on Home Group when TV off
  trigger:
    platform: state
    entity_id: remote.living_room
    to: 'off'
  condition:
    condition: not
    conditions:
      condition: state
      entity_id: media_player.home_group
      state: 'off'
  action:
    service: media_player.turn_off
    entity_id: all
