---

- alias: Media Player - Stop casting on Home Group when TV on
  trigger:
    - platform: state
      entity_id: remote.living_room
      attribute: current_activity
      to: TV
    - platform: state
      entity_id: remote.living_room
      attribute: current_activity
      to: Smart TV
  condition:
    condition: not
    conditions:
      condition: state
      entity_id: media_player.home_group
      state: 'off'
  action:
    service: media_player.turn_off
    entity_id: all

- alias: Media Player - Chromecast Full Volume
  trigger:
    platform: state
    entity_id: media_player.chromecast
    from: 'off'
  condition:
    condition: numeric_state
    entity_id: media_player.chromecast
    attribute: volume_level
    below: 1
  action:
    service: media_player.volume_set
    entity_id: media_player.chromecast
    data:
      volume_level: 1.0

- alias: Media Player - Stop casting on Home Group when TV off
  trigger:
    platform: state
    entity_id: remote.living_room
    to: 'off'
  condition:
    condition: not
    conditions:
      condition: state
      entity_id: media_player.home_group
      state: 'off'
  action:
    service: media_player.turn_off
    entity_id: all

- alias: Media Player - Spotify Start - Increase Volume
  trigger:
    platform: state
    entity_id:
      - media_player.kitchen
      - media_player.living_room
      - media_player.study
      - media_player.bedroom
      - media_player.bathroom
      - media_player.balcony
    attribute: app_name
    to: Spotify
  action:
    service: media_player.volume_set
    data:
      entity_id: "{{ trigger.entity_id }}"
      volume_level: 0.3

- alias: Media Player - Spotify End - Decrease Volume
  trigger:
    platform: state
    entity_id:
      - media_player.kitchen
      - media_player.living_room
      - media_player.study
      - media_player.bedroom
      - media_player.bathroom
      - media_player.balcony
    attribute: app_name
    from: Spotify
  action:
    service: media_player.volume_set
    data:
      entity_id: "{{ trigger.entity_id }}"
      volume_level: 0.1
