---

- alias: Media Player - Stop casting on All Speakers when TV on
  trigger:
    platform: state
    entity_id: media_player.lg_webos_smart_tv
    to: 'on'
  condition:
    condition: not
    conditions:
      condition: state
      entity_id: media_player.all_speakers
      state: 'off'
  action:
    service: media_player.turn_off
    entity_id: media_player.all_speakers

- alias: Media Player - Stop casting on All Speakers when TV off
  trigger:
    platform: state
    entity_id: remote.living_room
    to: 'off'
  condition:
    condition: not
    conditions:
      condition: state
      entity_id: media_player.all_speakers
      state: 'off'
  action:
    service: media_player.turn_off
    entity_id: all

- alias: Media Player - Bathroom - Turn off after 1 hour
  trigger:
    platform: state
    entity_id: media_player.bathroom
    to: playing
    for:
      minutes: 60
  condition:
    condition: not
    conditions:
      condition: state
      entity_id: media_player.all_speakers
      state: playing
  action:
    service: media_player.turn_off
    entity_id: media_player.bathroom

- alias: Media Player - Adjust volume
  mode: parallel
  max: 20
  trigger:
    platform: state
    entity_id:
      - sensor.volume_kitchen
      - sensor.volume_bathroom
      - sensor.volume_bedroom
      - sensor.volume_living_room
      - sensor.volume_study
      - sensor.volume_chromecast
      - sensor.media_player_kitchen
      - sensor.media_player_bathroom
      - sensor.media_player_bedroom
      - sensor.media_player_living_room
      - sensor.media_player_study
      - sensor.media_player_chromecast
  action:
    service: pyscript.adjust_volume
    data:
      volume_sensor_entity_id: '{{ trigger.entity_id.replace("media_player.", "sensor.volume_") }}'
      media_player_entity_id: '{{ trigger.entity_id.replace("sensor.volume_", "media_player.") }}'

- alias: Media Player - All Speakers - Reset volume offset when off for 30 seconds
  trigger:
    platform: state
    entity_id: media_player.all_speakers
    to: 'off'
    for:
      seconds: 30
  action:
    service: input_number.set_value
    entity_id: input_number.volume_offset
    data:
      value: 0
