---

- alias: Media Player - Stop casting on Home Group when TV on
  trigger:
    platform: template
    value_template: >
      {{
        is_state_attr('remote.living_room', 'current_activity', 'TV')
          or
        is_state_attr('remote.living_room', 'current_activity', 'Kodi')
          or
        is_state_attr('remote.living_room', 'current_activity', 'Smart TV')
      }}
  condition:
    condition: not
    conditions:
      condition: state
      entity_id: media_player.home_group
      state: 'off'
  action:
    service: media_player.turn_off
    entity_id: all

- alias: Media Player - Chromecast Full Volume
  trigger:
    platform: state
    entity_id: media_player.chromecast
    from: 'off'
  condition:
    condition: template
    value_template: "{{ state_attr('media_player.chromecast', 'volume_level') < 1}}"
  action:
    service: media_player.volume_set
    entity_id: media_player.chromecast
    data:
      volume_level: 1.0

- alias: Media Player - Stop casting on Home Group when TV off
  trigger:
    platform: state
    entity_id: remote.living_room
    to: 'off'
  condition:
    condition: not
    conditions:
      condition: state
      entity_id: media_player.home_group
      state: 'off'
  action:
    service: media_player.turn_off
    entity_id: all
