---

- alias: Media Player - Stop casting on Home Group when TV on
  trigger:
    - platform: state
      entity_id: remote.living_room
      attribute: current_activity
      to: TV
    - platform: state
      entity_id: remote.living_room
      attribute: current_activity
      to: Smart TV
  condition:
    condition: not
    conditions:
      condition: state
      entity_id: media_player.home_group
      state: 'off'
  action:
    service: media_player.turn_off
    entity_id: all

- alias: Media Player - Chromecast Full Volume
  trigger:
    platform: state
    entity_id: media_player.chromecast
    from: 'off'
  condition:
    condition: numeric_state
    entity_id: media_player.chromecast
    attribute: volume_level
    below: 1
  action:
    service: media_player.volume_set
    entity_id: media_player.chromecast
    data:
      volume_level: 1.0

- alias: Media Player - Stop casting on Home Group when TV off
  trigger:
    platform: state
    entity_id: remote.living_room
    to: 'off'
  condition:
    condition: not
    conditions:
      condition: state
      entity_id: media_player.home_group
      state: 'off'
  action:
    service: media_player.turn_off
    entity_id: all

- alias: Media Player - Kitchen - Increase Volume on Spotify playing
  trigger:
    platform: state
    entity_id: media_player.kitchen
    attribute: app_name
    to: Spotify
  action:
    service: media_player.volume_set
    data:
      entity_id: "{{ trigger.entity_id }}"
      volume_level: 0.3

- alias: Media Player - Kitchen - Reset Volume
  trigger:
    - platform: state
      entity_id: media_player.kitchen
      to: 'off'
      for:
        seconds: 10
    - platform: state
      entity_id: media_player.kitchen
      attribute: app_name
      from: Spotify
  action:
    service: media_player.volume_set
    data:
      entity_id: "{{ trigger.entity_id }}"
      volume_level: 0.1

- alias: Media Player - Bathroom - Increase Volume on Spotify playing
  trigger:
    platform: state
    entity_id: media_player.bathroom
    attribute: app_name
    to: Spotify
  action:
    service: media_player.volume_set
    data:
      entity_id: "{{ trigger.entity_id }}"
      volume_level: 0.3

- alias: Media Player - Bathroom - Reset Volume
  trigger:
    - platform: state
      entity_id: media_player.bathroom
      to: 'off'
      for:
        seconds: 10
    - platform: state
      entity_id: media_player.bathroom
      attribute: app_name
      from: Spotify
  action:
    service: media_player.volume_set
    data:
      entity_id: "{{ trigger.entity_id }}"
      volume_level: 0.15

- alias: Media Player - Bedroom - Increase Volume on Spotify playing
  trigger:
    platform: state
    entity_id: media_player.bedroom
    attribute: app_name
    to: Spotify
  action:
    service: media_player.volume_set
    data:
      entity_id: "{{ trigger.entity_id }}"
      volume_level: 0.3

- alias: Media Player - Bedroom - Reset Volume
  trigger:
    - platform: state
      entity_id: media_player.bedroom
      to: 'off'
      for:
        seconds: 10
    - platform: state
      entity_id: media_player.bedroom
      attribute: app_name
      from: Spotify
  action:
    service: media_player.volume_set
    data:
      entity_id: "{{ trigger.entity_id }}"
      volume_level: 0.15

- alias: Media Player - Study - Increase Volume on Spotify playing
  trigger:
    platform: state
    entity_id: media_player.study
    attribute: app_name
    to: Spotify
  condition:
    condition: state
    entity_id: switch.guest_mode
    state: 'off'
  action:
    service: media_player.volume_set
    data:
      entity_id: "{{ trigger.entity_id }}"
      volume_level: 0.3

- alias: Media Player - Study - Reset Volume
  trigger:
    - platform: state
      entity_id: media_player.study
      to: 'off'
      for:
        seconds: 10
    - platform: state
      entity_id: media_player.study
      attribute: app_name
      from: Spotify
  condition:
    condition: state
    entity_id: switch.guest_mode
    state: 'off'
  action:
    service: media_player.volume_set
    data:
      entity_id: "{{ trigger.entity_id }}"
      volume_level: 0.1

- alias: Media Player - Chromecast - Increase Volume on Spotify playing
  trigger:
    platform: state
    entity_id: media_player.chromecast
    attribute: app_name
    to: Spotify
  action:
    - wait_for_trigger:
        platform: template
        value_template: >
          {{
            is_state_attr('remote.living_room', 'current_activity', 'Speakers')
              or
            is_state_attr('remote.living_room', 'current_activity', 'Chromecast')
          }}
      continue_on_timeout: false
      timeout: '00:00:30'
    - service: remote.send_command
      entity_id: remote.living_room
      data:
        device: Pioneer-AV-Receiver
        command: VolumeUp
        num_repeats: 25

- alias: Media Player - Chromecast - Reset Volume
  trigger:
    platform: state
    entity_id: media_player.chromecast
    attribute: app_name
    from: Spotify
  action:
    - wait_for_trigger:
        platform: template
        value_template: >
          {{
            not is_state_attr('remote.living_room', 'current_activity', 'Speakers')
              and
            not is_state_attr('remote.living_room', 'current_activity', 'Chromecast')
              and
            not is_state('remote.living_room', 'off')
          }}
      continue_on_timeout: false
      timeout: '00:00:30'
    - service: remote.send_command
      entity_id: remote.living_room
      data:
        device: Pioneer-AV-Receiver
        command: VolumeDown
        num_repeats: 25

- alias: Media Player - Bathroom - Turn off after 1,5 hours
  trigger:
    platform: state
    entity_id: media_player.bathroom
    to: playing
    for:
      minutes: 90
  condition:
    condition: not
    conditions:
      condition: state
      entity_id: media_player.home_group
      state: playing
  action:
    service: media_player.turn_off
    entity_id: media_player.bathroom
