---

- alias: Media Player - Stop casting on Home Group when TV on
  trigger:
    platform: state
    entity_id: media_player.lg_webos_smart_tv
    to: 'on'
  condition:
    condition: not
    conditions:
      condition: state
      entity_id: media_player.home_group
      state: 'off'
  action:
    service: media_player.turn_off
    entity_id: media_player.home_group

- alias: Media Player - Stop casting on Home Group when TV off
  trigger:
    platform: state
    entity_id: remote.living_room
    to: 'off'
  condition:
    condition: not
    conditions:
      condition: state
      entity_id: media_player.home_group
      state: 'off'
  action:
    service: media_player.turn_off
    entity_id: all

- alias: Media Player - Bathroom - Turn off after 1,5 hours
  trigger:
    platform: state
    entity_id: media_player.bathroom
    to: playing
    for:
      minutes: 90
  condition:
    condition: not
    conditions:
      condition: state
      entity_id: media_player.home_group
      state: playing
  action:
    service: media_player.turn_off
    entity_id: media_player.bathroom

- alias: Media Player - Adjust volume on slider change
  mode: parallel
  trigger:
    - platform: state
      entity_id: sensor.volume_kitchen
    - platform: state
      entity_id: sensor.volume_bathroom
    - platform: state
      entity_id: sensor.volume_chromecast
    - platform: state
      entity_id: sensor.volume_bedroom
    - platform: state
      entity_id: sensor.volume_study
  action:
    service: media_player.volume_set
    data:
      entity_id: '{{ "media_player." + trigger.entity_id[14:] }}'
      volume_level: "{{ trigger.to_state.state }}"
