---

- alias: Media Player - Stop casting on All Speakers when TV on
  trigger:
    platform: state
    entity_id: media_player.lg_webos_smart_tv
    to: 'on'
  condition:
    condition: not
    conditions:
      condition: state
      entity_id: media_player.all_speakers
      state: 'off'
  action:
    service: media_player.turn_off
    entity_id: media_player.all_speakers

- alias: Media Player - Stop casting on All Speakers when TV off
  trigger:
    platform: state
    entity_id: remote.living_room
    to: 'off'
  condition:
    condition: not
    conditions:
      condition: state
      entity_id: media_player.all_speakers
      state: 'off'
  action:
    service: media_player.turn_off
    entity_id: all

- alias: Media Player - Bathroom - Turn off after 1 hour
  trigger:
    platform: state
    entity_id: media_player.bathroom
    to: playing
    for:
      minutes: 60
  condition:
    condition: not
    conditions:
      condition: state
      entity_id: media_player.all_speakers
      state: playing
  action:
    service: media_player.turn_off
    entity_id: media_player.bathroom

- alias: Media Player - Bathroom - Turn off after 1,5 hours
  trigger:
    platform: state
    entity_id: media_player.bathroom
    to: playing
    for:
      minutes: 60
  condition:
    condition: not
    conditions:
      condition: state
      entity_id: media_player.all_speakers
      state: playing
  action:
    service: media_player.turn_off
    entity_id: media_player.bathroom

- alias: Media Player - Kitchen - Adjust volume on slider change
  mode: queued
  trigger:
    - platform: state
      entity_id: sensor.volume_kitchen
      for:
        seconds: 1
    - platform: state
      entity_id: media_player.kitchen
      from: 'off'
      for:
        seconds: 1
  action:
    service: media_player.volume_set
    entity_id: media_player.kitchen
    data:
      volume_level: "{{ states('sensor.volume_kitchen') }}"

- alias: Media Player - Bathroom - Adjust volume on slider change
  mode: queued
  trigger:
    - platform: state
      entity_id: sensor.volume_bathroom
      for:
        seconds: 1
    - platform: state
      entity_id: media_player.bathroom
      from: 'off'
      for:
        seconds: 1
  action:
    service: media_player.volume_set
    entity_id: media_player.bathroom
    data:
      volume_level: "{{ states('sensor.volume_bathroom') }}"

- alias: Media Player - Living Room - Adjust volume on slider change
  mode: queued
  trigger:
    - platform: state
      entity_id: sensor.volume_living_room
      for:
        seconds: 1
    - platform: state
      entity_id: media_player.living_room
      from: 'off'
      for:
        seconds: 1
  action:
    service: media_player.volume_set
    entity_id: media_player.living_room
    data:
      volume_level: "{{ states('sensor.volume_living_room') }}"

- alias: Media Player - Bedroom - Adjust volume on slider change
  mode: queued
  trigger:
    - platform: state
      entity_id: sensor.volume_bedroom
      for:
        seconds: 1
    - platform: state
      entity_id: media_player.bedroom
      from: 'off'
      for:
        seconds: 1
  action:
    service: media_player.volume_set
    entity_id: media_player.bedroom
    data:
      volume_level: "{{ states('sensor.volume_bedroom') }}"

- alias: Media Player - Study - Adjust volume on slider change
  mode: queued
  trigger:
    - platform: state
      entity_id: sensor.volume_study
      for:
        seconds: 1
    - platform: state
      entity_id: media_player.study
      from: 'off'
      for:
        seconds: 1
  action:
    service: media_player.volume_set
    entity_id: media_player.study
    data:
      volume_level: "{{ states('sensor.volume_study') }}"

- alias: Media Player - Chromecast - Adjust volume on slider change
  mode: queued
  trigger:
    - platform: state
      entity_id: sensor.volume_chromecast
      for:
        seconds: 1
    - platform: state
      entity_id: media_player.chromecast
      from: 'off'
      for:
        seconds: 1
  action:
    service: media_player.volume_set
    entity_id: media_player.chromecast
    data:
      volume_level: "{{ states('sensor.volume_chromecast') }}"

- alias: Media Player - All Speakers - Reset volume offset when off for 30 seconds
  trigger:
    platform: state
    entity_id: media_player.all_speakers
    to: 'off'
    for:
      seconds: 30
  action:
    service: input_number.set_value
    entity_id: input_number.volume_offset
    data:
      value: 0
