---

- alias: Mode - Home Office Mode - Turn off
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_study_desk_occupancy
      to: 'off'
      for:
        minutes: 5
    - platform: state
      entity_id: group.residents
      to: not_home
  action:
    service: input_boolean.turn_off
    entity_id: input_boolean.home_office_mode

- alias: Mode - Home Office Mode - Turn on
  trigger:
    platform: state
    entity_id: binary_sensor.motion_study_desk_occupancy
    to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.guest_mode
      state: 'off'
    - condition: state
      entity_id: person.patrick
      state: home
    - condition: state
      entity_id: input_boolean.home_office_mode
      state: 'off'
  action:
    service: input_boolean.turn_on
    entity_id: input_boolean.home_office_mode

- alias: Mode - Party Mode - Turn off after 4 hours
  trigger:
    platform: state
    entity_id: input_boolean.party_mode
    to: 'on'
    for:
      hours: 4
  action:
    - service: notify.patrick
      data:
        message: Party Mode turned off after 4 hours.
    - service: input_boolean.turn_off
      entity_id: input_boolean.party_mode

- alias: Mode - TV Mode - Sync with TV
  trigger:
    platform: state
    entity_id: media_player.lg_webos_smart_tv
  action:
    service: "input_boolean.turn_{{ trigger.to_state.state }}"
    entity_id: input_boolean.tv_mode

- alias: Mode - Guest Mode - Toggle daily vacuum when Guest Mode changed
  trigger:
    platform: state
    entity_id: input_boolean.guest_mode
  action:
    service: "input_boolean.turn_{{ trigger.to_state.state }}"
    entity_id: input_boolean.vacuum_daily_cleanup

- alias: Mode - Guest mode - Turn off Home Office Mode when Guest Mode is turned on
  trigger:
    - platform: state
      entity_id: input_boolean.guest_mode
      to: 'on'
  action:
    service: input_boolean.turn_off
    entity_id: input_boolean.home_office_mode

- alias: Mode - Party Mode - Turn on manual heating when Party Mode is turned on
  trigger:
    - platform: state
      entity_id: input_boolean.guest_mode
      to: 'on'
  action:
    service: climate.set_temperature
    data:
      entity_id: all
      temperature: 22

- alias: Mode - Party Mode - Turn off manual heating when Party Mode is turned off
  trigger:
    - platform: state
      entity_id: input_boolean.guest_mode
      to: 'on'
  action:
    service: climate.set_hvac_mode
    data:
      entity_id: all
      hvac_mode: auto

- alias: Mode - Summer Mode - Sync climate with Summer Mode
  trigger:
    platform: state
    entity_id: input_boolean.summer_mode
  action:
    service: "input_boolean.turn_{{ trigger.to_state.state }}"
    entity_id: switch.climate_all
