---

- alias: Mode - Guest Mode - Mute Study speaker
  trigger:
    platform: state
    entity_id: media_player.study
  condition:
    - condition: state
      entity_id: input_boolean.guest_mode
      state: 'on'
    - "{{ not is_state_attr('media_player.study', 'is_volume_muted', true) }}"
  action:
    service: media_player.volume_mute
    entity_id: media_player.study
    data:
      is_volume_muted: true

- alias: Mode - Guest Mode - Keep lights off
  trigger:
    platform: state
    entity_id: light.study
    to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.guest_mode
      state: 'on'
  action:
    service: light.turn_off
    entity_id: light.study

- alias: Mode - Home Office Mode - Turn off
  trigger:
    - platform: state
      entity_id: group.motion_study_desk
      to: 'off'
      for:
        minutes: 20
    - platform: state
      entity_id: group.residents
      to: 'not_home'
  action:
    service: input_boolean.turn_off
    entity_id: input_boolean.home_office_mode

- alias: Mode - Home Office Mode - Turn on
  trigger:
    platform: state
    entity_id: group.motion_study_desk
    to: 'on'
  condition:
    condition: state
    entity_id: input_boolean.guest_mode
    state: 'off'
  action:
    service: input_boolean.turn_on
    entity_id: input_boolean.home_office_mode

- alias: Mode - Party Mode - Turn off after 4 hours
  trigger:
    platform: state
    entity_id: input_boolean.party_mode
    to: 'on'
    for:
      hours: 4
  action:
    service: input_boolean.turn_off
    entity_id: input_boolean.party_mode

- alias: Mode - Party Mode - Turn on
  trigger:
    platform: state
    entity_id: input_boolean.party_mode
    to: 'on'
  action:
    - service: climate.set_temperature
      data:
        entity_id: all
        temperature: 22

- alias: Mode - Party Mode - Turn off
  trigger:
    platform: state
    entity_id: input_boolean.party_mode
    to: 'off'
  action:
    - service: climate.set_hvac_mode
      data:
        entity_id: all
        hvac_mode: auto
