---

- alias: Mode - Guest Mode - Mute Study speaker
  trigger:
    platform: state
    entity_id: media_player.study
  condition:
    - condition: state
      entity_id: input_boolean.guest_mode
      state: 'on'
    - "{{ not is_state_attr('media_player.study', 'is_volume_muted', true) }}"
  action:
    service: media_player.volume_mute
    entity_id: media_player.study
    data:
      is_volume_muted: true

- alias: Mode - Home Office Mode - Turn off
  trigger:
    platform: numeric_state
    entity_id: sensor.plug_study_monitor
    below: 15
    for:
      minutes: 5
  action:
    service: input_boolean.turn_off
    entity_id: input_boolean.home_office_mode

- alias: Mode - Home Office Mode - Turn on
  trigger:
    platform: numeric_state
    entity_id: sensor.plug_study_monitor
    above: 15
  action:
    service: input_boolean.turn_on
    entity_id: input_boolean.home_office_mode
