---

- alias: Mode - Guest Mode - Mute Study speaker
  trigger:
    platform: state
    entity_id: media_player.study
  condition:
    - condition: state
      entity_id: input_boolean.guest_mode
      state: 'on'
    - "{{ not is_state_attr('media_player.study', 'is_volume_muted', true) }}"
  action:
    service: media_player.volume_mute
    entity_id: media_player.study
    data:
      is_volume_muted: true

- alias: Mode - Home Office Mode - Turn off
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_study_desk
      to: 'off'
      for:
        minutes: 20
    - platform: state
      entity_id: group.residents
      to: not_home
  action:
    service: input_boolean.turn_off
    entity_id: input_boolean.home_office_mode

- alias: Mode - Home Office Mode - Turn on
  trigger:
    platform: state
    entity_id: binary_sensor.motion_study_desk
    to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.guest_mode
      state: 'off'
    - condition: state
      entity_id: group.residents
      state: home
  action:
    service: input_boolean.turn_on
    entity_id: input_boolean.home_office_mode

- alias: Mode - Party Mode - Turn off after 4 hours
  trigger:
    platform: state
    entity_id: input_boolean.party_mode
    to: 'on'
    for:
      hours: 4
  action:
    service: input_boolean.turn_off
    entity_id: input_boolean.party_mode

- alias: Mode - Party Mode - Turn on
  trigger:
    platform: state
    entity_id: input_boolean.party_mode
    to: 'on'
  action:
    - service: climate.set_temperature
      data:
        entity_id: all
        temperature: 22

- alias: Mode - Party Mode - Turn off
  trigger:
    platform: state
    entity_id: input_boolean.party_mode
    to: 'off'
  action:
    - service: climate.set_hvac_mode
      data:
        entity_id: all
        hvac_mode: auto

- alias: Mode - TV Mode - Turn on when watching TV
  trigger:
    platform: state
    entity_id: media_player.lg_webos_smart_tv
    to: 'on'
  action:
    service: input_boolean.turn_on
    entity_id: input_boolean.tv_mode

- alias: Mode - TV Mode - Turn off when finished watching TV
  trigger:
    platform: state
    entity_id: media_player.lg_webos_smart_tv
    to: 'off'
  condition:
    condition: state
    entity_id: input_boolean.tv_mode
    state: 'on'
  action:
    service: input_boolean.turn_off
    entity_id: input_boolean.tv_mode

- alias: Mode - TV Mode - Dim lights when TV Mode on
  trigger:
    - platform: state
      entity_id: input_boolean.tv_mode
      to: 'on'
  condition:
    condition: state
    entity_id: light.living_room
    state: 'on'
  action:
    - service: input_text.set_value
      entity_id: input_text.old_brightness_living_room_couch
      data:
        value: "{{ state_attr('light.living_room_couch', 'brightness') }}"
    - service: light.turn_on
      entity_id: light.living_room
      data:
        brightness: 80
        transition: 60
    - service: input_text.set_value
      entity_id: input_text.old_brightness_living_room_tv
      data:
        value: "{{ state_attr('light.living_room_tv', 'brightness') }}"
    - service: light.turn_on
      entity_id: light.living_room_tv
      data:
        brightness: 80
        transition: 60

- alias: Mode - TV Mode - Increase light brightness when TV Mode off
  trigger:
    - platform: state
      entity_id: input_boolean.tv_mode
      to: 'off'
  condition:
    - condition: state
      entity_id: light.living_room
      state: 'on'
    - "{{ states('input_text.old_brightness_living_room_couch') != '-' }}"
    - "{{ states('input_text.old_brightness_living_room_tv') != '-' }}"
  action:
    - service: light.turn_on
      entity_id: light.living_room
      data:
        brightness: "{{ states('input_text.old_brightness_living_room_couch') }}"
        transition: 10
    - service: input_text.set_value
      entity_id: input_text.old_brightness_living_room_couch
      data:
        value: '-'
    - service: light.turn_on
      entity_id: light.living_room_tv
      data:
        brightness: "{{ states('input_text.old_brightness_living_room_tv') }}"
        transition: 10
    - service: input_text.set_value
      entity_id: input_text.old_brightness_living_room_tv
      data:
        value: '-'
