---

- alias: Mode - Guest Mode - Mute Study speaker
  trigger:
    platform: state
    entity_id: media_player.study
  condition:
    - condition: state
      entity_id: input_boolean.guest_mode
      state: 'on'
    - "{{ not is_state_attr('media_player.study', 'is_volume_muted', true) }}"
  action:
    service: media_player.volume_mute
    entity_id: media_player.study
    data:
      is_volume_muted: true
