---

- alias: MQTT Broker - Send notification when offline
  trigger:
    platform: state
    entity_id: binary_sensor.mqtt_broker_health
    to: 'off'
    for:
      minutes: 5
  action:
    service: notify.patrick
    data:
      title: MQTT Broker
      message: MQTT Broker is offline

- alias: Zigbee2mqtt - Restart if device is unavailable
  trigger:
    platform: template
    value_template: "{{ is_state('binary_sensor.motion_corridor_left_occupancy', 'unavailable') }}"
    for:
      minutes: 1
  action:
    - service: mqtt.publish
      data:
        topic: zigbee2mqtt/bridge/request/restart
        qos: 1
    - service: notify.patrick
      data:
        title: MQTT is unavailable
        message: Restarting zigbee2mqtt
    - wait_for_trigger:
        platform: state
        entity_id: binary_sensor.motion_corridor_left_occupancy
        from: 'unavailable'
      continue_on_timeout: false
      timeout: '0:01:00'
    - service: notify.patrick
      data:
        title: MQTT is available again
        message: After restarting zigbee2mqtt
