---

- alias: MQTT Broker - Send notification when offline
  trigger:
    platform: state
    entity_id: binary_sensor.mqtt_broker_health
    to: 'off'
    for:
      minutes: 5
  action:
    service: notify.patrick
    data:
      title: MQTT Broker
      message: MQTT Broker is offline
