---

- alias: Notification - All - Summer Mode - Thermostat turned on
  mode: parallel
  trigger:
    - platform: state
      entity_id: climate.kitchen
      from: 'off'
      for:
        minutes: 1
    - platform: state
      entity_id: climate.living_room
      from: 'off'
      for:
        minutes: 1
    - platform: state
      entity_id: climate.bedroom
      from: 'off'
      for:
        minutes: 1
    - platform: state
      entity_id: climate.study
      from: 'off'
      for:
        minutes: 1
    - platform: state
      entity_id: climate.toilet
      from: 'off'
      for:
        minutes: 1
    - platform: state
      entity_id: climate.bathroom
      from: 'off'
      for:
        minutes: 1
  condition:
    condition: state
    entity_id: input_boolean.summer_mode
    state: 'on'
  action:
    service: notify.patrick
    data:
      title: Thermostat
      message: Thermostat in {{ trigger.to_state.name }} turned on.

- alias: Notification - All - Thermostat turned on
  mode: parallel
  trigger:
    - platform: state
      entity_id: climate.kitchen
      to: heat
      for:
        minutes: 1
    - platform: state
      entity_id: climate.living_room
      to: heat
      for:
        minutes: 1
    - platform: state
      entity_id: climate.bedroom
      to: heat
      for:
        minutes: 1
    - platform: state
      entity_id: climate.study
      to: heat
      for:
        minutes: 1
    - platform: state
      entity_id: climate.toilet
      to: heat
      for:
        minutes: 1
    - platform: state
      entity_id: climate.bathroom
      to: heat
      for:
        minutes: 1
  condition:
    condition: state
    entity_id: input_boolean.summer_mode
    state: 'off'
  action:
    service: notify.patrick
    data:
      title: Thermostat
      message: Thermostat in {{ trigger.to_state.name }} was set to {{ state_attr(trigger.entity_id, 'temperature') }}°C.

- alias: Notification - Device Tracker not working for Patrick
  trigger:
    platform: template
    value_template: >
      {{
        states('device_tracker.tado_patricks_iphone')
          !=
        states('device_tracker.patricks_iphone')
      }}
    for:
      hours: 1
  action:
    service: notify.patrick
    data:
      title: Device Tracker
      message: Patrick's device tracker is out of sync

- alias: Notification - Expiring SSL Certificate
  trigger:
    platform: numeric_state
    entity_id: sensor.cert_expiry_days_ha
    below: 5
  action:
    service: notify.patrick
    data:
      title: SSL Certificate
      message: HA SSL certificate exipres in less than 5 days.
