---

- alias: Notification - Summer Mode - Thermostat Kitchen on
  trigger:
    platform: state
    entity_id: binary_sensor.thermostat_kitchen
    from: 'off'
    to: 'on'
  condition:
    condition: state
    entity_id: input_boolean.summer_mode
    state: 'on'
  action:
    service: notify.patrick
    data:
      title: Thermostat
      message: Thermostat in Kitchen turned on.

- alias: Notification - Summer Mode - Thermostat Living Room on
  trigger:
    platform: state
    entity_id: binary_sensor.thermostat_living_room
    from: 'off'
    to: 'on'
  condition:
    condition: state
    entity_id: input_boolean.summer_mode
    state: 'on'
  action:
    service: notify.patrick
    data:
      title: Thermostat
      message: Thermostat in Living Room turned on.

- alias: Notification - Summer Mode - Thermostat Study on
  trigger:
    platform: state
    entity_id: binary_sensor.thermostat_study
    from: 'off'
    to: 'on'
  condition:
    condition: state
    entity_id: input_boolean.summer_mode
    state: 'on'
  action:
    service: notify.patrick
    data:
      title: Thermostat
      message: Thermostat in Study turned on.

- alias: Notification - Summer Mode - Thermostat Bedroom on
  trigger:
    platform: state
    entity_id: binary_sensor.thermostat_bedroom
    from: 'off'
    to: 'on'
  condition:
    condition: state
    entity_id: input_boolean.summer_mode
    state: 'on'
  action:
    service: notify.patrick
    data:
      title: Thermostat
      message: Thermostat in Bedroom turned on.

- alias: Notification - Summer Mode - Thermostat Bathroom on
  trigger:
    platform: state
    entity_id: binary_sensor.thermostat_bathroom
    from: 'off'
    to: 'on'
  condition:
    condition: state
    entity_id: input_boolean.summer_mode
    state: 'on'
  action:
    service: notify.patrick
    data:
      title: Thermostat
      message: Thermostat in Bathroom turned on.

- alias: Notification - Thermostat Bathroom set to heat
  trigger:
    platform: state
    entity_id: climate.bathroom
    to: heat
  condition:
    condition: state
    entity_id: input_boolean.summer_mode
    state: 'off'
  action:
    service: notify.patrick
    data:
      title: Thermostat
      message: Thermostat in Bathroom was set to 'heat'.

- alias: Notification - Thermostat Bedroom set to heat
  trigger:
    platform: state
    entity_id: climate.bedroom
    to: heat
  condition:
    condition: state
    entity_id: input_boolean.summer_mode
    state: 'off'
  action:
    service: notify.patrick
    data:
      title: Thermostat
      message: Thermostat in Bedroom was set to 'heat'.

- alias: Notification - Thermostat Study set to heat
  trigger:
    platform: state
    entity_id: climate.study
    to: heat
  condition:
    - condition: state
      entity_id: input_boolean.summer_mode
      state: 'off'
    - condition: state
      entity_id: input_boolean.thermostat_study_triggered_by_motion
      state: 'off'
  action:
    service: notify.patrick
    data:
      title: Thermostat
      message: Thermostat in Study was set to 'heat'.

- alias: Notification - Thermostat Living Room set to heat
  trigger:
    platform: state
    entity_id: climate.living_room
    to: heat
  condition:
    condition: state
    entity_id: input_boolean.summer_mode
    state: 'off'
  action:
    service: notify.patrick
    data:
      title: Thermostat
      message: Thermostat in Living Room was set to 'heat'.

- alias: Notification - Thermostat Kitchen set to heat
  trigger:
    platform: state
    entity_id: climate.kitchen
    to: heat
  condition:
    condition: state
    entity_id: input_boolean.summer_mode
    state: 'off'
  action:
    service: notify.patrick
    data:
      title: Thermostat
      message: Thermostat in Kitchen was set to 'heat'.

- alias: Notification - Device Tracker not working for Patrick
  trigger:
    platform: template
    value_template: >
      {{
        states('device_tracker.tado_patricks_iphone')
          !=
        states('device_tracker.patricks_iphone')
      }}
    for:
      hours: 1
  action:
    service: notify.patrick
    data:
      title: Device Tracker
      message: Patrick's device tracker is out of sync

- alias: Notification - Expiring SSL Certificate
  trigger:
    platform: numeric_state
    entity_id: sensor.cert_expiry_days_ha
    below: 5
  action:
    service: notify.patrick
    data:
      title: SSL Certificate
      message: HA SSL certificate exipres in less than 5 days.

- alias: Notification - Dishwasher running too long
  trigger:
    platform: numeric_state
    entity_id: sensor.plug_kitchen_dishwasher
    above: 0
    for:
      hours: 3
  action:
    service: notify.patrick
    data:
      title: Dishwasher
      message: Dishwasher has been running for more than 3 hours!
