---

- alias: Notification - All - Summer Mode - Thermostat turned on
  mode: parallel
  trigger:
    - platform: state
      entity_id: climate.kitchen
      to:
        - auto
        - heat
      for:
        minutes: 1
    - platform: state
      entity_id: climate.living_room
      to:
        - auto
        - heat
      for:
        minutes: 1
    - platform: state
      entity_id: climate.bedroom
      to:
        - auto
        - heat
      for:
        minutes: 1
    - platform: state
      entity_id: climate.study
      to:
        - auto
        - heat
      for:
        minutes: 1
    - platform: state
      entity_id: climate.toilet
      to:
        - auto
        - heat
      for:
        minutes: 1
    - platform: state
      entity_id: climate.bathroom
      to:
        - auto
        - heat
      for:
        minutes: 1
  condition:
    condition: state
    entity_id: input_boolean.summer_mode
    state: 'on'
  action:
    service: notify.patrick
    data:
      title: Thermostat
      message: Thermostat in {{ trigger.to_state.name }} turned on.

- alias: Notification - All - Thermostat turned on
  mode: parallel
  trigger:
    - platform: state
      entity_id: climate.kitchen
      to: heat
      for:
        minutes: 1
    - platform: state
      entity_id: climate.living_room
      to: heat
      for:
        minutes: 1
    - platform: state
      entity_id: climate.bedroom
      to: heat
      for:
        minutes: 1
    - platform: state
      entity_id: climate.study
      to: heat
      for:
        minutes: 1
    - platform: state
      entity_id: climate.toilet
      to: heat
      for:
        minutes: 1
    - platform: state
      entity_id: climate.bathroom
      to: heat
      for:
        minutes: 1
  condition:
    condition: state
    entity_id: input_boolean.summer_mode
    state: 'off'
  action:
    service: notify.patrick
    data:
      title: Thermostat
      message: Thermostat in {{ trigger.to_state.name }} was set to {{ state_attr(trigger.entity_id, 'temperature') }}°C.

- alias: Notification - Device Tracker not working for Patrick
  trigger:
    platform: template
    value_template: >
      {{
        states('device_tracker.tado_patricks_iphone')
          !=
        states('device_tracker.router_patricks_iphone')
          !=
        states('device_tracker.icloud_patricks_iphone')
          !=
        states('device_tracker.icloud_patricks_apple_watch')
      }}
    for:
      hours: 1
  action:
    service: notify.patrick
    data:
      title: Device Tracker
      message: Patrick's device tracker is out of sync

- alias: Notification - Device Tracker not working for Sandra
  trigger:
    platform: template
    value_template: >
      {{
        states('device_tracker.router_iphone_von_sandra')
          !=
        states('device_tracker.icloud_sandras_iphone')
          !=
        states('device_tracker.icloud_sandras_apple_watch')
      }}
    for:
      hours: 1
  action:
    service: notify.patrick
    data:
      title: Device Tracker
      message: Sandra's device tracker is out of sync

- alias: Notification - Expiring SSL Certificate
  trigger:
    platform: numeric_state
    entity_id: sensor.cert_expiry_days_ha
    below: 5
  action:
    service: notify.patrick
    data:
      title: SSL Certificate
      message: HA SSL certificate exipres in less than 5 days.

- alias: Notification - Monitor not in sync with Home Office mode
  trigger:
    platform: template
    value_template: >
      {{
        states('input_boolean.home_office_mode')
          !=
        states('switch.plug_study_monitor')
      }}
    for:
      minutes: 5
  action:
    service: notify.patrick
    data:
      title: Device Tracker
      message: Monitor is not in sync with Home Office mode
