---

- alias: Notification - New HA release available
  trigger:
    - platform: state
      entity_id: binary_sensor.updater
      to: 'on'
  action:
    - service: notify.pushbullet
      data:
        title: Home Assistant
        message: >
          Home Assistant update available from {{ states('sensor.current_version') }}
          to {{ state_attr('binary_sensor.updater', 'newest_version') }}.
          Release notes: {{ state_attr('binary_sensor.updater', 'release_notes') }}
        target: device/OnePlus 7 Pro

- alias: Notification - Summer Mode - Thermostat Kitchen on
  trigger:
    platform: state
    entity_id: binary_sensor.thermostat_kitchen
    from: 'off'
    to: 'on'
  condition:
    condition: state
    entity_id: input_boolean.summer_mode
    state: 'on'
  action:
    service: notify.pushbullet
    data:
      title: Home Assistant
      message: Thermostat in Kitchen turned on.
      target: device/OnePlus 7 Pro

- alias: Notification - Summer Mode - Thermostat Living Room on
  trigger:
    platform: state
    entity_id: binary_sensor.thermostat_living_room
    from: 'off'
    to: 'on'
  condition:
    condition: state
    entity_id: input_boolean.summer_mode
    state: 'on'
  action:
    service: notify.pushbullet
    data:
      title: Home Assistant
      message: Thermostat in Living Room turned on.
      target: device/OnePlus 7 Pro

- alias: Notification - Summer Mode - Thermostat Study on
  trigger:
    platform: state
    entity_id: binary_sensor.thermostat_study
    from: 'off'
    to: 'on'
  condition:
    condition: state
    entity_id: input_boolean.summer_mode
    state: 'on'
  action:
    service: notify.pushbullet
    data:
      title: Home Assistant
      message: Thermostat in Study turned on.
      target: device/OnePlus 7 Pro

- alias: Notification - Summer Mode - Thermostat Bedroom on
  trigger:
    platform: state
    entity_id: binary_sensor.thermostat_bedroom
    from: 'off'
    to: 'on'
  condition:
    condition: state
    entity_id: input_boolean.summer_mode
    state: 'on'
  action:
    service: notify.pushbullet
    data:
      title: Home Assistant
      message: Thermostat in Bedroom turned on.
      target: device/OnePlus 7 Pro

- alias: Notification - Summer Mode - Thermostat Bathroom on
  trigger:
    platform: state
    entity_id: binary_sensor.thermostat_bathroom
    from: 'off'
    to: 'on'
  condition:
    condition: state
    entity_id: input_boolean.summer_mode
    state: 'on'
  action:
    service: notify.pushbullet
    data:
      title: Home Assistant
      message: Thermostat in Bathroom turned on.
      target: device/OnePlus 7 Pro

- alias: Notification - Thermostat Bathroom set to heat
  trigger:
    platform: template
    value_template: "{{ is_state('climate.bathroom', 'heat') }}"
  condition:
    condition: state
    entity_id: input_boolean.summer_mode
    state: 'off'
  action:
    service: notify.pushbullet
    data:
      title: Home Assistant
      message: Thermostat in Bathroom was set to 'heat'.
      target: device/OnePlus 7 Pro

- alias: Notification - Thermostat Bedroom set to heat
  trigger:
    platform: template
    value_template: "{{ is_state('climate.bedroom', 'heat') }}"
  condition:
    condition: state
    entity_id: input_boolean.summer_mode
    state: 'off'
  action:
    service: notify.pushbullet
    data:
      title: Home Assistant
      message: Thermostat in Bedroom was set to 'heat'.
      target: device/OnePlus 7 Pro

- alias: Notification - Thermostat Study set to heat
  trigger:
    platform: template
    value_template: "{{ is_state('climate.study', 'heat') }}"
  condition:
    condition: state
    entity_id: input_boolean.summer_mode
    state: 'off'
  action:
    service: notify.pushbullet
    data:
      title: Home Assistant
      message: Thermostat in Study was set to 'heat'.
      target: device/OnePlus 7 Pro

- alias: Notification - Thermostat Living Room set to heat
  trigger:
    platform: template
    value_template: "{{ is_state('climate.living_room', 'heat') }}"
  condition:
    condition: state
    entity_id: input_boolean.summer_mode
    state: 'off'
  action:
    service: notify.pushbullet
    data:
      title: Home Assistant
      message: Thermostat in Living Room was set to 'heat'.
      target: device/OnePlus 7 Pro

- alias: Notification - Thermostat Kitchen set to heat
  trigger:
    platform: template
    value_template: "{{ is_state('climate.kitchen', 'heat') }}"
  condition:
    condition: state
    entity_id: input_boolean.summer_mode
    state: 'off'
  action:
    service: notify.pushbullet
    data:
      title: Home Assistant
      message: Thermostat in Kitchen was set to 'heat'.
      target: device/OnePlus 7 Pro

- alias: Notification - Device Tracker not working for Patrick
  trigger:
    platform: template
    value_template: >
      {{
        is_state('device_tracker.tado_patrick_oneplus7pro', 'not_home')
          and
        is_state('device_tracker.wifi_patrick_oneplus7pro', 'home')
      }}
    for:
      hours: 1
  action:
    service: notify.pushbullet
    data:
      title: Home Assistant
      message: Patrick's device tracker is out of sync
      target: device/OnePlus 7 Pro

- alias: Notification - Device Tracker not working for Sandra
  trigger:
    platform: template
    value_template: >
      {{
        is_state('device_tracker.tado_sandra_iphone', 'not_home')
          and
        is_state('device_tracker.wifi_sandra_iphone', 'home')
      }}
    for:
      hours: 1
  action:
    service: notify.pushbullet
    data:
      title: Home Assistant
      message: Sandra's device tracker is out of sync
      target: device/OnePlus 7 Pro

- alias: Notification - Expiring SSL Certificate
  trigger:
    platform: numeric_state
    entity_id: !secret sensor_ssl_cert_ha_expiry
    below: 5
  action:
    service: notify.pushbullet
    data:
      title: Home Assistant
      message: "HA SSL certificate exipres in less than 5 days."
      target: device/OnePlus 7 Pro
