---

- alias: Notification - New HA release available
  trigger:
    - platform: state
      entity_id: binary_sensor.updater
      to: 'on'
  action:
    - service: notify.pushbullet
      data_template:
        title: Home Assistant
        message: >
          Home Assistant update available from {{ states('sensor.current_version') }}
          to {{ state_attr('binary_sensor.updater', 'newest_version') }}.
          Release notes: {{ state_attr('binary_sensor.updater', 'release_notes') }}
        target: device/OnePlus 7 Pro

- alias: Notification - Summer Mode - Thermostat Kitchen on
  trigger:
    platform: state
    entity_id: binary_sensor.thermostat_kitchen
    from: 'off'
    to: 'on'
  condition:
    condition: state
    entity_id: input_boolean.summer_mode
    state: 'on'
  action:
    service: notify.pushbullet
    data:
      title: Home Assistant
      message: Thermostat in Kitchen turned on.
      target: device/OnePlus 7 Pro

- alias: Notification - Summer Mode - Thermostat Living Room on
  trigger:
    platform: state
    entity_id: binary_sensor.thermostat_living_room
    from: 'off'
    to: 'on'
  condition:
    condition: state
    entity_id: input_boolean.summer_mode
    state: 'on'
  action:
    service: notify.pushbullet
    data:
      title: Home Assistant
      message: Thermostat in Living Room turned on.
      target: device/OnePlus 7 Pro

- alias: Notification - Summer Mode - Thermostat Study on
  trigger:
    platform: state
    entity_id: binary_sensor.thermostat_study
    from: 'off'
    to: 'on'
  condition:
    condition: state
    entity_id: input_boolean.summer_mode
    state: 'on'
  action:
    service: notify.pushbullet
    data:
      title: Home Assistant
      message: Thermostat in Study turned on.
      target: device/OnePlus 7 Pro

- alias: Notification - Summer Mode - Thermostat Bedroom on
  trigger:
    platform: state
    entity_id: binary_sensor.thermostat_bedroom
    from: 'off'
    to: 'on'
  condition:
    condition: state
    entity_id: input_boolean.summer_mode
    state: 'on'
  action:
    service: notify.pushbullet
    data:
      title: Home Assistant
      message: Thermostat in Bedroom turned on.
      target: device/OnePlus 7 Pro

- alias: Notification - Summer Mode - Thermostat Bathroom on
  trigger:
    platform: state
    entity_id: binary_sensor.thermostat_bathroom
    from: 'off'
    to: 'on'
  condition:
    condition: state
    entity_id: input_boolean.summer_mode
    state: 'on'
  action:
    service: notify.pushbullet
    data:
      title: Home Assistant
      message: Thermostat in Bathroom turned on.
      target: device/OnePlus 7 Pro

- alias: Notification - Thermostat Bathroom set to heat
  trigger:
    platform: template
    value_template: "{{ is_state('climate.bathroom', 'heat') }}"
  condition:
    condition: state
    entity_id: input_boolean.summer_mode
    state: 'off'
  action:
    service: notify.pushbullet
    data:
      title: Home Assistant
      message: Thermostat in Bathroom was set to 'heat'.
      target: device/OnePlus 7 Pro

- alias: Notification - Thermostat Bedroom set to heat
  trigger:
    platform: template
    value_template: "{{ is_state('climate.bedroom', 'heat') }}"
  condition:
    condition: state
    entity_id: input_boolean.summer_mode
    state: 'off'
  action:
    service: notify.pushbullet
    data:
      title: Home Assistant
      message: Thermostat in Bedroom was set to 'heat'.
      target: device/OnePlus 7 Pro

- alias: Notification - Thermostat Study set to heat
  trigger:
    platform: template
    value_template: "{{ is_state('climate.study', 'heat') }}"
  condition:
    condition: state
    entity_id: input_boolean.summer_mode
    state: 'off'
  action:
    service: notify.pushbullet
    data:
      title: Home Assistant
      message: Thermostat in Study was set to 'heat'.
      target: device/OnePlus 7 Pro

- alias: Notification - Thermostat Living Room set to heat
  trigger:
    platform: template
    value_template: "{{ is_state('climate.living_room', 'heat') }}"
  condition:
    condition: state
    entity_id: input_boolean.summer_mode
    state: 'off'
  action:
    service: notify.pushbullet
    data:
      title: Home Assistant
      message: Thermostat in Living Room was set to 'heat'.
      target: device/OnePlus 7 Pro

- alias: Notification - Thermostat Kitchen set to heat
  trigger:
    platform: template
    value_template: "{{ is_state('climate.kitchen', 'heat') }}"
  condition:
    condition: state
    entity_id: input_boolean.summer_mode
    state: 'off'
  action:
    service: notify.pushbullet
    data:
      title: Home Assistant
      message: Thermostat in Kitchen was set to 'heat'.
      target: device/OnePlus 7 Pro

- alias: Notification - Thermostat Living Room on and window open
  trigger:
    platform: state
    entity_id: binary_sensor.thermostat_living_room_warning
    from: 'off'
    to: 'on'
    for:
      minutes: 1
  action:
    service: notify.pushbullet
    data:
      title: Home Assistant
      message: Thermostat in Living Room on and window open.
      target: device/OnePlus 7 Pro

- alias: Notification - Thermostat Bedroom on and window open
  trigger:
    platform: state
    entity_id: binary_sensor.thermostat_bedroom_warning
    from: 'off'
    to: 'on'
    for:
      minutes: 1
  action:
    service: notify.pushbullet
    data:
      title: Home Assistant
      message: Thermostat in Bedroom on and window open.
      target: device/OnePlus 7 Pro

- alias: Notification - Thermostat Bathroom on and window open
  trigger:
    platform: state
    entity_id: binary_sensor.thermostat_bathroom_warning
    from: 'off'
    to: 'on'
    for:
      minutes: 1
  action:
    service: notify.pushbullet
    data:
      title: Home Assistant
      message: Thermostat in Bathroom on and window open.
      target: device/OnePlus 7 Pro

- alias: Notification - Thermostat Study on and window open
  trigger:
    platform: state
    entity_id: binary_sensor.thermostat_study_warning
    from: 'off'
    to: 'on'
    for:
      minutes: 1
  action:
    service: notify.pushbullet
    data:
      title: Home Assistant
      message: Thermostat in Study on and window open.
      target: device/OnePlus 7 Pro

- alias: Notification - Thermostat Kitchen on and window open
  trigger:
    platform: state
    entity_id: binary_sensor.thermostat_kitchen_warning
    from: 'off'
    to: 'on'
    for:
      minutes: 1
  action:
    service: notify.pushbullet
    data:
      title: Home Assistant
      message: Thermostat in Kitchen on and window open.
      target: device/OnePlus 7 Pro

- alias: Notification - Device Tracker not working when Person 1 not home for 2 days
  trigger:
    platform: state
    entity_id: person.patrick
    to: not_home
    for:
      days: 2
  action:
    service: notify.pushbullet
    data_template:
      title: Home Assistant
      message: Person 1 state has been 'not_home' for 2 days sraight. Please check device tracker settings.
      target: device/OnePlus 7 Pro

- alias: Notification - Device Tracker not working when Person 2 not home for 2 days
  trigger:
    platform: state
    entity_id: person.sandra
    to: not_home
    for:
      days: 2
  action:
    service: notify.pushbullet
    data_template:
      title: Home Assistant
      message: Person 2 state has been 'not_home' for 2 days sraight. Please check device tracker settings.
      target: device/OnePlus 7 Pro
