---

- alias: Notification - New HA release available
  trigger:
    - platform: state
      entity_id: binary_sensor.updater
      from: 'off'
      to: 'on'
  action:
    - service: notify.pushbullet
      data_template:
        title: Home Assistant
        message: >
          New release available: {{ state_attr('binary_sensor.updater', 'newest_version') }}
          Version running: {{ states('sensor.current_version') }}
          Release notes: {{ state_attr('binary_sensor.updater', 'release_notes') }}
        target: device/OnePlus 7 Pro

- alias: Notification - Summer Mode - Heating on
  trigger:
    platform: state
    entity_id: switch.climate_all
    from: 'off'
  condition:
    condition: state
    entity_id: input_boolean.summer_mode
    state: 'on'
  action:
    - service: notify.pushbullet
      data_template:
        title: Home Assistant
        message: Thermostat in {{ expand('group.climate_all') | rejectattr('state','eq','off') | map(attribute='friendly_name') | join(', ') }} turned on
        target: device/OnePlus 7 Pro
