---
- alias: Residents - Left home
  trigger:
  - platform: state
    entity_id: group.residents
    from: home
    to: not_home
  action:
  - service: light.turn_off
    entity_id: light.all
  - service: media_player.turn_off
    entity_id: all
  - service: remote.turn_off
    entity_id: all

- alias: Residents - Came home
  trigger:
  - entity_id: group.residents
    from: not_home
    platform: state
    to: home
  action:
  - service: remote.turn_on  # TODO use switch!
    entity_id: remote.living_room
    data:
      activity: Speakers
  - service: media_player.play_media
    entity_id: media_player.home_group
    data:
      media_content_id: http://nrj.de/muenchen
      media_content_type: music
