---
- alias: Residents - Left home
  trigger:
    - platform: state
      entity_id: group.residents
      from: home
      to: not_home
  action:
    - service: media_player.turn_off
      entity_id: all
    - service: remote.turn_off
      entity_id: all

- alias: Residents - Came home
  trigger:
    - platform: state
      entity_id: group.residents
      from: not_home
      to: home
  action:
    service: switch.turn_on
    entity_id: switch.radio_puls

- alias: Residents - Notify Resident Guest Mode still on
  trigger:
    - platform: time
      at: '10:00:00'
    - platform: state
      entity_id: input_boolean.person_guest
      to: 'on'
      for:
        hours: 4
  condition:
    condition: state
    entity_id: input_boolean.person_guest
    state: 'on'
  action:
    service: notify.patrick
    data:
      title: Residents - Guest Mode
      message: Manual Resident Guest Mode is still on.

- alias: Residents - Sync guest with input boolean
  mode: queued
  trigger:
    platform: state
    entity_id: input_boolean.person_guest
  action:
    service: device_tracker.see
    data:
      dev_id: guest
      location_name: "{{ 'home' if is_state(trigger.entity_id, 'on') else 'not_home' }}"
      source_type: router
