---

- alias: Plant - Musaceae - Unavailable
  trigger:
    platform: state
    entity_id: sensor.musaceae_temperature
    for: '24:00:00'
    to: unavailable
  action:
    service: notify.patrick
    data:
      title: Plant
      message: Musaceae 🍌🌴 unavailable since 24 hours

- alias: Plant - Musaceae - Problem
  trigger:
    platform: time
    at: "20:00"
  condition:
    condition: template
    value_template: >
      {{
        is_state('plant.musaceae', 'problem')
          and
        not is_state('sensor.musaceae_temperature', 'unavailable')
          and
        not is_state('sensor.musaceae_temperature', 'unknown')
      }}
  action:
    service: notify.all
    data:
      title: Plant
      message: >
        Musaceae 🍌🌴 needs love: {{ state_attr('plant.musaceae', 'problem') }}
      data:
        clickAction: /lovelace/plants
        url: /lovelace/plants
