---

- alias: Plug - Monitor - Turn on with home office mode when Patrick home
  trigger:
    - platform: state
      entity_id: input_boolean.home_office_mode
      to: 'on'
    - platform: state
      entity_id: person.patrick
      to: home
  condition:
    - condition: state
      entity_id: person.patrick
      state: home
    - condition: state
      entity_id: input_boolean.home_office_mode
      state: 'on'
  action:
    service: switch.turn_on
    entity_id: switch.monitor

- alias: Plug - Monitor - Turn off with home office mode
  trigger:
    - platform: state
      entity_id: input_boolean.home_office_mode
      to: 'off'
    - platform: state
      entity_id: person.patrick
      to: not_home
  action:
    service: switch.turn_off
    entity_id: switch.monitor
