---

- alias: Plug - Monitor - Sync with home office mode
  trigger:
    platform: state
    entity_id: input_boolean.home_office_mode
  action:
    service: "switch.turn_{{ trigger.to_state.state }}"
    entity_id: switch.monitor
