---

- alias: Plug - Monitor - Turn on when home office mode
  trigger:
    platform: state
    entity_id: input_boolean.home_office_mode
    to: 'on'
  action:
    - service: switch.turn_on
      entity_id: switch.plug_study_monitor

- alias: Plug - Monitor - Turn off when home office mode off
  trigger:
    platform: state
    entity_id: input_boolean.home_office_mode
    to: 'off'
    for:
      minutes: 30
  action:
    - service: switch.turn_off
      entity_id: switch.plug_study_monitor
