---

- alias: Remote - Turn on Chromecast when Home Group is playing
  trigger:
    platform: state
    entity_id: media_player.home_group
    to: playing
  condition:
    condition: state
    entity_id: remote.living_room
    state: 'off'
  action:
    service: switch.turn_on
    entity_id: switch.living_room_chromecast

- alias: Remote - Amplifier - Turn off if still running
  trigger:
    platform: state
    entity_id: remote.living_room
    to: 'off'
    for:
      seconds: 10
  condition:
    condition: numeric_state
    entity_id: sensor.plug_living_room_amplifier
    above: 10
  mode: queued
  action:
    repeat:
      sequence:
        # Run command that for some reason doesn't always work
        - service: remote.send_command
          entity_id: remote.living_room
          data:
            device: Pioneer-AV-Receiver
            command: PowerOff
        # Give plug time to update the sensor
        - delay:
            seconds: 5
      until:
        condition: numeric_state
        entity_id: sensor.plug_living_room_amplifier
        below: 10

- alias: Remote - Amplifier - Turn on if not running
  trigger:
    platform: state
    entity_id: remote.living_room
    to: 'on'
    for:
      seconds: 10
  condition:
    condition: numeric_state
    entity_id: sensor.plug_living_room_amplifier
    below: 10
  mode: queued
  action:
    repeat:
      sequence:
        # Retry turning on amplifier
        - service: remote.send_command
          entity_id: remote.living_room
          data:
            device: Pioneer-AV-Receiver
            command: PowerOn
        # Give amplifier time to start and get ready
        - delay:
            seconds: 10
        # Set correct input source
        - service: remote.send_command
          entity_id: remote.living_room
          data:
            device: Pioneer-AV-Receiver
            command: "{{ state_attr('remote.living_room', 'current_activity') == 'Chromecast' | iif('InputHdmi1', 'InputTv') }}"
      until:
        condition: numeric_state
        entity_id: sensor.plug_living_room_amplifier
        above: 10

- alias: Remote - TV - Turn Amplifier on when TV running
  trigger:
    platform: state
    entity_id: media_player.lg_webos_smart_tv
    to: 'on'
  action:
    service: switch.turn_on
    entity_id: switch.living_room_tv

- alias: Remote - TV - Turn Amplifier off when TV off
  trigger:
    platform: state
    entity_id: media_player.lg_webos_smart_tv
    to: 'off'
  action:
    service: remote.turn_off
    entity_id: remote.living_room

- alias: Remote - TV - Switch to Chromecast when HDMI2 selected
  trigger:
    platform: state
    entity_id: media_player.lg_webos_smart_tv
    attribute: source
    to: Pioneer
  action:
    service: switch.turn_on
    entity_id: switch.living_room_chromecast

- alias: Remote - TV - Switch back to TV when HDMI2 not selected
  trigger:
    platform: state
    entity_id: media_player.lg_webos_smart_tv
    attribute: source
    from: Pioneer
  condition:
    condition: not
    conditions:
      condition: state
      entity_id: media_player.lg_webos_smart_tv
      state: 'off'
  action:
    service: switch.turn_on
    entity_id: switch.living_room_tv

- alias: Remote - TV - Increase Amplifier Volume when TV running
  trigger:
    platform: state
    entity_id: remote.living_room
    attribute: current_activity
    to: 'TV'
  action:
    service: remote.send_command
    entity_id: remote.living_room
    data:
      device: Pioneer-AV-Receiver
      command: VolumeUp
      num_repeats: 45

- alias: Remote - Turn off remote when Home Group stopped/paused casting for 30 seconds
  trigger:
    - platform: state
      entity_id: media_player.home_group
      to: 'off'
      for:
        seconds: 30
    - platform: state
      entity_id: media_player.home_group
      to: paused
      for:
        seconds: 30
    - platform: state
      entity_id: media_player.home_group
      to: unavailable
      for:
        seconds: 30
    - platform: state
      entity_id: media_player.home_group
      to: idle
      for:
        seconds: 30
  condition:
    - condition: state
      entity_id: switch.living_room_chromecast
      state: 'on'
    - condition: state
      entity_id: media_player.lg_webos_smart_tv
      state: 'off'
  action:
    service: remote.turn_off
    entity_id: remote.living_room
