---

- alias: Remote - Turn on Chromecast when All Speakers is playing
  trigger:
    platform: state
    entity_id: media_player.all_speakers
    to: playing
  condition:
    condition: state
    entity_id: remote.living_room
    state: 'off'
  action:
    service: switch.turn_on
    entity_id: switch.living_room_chromecast

- alias: Remote - Amplifier - Turn off if still running
  trigger:
    platform: state
    entity_id: remote.living_room
    to: 'off'
    for:
      seconds: 10
  condition:
    condition: numeric_state
    entity_id: sensor.amplifier_power
    above: 10
  mode: queued
  action:
    repeat:
      sequence:
        # Run command that for some reason doesn't always work
        - service: remote.send_command
          entity_id: remote.living_room
          data:
            device: Pioneer-AV-Receiver
            command: PowerOff
        # Give plug time to update the sensor
        - delay:
            seconds: 5
      until:
        condition: numeric_state
        entity_id: sensor.amplifier_power
        below: 10

- alias: Remote - Amplifier - Turn on if not running
  trigger:
    platform: state
    entity_id: remote.living_room
    to: 'on'
    for:
      seconds: 10
  condition:
    condition: numeric_state
    entity_id: sensor.amplifier_power
    below: 10
  mode: queued
  action:
    repeat:
      sequence:
        # Retry turning on amplifier
        - service: remote.send_command
          entity_id: remote.living_room
          data:
            device: Pioneer-AV-Receiver
            command: PowerOn
        # Give amplifier time to start and get ready
        - delay:
            seconds: 10
        # Set correct input source
        - service: remote.send_command
          entity_id: remote.living_room
          data:
            device: Pioneer-AV-Receiver
            command: "{{ state_attr('remote.living_room', 'current_activity') == 'Chromecast' | iif('InputHdmi1', 'InputTv') }}"
      until:
        condition: numeric_state
        entity_id: sensor.amplifier_power
        above: 10

- alias: Remote - TV - Turn Amplifier on when TV running
  trigger:
    platform: state
    entity_id: media_player.lg_webos_smart_tv
    to: 'on'
  action:
    service: switch.turn_on
    entity_id: switch.living_room_tv

- alias: Remote - TV - Turn Amplifier off when TV off
  trigger:
    platform: state
    entity_id: media_player.lg_webos_smart_tv
    to: 'off'
  action:
    service: remote.turn_off
    entity_id: remote.living_room

- alias: Remote - TV - Switch to Chromecast when HDMI2 selected
  trigger:
    platform: state
    entity_id: media_player.lg_webos_smart_tv
    attribute: source
    to: HDMI 2
  action:
    service: switch.turn_on
    entity_id: switch.living_room_chromecast

- alias: Remote - TV - Switch back to TV when HDMI2 not selected
  trigger:
    platform: state
    entity_id: media_player.lg_webos_smart_tv
    attribute: source
    from: HDMI 2
  condition:
    condition: not
    conditions:
      condition: state
      entity_id: media_player.lg_webos_smart_tv
      state: 'off'
  action:
    service: switch.turn_on
    entity_id: switch.living_room_tv

- alias: Remote - Turn off remote when All Speakers stopped/paused casting for 30 seconds
  trigger:
    - platform: state
      entity_id: media_player.all_speakers
      to: 'off'
      for:
        seconds: 30
    - platform: state
      entity_id: media_player.all_speakers
      to: unavailable
      for:
        seconds: 30
    - platform: state
      entity_id: media_player.all_speakers
      to: idle
      for:
        seconds: 30
    - platform: state
      entity_id: media_player.all_speakers
      to: buffering
      for:
        minutes: 5
    - platform: state
      entity_id: media_player.all_speakers
      to: paused
      for:
        minutes: 5
  condition:
    - condition: state
      entity_id: switch.living_room_chromecast
      state: 'on'
    - condition: state
      entity_id: media_player.lg_webos_smart_tv
      state: 'off'
  action:
    service: remote.turn_off
    entity_id: remote.living_room
