---

- alias: Tab - Display - Sync with corridor motion
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_corridor_occupancy
      to: 'on'
    - platform: state
      entity_id: binary_sensor.motion_corridor_occupancy
      to: 'off'
      for:
        minutes: 2
  action:
    service: switch.turn_{{ trigger.to_state.state }}
    entity_id: switch.display_tab_corridor
