---

- alias: Tab - Display - Turn on when motion
  trigger:
    platform: state
    entity_id: binary_sensor.motion_corridor_tab
    to: 'on'
  condition:
    condition: state
    entity_id: binary_sensor.dock_corridor_tab
    state: 'on'
  action:
    service: switch.turn_on
    entity_id: switch.display_tab_corridor

- alias: Tab - Display - Turn off when no motion for 3 mins
  trigger:
    platform: state
    entity_id: binary_sensor.motion_corridor_tab
    to: 'off'
    for:
      minutes: 3
  condition:
    condition: state
    entity_id: binary_sensor.dock_corridor_tab
    state: 'on'
  action:
    service: switch.turn_off
    entity_id: switch.display_tab_corridor
