---

# Bedroom
- alias: Thermostat Bedroom - Window opened
  trigger:
    platform: state
    entity_id: group.window_bedroom
    from: 'off'
    to: 'on'
    for:
      seconds: 5
  condition:
    condition: state
    entity_id: binary_sensor.thermostat_bedroom
    state: 'on'
  action:
    - service: input_text.set_value
      entity_id: input_text.thermostat_old_hvac_bedroom
      data:
        value: "{{ states('climate.bedroom') }}"
    - service: climate.set_hvac_mode
      entity_id: climate.bedroom
      data:
        hvac_mode: 'off'

- alias: Thermostat Bedroom - Window closed
  trigger:
    platform: state
    entity_id: group.window_bedroom
    from: 'on'
    to: 'off'
    for:
      seconds: 5
  condition:
    - condition: template
      value_template: "{{ not is_state('input_text.thermostat_old_hvac_bedroom', 'unknown') }}"
  action:
    - service: climate.set_hvac_mode
      entity_id: climate.bedroom
      data:
        hvac_mode: "{{ states('input_text.thermostat_old_hvac_bedroom') }}"
    - service: input_text.set_value
      entity_id: input_text.thermostat_old_hvac_bedroom
      data:
        value: unknown

# Study
- alias: Thermostat Study - Window openend
  trigger:
    platform: state
    entity_id: group.window_study
    from: 'off'
    to: 'on'
    for:
      seconds: 5
  condition:
    condition: state
    entity_id: binary_sensor.thermostat_study
    state: 'on'
  action:
    - service: input_text.set_value
      entity_id: input_text.thermostat_old_hvac_study
      data:
        value: "{{ states('climate.study') }}"
    - service: climate.set_hvac_mode
      entity_id: climate.study
      data:
        hvac_mode: 'off'

- alias: Thermostat Study - Window closed
  trigger:
    platform: state
    entity_id: group.window_study
    from: 'on'
    to: 'off'
    for:
      seconds: 5
  condition:
    condition: template
    value_template: "{{ not is_state('input_text.thermostat_old_hvac_study', 'unknown') }}"
  action:
    - service: climate.set_hvac_mode
      entity_id: climate.study
      data:
        hvac_mode: "{{ states('input_text.thermostat_old_hvac_study') }}"
    - service: input_text.set_value
      entity_id: input_text.thermostat_old_hvac_study
      data:
        value: unknown

# Bathroom
- alias: Thermostat Bathroom - Window openend
  trigger:
    platform: state
    entity_id: group.window_bathroom
    from: 'off'
    to: 'on'
    for:
      seconds: 5
  condition:
    condition: state
    entity_id: binary_sensor.thermostat_bathroom
    state: 'on'
  action:
    - service: input_text.set_value
      entity_id: input_text.thermostat_old_hvac_bathroom
      data:
        value: "{{ states('climate.bathroom') }}"
    - service: climate.set_hvac_mode
      entity_id: climate.bathroom
      data:
        hvac_mode: 'off'

- alias: Thermostat Bathroom - Window closed
  trigger:
    platform: state
    entity_id: group.window_bathroom
    from: 'on'
    to: 'off'
    for:
      seconds: 5
  condition:
    condition: template
    value_template: "{{ not is_state('input_text.thermostat_old_hvac_bathroom', 'unknown') }}"
  action:
    - service: climate.set_hvac_mode
      entity_id: climate.bathroom
      data:
        hvac_mode: "{{ states('input_text.thermostat_old_hvac_bathroom') }}"
    - service: input_text.set_value
      entity_id: input_text.thermostat_old_hvac_bathroom
      data:
        value: unknown

# Living Room
- alias: Thermostat Living Room - Window openend
  trigger:
    platform: state
    entity_id: group.window_living_room_and_kitchen
    from: 'off'
    to: 'on'
    for:
      seconds: 5
  condition:
    condition: state
    entity_id: binary_sensor.thermostat_living_room
    state: 'on'
  action:
    - service: input_text.set_value
      entity_id: input_text.thermostat_old_hvac_living_room
      data:
        value: "{{ states('climate.living_room') }}"
    - service: climate.set_hvac_mode
      entity_id: climate.living_room
      data:
        hvac_mode: 'off'

- alias: Thermostat Living Room - Window closed
  trigger:
    platform: state
    entity_id: group.window_living_room_and_kitchen
    from: 'on'
    to: 'off'
    for:
      seconds: 5
  condition:
    condition: template
    value_template: "{{ not is_state('input_text.thermostat_old_hvac_living_room', 'unknown') }}"
  action:
    - service: climate.set_hvac_mode
      entity_id: climate.living_room
      data:
        hvac_mode: "{{ states('input_text.thermostat_old_hvac_living_room') }}"
    - service: input_text.set_value
      entity_id: input_text.thermostat_old_hvac_living_room
      data:
        value: unknown

# Kitchen
- alias: Thermostat Kitchen - Window openend
  trigger:
    platform: state
    entity_id: group.window_living_room_and_kitchen
    from: 'off'
    to: 'on'
    for:
      seconds: 5
  condition:
    condition: state
    entity_id: binary_sensor.thermostat_kitchen
    state: 'on'
  action:
    - service: input_text.set_value
      entity_id: input_text.thermostat_old_hvac_kitchen
      data:
        value: "{{ states('climate.kitchen') }}"
    - service: climate.set_hvac_mode
      entity_id: climate.kitchen
      data:
        hvac_mode: 'off'

- alias: Thermostat Kitchen - Window closed
  trigger:
    platform: state
    entity_id: group.window_living_room_and_kitchen
    from: 'on'
    to: 'off'
    for:
      seconds: 5
  condition:
    condition: template
    value_template: "{{ not is_state('input_text.thermostat_old_hvac_kitchen', 'unknown') }}"
  action:
    - service: climate.set_hvac_mode
      entity_id: climate.kitchen
      data:
        hvac_mode: "{{ states('input_text.thermostat_old_hvac_kitchen') }}"
    - service: input_text.set_value
      entity_id: input_text.thermostat_old_hvac_kitchen
      data:
        value: unknown

# Toilet
- alias: Thermostat Toilet - Window openend
  trigger:
    platform: state
    entity_id: group.window_toilet
    from: 'off'
    to: 'on'
    for:
      seconds: 5
  condition:
    condition: state
    entity_id: binary_sensor.thermostat_toilet
    state: 'on'
  action:
    - service: input_text.set_value
      entity_id: input_text.thermostat_old_hvac_toilet
      data:
        value: "{{ states('climate.toilet') }}"
    - service: climate.set_hvac_mode
      entity_id: climate.toilet
      data:
        hvac_mode: 'off'

- alias: Thermostat Toilet - Window closed
  trigger:
    platform: state
    entity_id: group.window_toilet
    from: 'on'
    to: 'off'
    for:
      seconds: 5
  condition:
    condition: template
    value_template: "{{ not is_state('input_text.thermostat_old_hvac_toilet', 'unknown') }}"
  action:
    - service: climate.set_hvac_mode
      entity_id: climate.toilet
      data:
        hvac_mode: "{{ states('input_text.thermostat_old_hvac_toilet') }}"
    - service: input_text.set_value
      entity_id: input_text.thermostat_old_hvac_toilet
      data:
        value: unknown

- alias: Thermostat Kitchen - Summer Mode - Heating off after 4 hours
  trigger:
    platform: state
    entity_id: binary_sensor.thermostat_kitchen
    from: 'off'
    to: 'on'
    for:
      hours: 4
  condition:
    condition: state
    entity_id: input_boolean.summer_mode
    state: 'on'
  action:
    - service: notify.patrick
      data:
        title: Thermostat
        message: Thermostat in Kitchen turned off after 4 hours.
    - service: switch.turn_off
      entity_id: switch.climate_kitchen

- alias: Thermostat Living Room - Summer Mode - Heating off after 4 hours
  trigger:
    platform: state
    entity_id: binary_sensor.thermostat_living_room
    from: 'off'
    to: 'on'
    for:
      hours: 4
  condition:
    condition: state
    entity_id: input_boolean.summer_mode
    state: 'on'
  action:
    - service: notify.patrick
      data:
        title: Thermostat
        message: Thermostat in Living Room turned off after 4 hours.
    - service: switch.turn_off
      entity_id: switch.climate_living_room

- alias: Thermostat Study - Summer Mode - Heating off after 4 hours
  trigger:
    platform: state
    entity_id: binary_sensor.thermostat_study
    from: 'off'
    to: 'on'
    for:
      hours: 4
  condition:
    condition: state
    entity_id: input_boolean.summer_mode
    state: 'on'
  action:
    - service: notify.patrick
      data:
        title: Thermostat
        message: Thermostat in Study turned off after 4 hours.
    - service: switch.turn_off
      entity_id: switch.climate_study

- alias: Thermostat Bathroom - Summer Mode - Heating off after 4 hours
  trigger:
    platform: state
    entity_id: binary_sensor.thermostat_bathroom
    from: 'off'
    to: 'on'
    for:
      hours: 4
  condition:
    condition: state
    entity_id: input_boolean.summer_mode
    state: 'on'
  action:
    - service: notify.patrick
      data:
        title: Thermostat
        message: Thermostat in Bathroom turned off after 4 hours.
    - service: switch.turn_off
      entity_id: switch.climate_bathroom

- alias: Thermostat Bedroom - Summer Mode - Heating off after 4 hours
  trigger:
    platform: state
    entity_id: binary_sensor.thermostat_bedroom
    from: 'off'
    to: 'on'
    for:
      hours: 4
  condition:
    condition: state
    entity_id: input_boolean.summer_mode
    state: 'on'
  action:
    - service: notify.patrick
      data:
        title: Thermostat
        message: Thermostat in Bedroom turned off after 4 hours.
    - service: switch.turn_off
      entity_id: switch.climate_bedroom

- alias: Thermostat Toilet - Summer Mode - Heating off after 4 hours
  trigger:
    platform: state
    entity_id: binary_sensor.thermostat_toilet
    from: 'off'
    to: 'on'
    for:
      hours: 4
  condition:
    condition: state
    entity_id: input_boolean.summer_mode
    state: 'on'
  action:
    - service: notify.patrick
      data:
        title: Thermostat
        message: Thermostat in Toilet turned off after 4 hours.
    - service: switch.turn_off
      entity_id: switch.climate_toilet

- alias: Thermostat Kitchen - Manual heating off after 4 hours
  trigger:
    platform: template
    value_template: "{{ is_state('climate.kitchen', 'heat') }}"
    for:
      hours: 4
  condition:
    condition: state
    entity_id: input_boolean.summer_mode
    state: 'off'
  action:
    - service: notify.patrick
      data:
        title: Thermostat
        message: Manual heating in Kitchen turned off after 4 hours.
    - service: switch.turn_on
      entity_id: switch.climate_kitchen

- alias: Thermostat Living Room - Manual heating off after 4 hours
  trigger:
    platform: template
    value_template: "{{ is_state('climate.living_room', 'heat') }}"
    for:
      hours: 4
  condition:
    condition: state
    entity_id: input_boolean.summer_mode
    state: 'off'
  action:
    - service: notify.patrick
      data:
        title: Thermostat
        message: Manual heating in Living Room turned off after 4 hours.
    - service: switch.turn_on
      entity_id: switch.climate_living_room

- alias: Thermostat Study - Manual heating off after 4 hours
  trigger:
    platform: template
    value_template: "{{ is_state('climate.study', 'heat') }}"
    for:
      hours: 4
  condition:
    condition: state
    entity_id: input_boolean.summer_mode
    state: 'off'
  action:
    - service: notify.patrick
      data:
        title: Thermostat
        message: Manual heating in Study turned off after 4 hours.
    - service: switch.turn_on
      entity_id: switch.climate_study

- alias: Thermostat Bathroom - Manual heating off after 4 hours
  trigger:
    platform: template
    value_template: "{{ is_state('climate.bathroom', 'heat') }}"
    for:
      hours: 4
  condition:
    condition: state
    entity_id: input_boolean.summer_mode
    state: 'off'
  action:
    - service: notify.patrick
      data:
        title: Thermostat
        message: Manual heating in Bathroom turned off after 4 hours.
    - service: switch.turn_on
      entity_id: switch.climate_bathroom

- alias: Thermostat Bedroom - Manual heating off after 4 hours
  trigger:
    platform: template
    value_template: "{{ is_state('climate.bedroom', 'heat') }}"
    for:
      hours: 4
  condition:
    condition: state
    entity_id: input_boolean.summer_mode
    state: 'off'
  action:
    - service: notify.patrick
      data:
        title: Thermostat
        message: Manual heating in Bedroom turned off after 4 hours.
    - service: switch.turn_on
      entity_id: switch.climate_bedroom

- alias: Thermostat Toilet - Manual heating off after 4 hours
  trigger:
    platform: template
    value_template: "{{ is_state('climate.toilet', 'heat') }}"
    for:
      hours: 4
  condition:
    condition: state
    entity_id: input_boolean.summer_mode
    state: 'off'
  action:
    - service: notify.patrick
      data:
        title: Thermostat
        message: Manual heating in Toilet turned off after 4 hours.
    - service: switch.turn_on
      entity_id: switch.climate_toilet

- alias: Thermostat Living Room - Force off and notify
  trigger:
    platform: template
    value_template: >
      {{
        is_state('binary_sensor.thermostat_living_room', 'on')
          and
        is_state('group.window_living_room', 'on')
      }}
    for:
      minutes: 1
  action:
    - service: notify.patrick
      data:
        title: Thermostat
        message: Thermostat in Living Room turned off because window is open.
    - service: input_text.set_value
      entity_id: input_text.thermostat_old_hvac_living_room
      data:
        value: "{{ states('climate.living_room') }}"
    - service: climate.set_hvac_mode
      entity_id: climate.living_room
      data:
        hvac_mode: 'off'

- alias: Thermostat Bedroom - Force off and notify
  trigger:
    platform: template
    value_template: >
      {{
        is_state('binary_sensor.thermostat_bedroom', 'on')
          and
        is_state('group.window_bedroom', 'on')
      }}
    for:
      minutes: 1
  action:
    - service: notify.patrick
      data:
        title: Thermostat
        message: Thermostat in Bedroom turned off because window is open.
    - service: input_text.set_value
      entity_id: input_text.thermostat_old_hvac_bedroom
      data:
        value: "{{ states('climate.bedroom') }}"
    - service: climate.set_hvac_mode
      entity_id: climate.bedroom
      data:
        hvac_mode: 'off'


- alias: Thermostat Bathroom - Force off and notify
  trigger:
    platform: template
    value_template: >
      {{
        is_state('binary_sensor.thermostat_bathroom', 'on')
          and
        is_state('group.window_bathroom', 'on')
      }}

    for:
      minutes: 1
  action:
    - service: notify.patrick
      data:
        title: Thermostat
        message: Thermostat in Bathroom turned off because window is open.
    - service: input_text.set_value
      entity_id: input_text.thermostat_old_hvac_bathroom
      data:
        value: "{{ states('climate.bathroom') }}"
    - service: climate.set_hvac_mode
      entity_id: climate.bathroom
      data:
        hvac_mode: 'off'


- alias: Thermostat Study - Force off and notify
  trigger:
    platform: template
    value_template: >
      {{
        is_state('binary_sensor.thermostat_study', 'on')
          and
        is_state('group.window_study', 'on')
      }}
    for:
      minutes: 1
  action:
    - service: notify.patrick
      data:
        title: Thermostat
        message: Thermostat in Study turned off because window is open.
    - service: input_text.set_value
      entity_id: input_text.thermostat_old_hvac_study
      data:
        value: "{{ states('climate.study') }}"
    - service: climate.set_hvac_mode
      entity_id: climate.study
      data:
        hvac_mode: 'off'


- alias: Thermostat Kitchen - Force off and notify
  trigger:
    platform: template
    value_template: >
      {{
        is_state('binary_sensor.thermostat_kitchen', 'on')
          and
        is_state('group.window_kitchen', 'on')
      }}
    for:
      minutes: 1
  action:
    - service: notify.patrick
      data:
        title: Thermostat
        message: Thermostat in Kitchen turned off because window is open.
    - service: input_text.set_value
      entity_id: input_text.thermostat_old_hvac_kitchen
      data:
        value: "{{ states('climate.kitchen') }}"
    - service: climate.set_hvac_mode
      entity_id: climate.kitchen
      data:
        hvac_mode: 'off'

- alias: Thermostat Toilet - Force off and notify
  trigger:
    platform: template
    value_template: >
      {{
        is_state('binary_sensor.thermostat_toilet', 'on')
          and
        is_state('group.window_toilet', 'on')
      }}
    for:
      minutes: 1
  action:
    - service: notify.patrick
      data:
        title: Thermostat
        message: Thermostat in Toilet turned off because window is open.
    - service: input_text.set_value
      entity_id: input_text.thermostat_old_hvac_toilet
      data:
        value: "{{ states('climate.toilet') }}"
    - service: climate.set_hvac_mode
      entity_id: climate.toilet
      data:
        hvac_mode: 'off'

- alias: Thermostat Study - Turn on when motion
  trigger:
    platform: state
    entity_id: binary_sensor.motion_study
    to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.summer_mode
      state: 'off'
    - condition: state
      entity_id: group.residents
      state: 'home'
    - condition: template
      value_template: "{{ not is_state('vacuum.xiaomi_vacuum_cleaner', 'cleaning') }}"
    - condition: time
      after: '08:00'
    - condition: time
      before: '22:00'
    - condition: state
      entity_id: input_boolean.guest_mode
      state: 'off'
  action:
    service: climate.set_temperature
    entity_id: climate.study
    data:
      temperature: 22

- alias: Thermostat Study - Turn off when no motion for 30 mins
  trigger:
    platform: state
    entity_id: binary_sensor.motion_study
    to: 'off'
    for:
      minutes: 30
  condition:
    - condition: state
      entity_id: input_boolean.summer_mode
      state: 'off'
    - condition: state
      entity_id: climate.study
      state: heat
    - condition: state
      entity_id: input_boolean.guest_mode
      state: 'off'
  action:
    service: climate.set_hvac_mode
    entity_id: climate.study
    data:
      hvac_mode: auto
