---

# Bedroom
- alias: Thermostat - Bedroom - Window opened
  trigger:
    platform: state
    entity_id: binary_sensor.window_bedroom
    from: 'off'
    to: 'on'
    for:
      minutes: 1
  condition:
    condition: state
    entity_id: binary_sensor.thermostat_bedroom
    state: 'on'
  action:
    - service: input_text.set_value
      entity_id: input_text.thermostat_old_hvac_bedroom
      data:
        value: "{{ states('climate.bedroom') }}"
    - service: climate.set_hvac_mode
      entity_id: climate.bedroom
      data:
        hvac_mode: 'off'

- alias: Thermostat - Bedroom - Window closed
  trigger:
    platform: state
    entity_id: binary_sensor.window_bedroom
    from: 'on'
    to: 'off'
    for:
      minutes: 5
  condition:
    - condition: template
      value_template: "{{ not is_state('input_text.thermostat_old_hvac_bedroom', 'unknown') }}"
  action:
    - service: climate.set_hvac_mode
      entity_id: climate.bedroom
      data:
        hvac_mode: "{{ states('input_text.thermostat_old_hvac_bedroom') }}"
    - service: input_text.set_value
      entity_id: input_text.thermostat_old_hvac_bedroom
      data:
        value: unknown

# Study
- alias: Thermostat - Study - Window openend
  trigger:
    platform: state
    entity_id: binary_sensor.window_study
    from: 'off'
    to: 'on'
    for:
      minutes: 1
  condition:
    condition: state
    entity_id: binary_sensor.thermostat_study
    state: 'on'
  action:
    - service: input_text.set_value
      entity_id: input_text.thermostat_old_hvac_study
      data:
        value: "{{ states('climate.study') }}"
    - service: climate.set_hvac_mode
      entity_id: climate.study
      data:
        hvac_mode: 'off'

- alias: Thermostat - Study - Window closed
  trigger:
    platform: state
    entity_id: binary_sensor.window_study
    from: 'on'
    to: 'off'
    for:
      minutes: 5
  condition:
    condition: template
    value_template: "{{ not is_state('input_text.thermostat_old_hvac_study', 'unknown') }}"
  action:
    - service: climate.set_hvac_mode
      entity_id: climate.study
      data:
        hvac_mode: "{{ states('input_text.thermostat_old_hvac_study') }}"
    - service: input_text.set_value
      entity_id: input_text.thermostat_old_hvac_study
      data:
        value: unknown

# Bathroom
- alias: Thermostat - Bathroom - Window openend
  trigger:
    platform: state
    entity_id: binary_sensor.window_bathroom
    from: 'off'
    to: 'on'
    for:
      minutes: 1
  condition:
    condition: state
    entity_id: binary_sensor.thermostat_bathroom
    state: 'on'
  action:
    - service: input_text.set_value
      entity_id: input_text.thermostat_old_hvac_bathroom
      data:
        value: "{{ states('climate.bathroom') }}"
    - service: climate.set_hvac_mode
      entity_id: climate.bathroom
      data:
        hvac_mode: 'off'

- alias: Thermostat - Bathroom - Window closed
  trigger:
    platform: state
    entity_id: binary_sensor.window_bathroom
    from: 'on'
    to: 'off'
    for:
      minutes: 5
  condition:
    condition: template
    value_template: "{{ not is_state('input_text.thermostat_old_hvac_bathroom', 'unknown') }}"
  action:
    - service: climate.set_hvac_mode
      entity_id: climate.bathroom
      data:
        hvac_mode: "{{ states('input_text.thermostat_old_hvac_bathroom') }}"
    - service: input_text.set_value
      entity_id: input_text.thermostat_old_hvac_bathroom
      data:
        value: unknown

# Living Room
- alias: Thermostat - Living Room - Window openend
  trigger:
    - platform: state
      entity_id: binary_sensor.window_kitchen
      from: 'off'
      to: 'on'
      for:
        minutes: 1
    - platform: state
      entity_id: binary_sensor.window_living_room
      from: 'off'
      to: 'on'
      for:
        minutes: 1
  condition:
    condition: state
    entity_id: binary_sensor.thermostat_living_room
    state: 'on'
  action:
    - service: input_text.set_value
      entity_id: input_text.thermostat_old_hvac_living_room
      data:
        value: "{{ states('climate.living_room') }}"
    - service: climate.set_hvac_mode
      entity_id: climate.living_room
      data:
        hvac_mode: 'off'

- alias: Thermostat - Living Room - Window closed
  trigger:
    - platform: state
      entity_id: binary_sensor.window_kitchen
      from: 'on'
      to: 'off'
      for:
        minutes: 5
    - platform: state
      entity_id: binary_sensor.window_living_room
      from: 'on'
      to: 'off'
      for:
        minutes: 5
  condition:
    condition: template
    value_template: "{{ not is_state('input_text.thermostat_old_hvac_living_room', 'unknown') }}"
  action:
    - service: climate.set_hvac_mode
      entity_id: climate.living_room
      data:
        hvac_mode: "{{ states('input_text.thermostat_old_hvac_living_room') }}"
    - service: input_text.set_value
      entity_id: input_text.thermostat_old_hvac_living_room
      data:
        value: unknown

# Kitchen
- alias: Thermostat - Kitchen - Window openend
  trigger:
    - platform: state
      entity_id: binary_sensor.window_kitchen
      from: 'off'
      to: 'on'
      for:
        minutes: 1
    - platform: state
      entity_id: binary_sensor.window_living_room
      from: 'off'
      to: 'on'
      for:
        minutes: 5
  condition:
    condition: state
    entity_id: binary_sensor.thermostat_kitchen
    state: 'on'
  action:
    - service: input_text.set_value
      entity_id: input_text.thermostat_old_hvac_kitchen
      data:
        value: "{{ states('climate.kitchen') }}"
    - service: climate.set_hvac_mode
      entity_id: climate.kitchen
      data:
        hvac_mode: 'off'

- alias: Thermostat - Kitchen - Window closed
  trigger:
    - platform: state
      entity_id: binary_sensor.window_kitchen
      from: 'on'
      to: 'off'
      for:
        minutes: 5
    - platform: state
      entity_id: binary_sensor.window_living_room
      from: 'on'
      to: 'off'
      for:
        minutes: 5
  condition:
    condition: template
    value_template: "{{ not is_state('input_text.thermostat_old_hvac_kitchen', 'unknown') }}"
  action:
    - service: climate.set_hvac_mode
      entity_id: climate.kitchen
      data:
        hvac_mode: "{{ states('input_text.thermostat_old_hvac_kitchen') }}"
    - service: input_text.set_value
      entity_id: input_text.thermostat_old_hvac_kitchen
      data:
        value: unknown

# Toilet
- alias: Thermostat - Toilet - Window openend
  trigger:
    platform: state
    entity_id: binary_sensor.window_toilet
    from: 'off'
    to: 'on'
  condition:
    condition: state
    entity_id: binary_sensor.thermostat_toilet
    state: 'on'
  action:
    - service: input_text.set_value
      entity_id: input_text.thermostat_old_hvac_toilet
      data:
        value: "{{ states('climate.toilet') }}"
    - service: climate.set_hvac_mode
      entity_id: climate.toilet
      data:
        hvac_mode: 'off'

- alias: Thermostat - Toilet - Window closed
  trigger:
    platform: state
    entity_id: binary_sensor.window_toilet
    from: 'on'
    to: 'off'
    for:
      minutes: 5
  condition:
    condition: template
    value_template: "{{ not is_state('input_text.thermostat_old_hvac_toilet', 'unknown') }}"
  action:
    - service: climate.set_hvac_mode
      entity_id: climate.toilet
      data:
        hvac_mode: "{{ states('input_text.thermostat_old_hvac_toilet') }}"
    - service: input_text.set_value
      entity_id: input_text.thermostat_old_hvac_toilet
      data:
        value: unknown

- alias: Thermostat - All - Summer Mode - Heating off after 4 hours
  trigger:
    - platform: state
      entity_id: climate.kitchen
      to: 'on'
      for:
        hours: 4
    - platform: state
      entity_id: climate.living_room
      to: 'on'
      for:
        hours: 4
    - platform: state
      entity_id: climate.bedroom
      to: 'on'
      for:
        hours: 4
    - platform: state
      entity_id: climate.study
      to: 'on'
      for:
        hours: 4
    - platform: state
      entity_id: climate.bathroom
      to: 'on'
      for:
        hours: 4
    - platform: state
      entity_id: climate.toilet
      to: 'on'
      for:
        hours: 4
  condition:
    condition: state
    entity_id: input_boolean.summer_mode
    state: 'on'
  action:
    - service: notify.patrick
      data:
        title: Thermostat
        message: Thermostat in {{ trigger.to_state.name }} turned off after 4 hours.
    - service: climate.set_hvac_mode
      data:
        entity_id: "{{ trigger.entity_id }}"
        hvac_mode: auto

- alias: Thermostat - All - Manual heating off after 4 hours
  trigger:
    - platform: state
      entity_id: climate.kitchen
      to: heat
      for:
        hours: 4
    - platform: state
      entity_id: climate.living_room
      to: heat
      for:
        hours: 4
    - platform: state
      entity_id: climate.bedroom
      to: heat
      for:
        hours: 4
    - platform: state
      entity_id: climate.study
      to: heat
      for:
        hours: 4
    - platform: state
      entity_id: climate.bathroom
      to: heat
      for:
        hours: 4
    - platform: state
      entity_id: climate.toilet
      to: heat
      for:
        hours: 4
  condition:
    condition: state
    entity_id: input_boolean.summer_mode
    state: 'off'
  action:
    - service: notify.patrick
      data:
        title: Thermostat
        message: Manual heating in {{ trigger.to_state.name }} turned off after 4 hours.
    - service: climate.set_hvac_mode
      data:
        entity_id: "{{ trigger.entity_id}}"
        hvac_mode: auto

- alias: Thermostat - Living Room - Force off when window open
  trigger:
    platform: time_pattern
    minutes: /5
  condition:
    - condition: state
      entity_id: binary_sensor.thermostat_living_room
      state: 'on'
    - condition: state
      entity_id: binary_sensor.window_living_room
      state: 'on'
  action:
    - service: input_text.set_value
      entity_id: input_text.thermostat_old_hvac_living_room
      data:
        value: "{{ states('climate.living_room') }}"
    - service: climate.set_hvac_mode
      entity_id: climate.living_room
      data:
        hvac_mode: 'off'

- alias: Thermostat - Bedroom - Force off when window open
  trigger:
    platform: time_pattern
    minutes: /5
  condition:
    - condition: state
      entity_id: binary_sensor.thermostat_bedroom
      state: 'on'
    - condition: state
      entity_id: binary_sensor.window_bedroom
      state: 'on'
  action:
    - service: input_text.set_value
      entity_id: input_text.thermostat_old_hvac_bedroom
      data:
        value: "{{ states('climate.bedroom') }}"
    - service: climate.set_hvac_mode
      entity_id: climate.bedroom
      data:
        hvac_mode: 'off'


- alias: Thermostat - Bathroom - Force off when window open
  trigger:
    platform: time_pattern
    minutes: /5
  condition:
    - condition: state
      entity_id: binary_sensor.thermostat_bathroom
      state: 'on'
    - condition: state
      entity_id: binary_sensor.window_bathroom
      state: 'on'
  action:
    - service: input_text.set_value
      entity_id: input_text.thermostat_old_hvac_bathroom
      data:
        value: "{{ states('climate.bathroom') }}"
    - service: climate.set_hvac_mode
      entity_id: climate.bathroom
      data:
        hvac_mode: 'off'


- alias: Thermostat - Study - Force off when window open
  trigger:
    platform: time_pattern
    minutes: /5
  condition:
    - condition: state
      entity_id: binary_sensor.thermostat_study
      state: 'on'
    - condition: state
      entity_id: binary_sensor.window_study
      state: 'on'
  action:
    - service: input_text.set_value
      entity_id: input_text.thermostat_old_hvac_study
      data:
        value: "{{ states('climate.study') }}"
    - service: climate.set_hvac_mode
      entity_id: climate.study
      data:
        hvac_mode: 'off'


- alias: Thermostat - Kitchen - Force off when window open
  trigger:
    platform: time_pattern
    minutes: /5
  condition:
    - condition: state
      entity_id: binary_sensor.thermostat_kitchen
      state: 'on'
    - condition: state
      entity_id: binary_sensor.window_kitchen
      state: 'on'
  action:
    - service: input_text.set_value
      entity_id: input_text.thermostat_old_hvac_kitchen
      data:
        value: "{{ states('climate.kitchen') }}"
    - service: climate.set_hvac_mode
      entity_id: climate.kitchen
      data:
        hvac_mode: 'off'

- alias: Thermostat - Toilet - Force off when window open
  trigger:
    platform: time_pattern
    minutes: /5
  condition:
    - condition: state
      entity_id: binary_sensor.thermostat_toilet
      state: 'on'
    - condition: state
      entity_id: binary_sensor.window_toilet
      state: 'on'
  action:
    - service: input_text.set_value
      entity_id: input_text.thermostat_old_hvac_toilet
      data:
        value: "{{ states('climate.toilet') }}"
    - service: climate.set_hvac_mode
      entity_id: climate.toilet
      data:
        hvac_mode: 'off'

- alias: Thermostat - Study - Turn on when home office mode on
  trigger:
    platform: state
    entity_id: input_boolean.home_office_mode
    to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.summer_mode
      state: 'off'
    - condition: state
      entity_id: group.residents
      state: 'home'
    - condition: state
      entity_id: binary_sensor.window_study
      state: 'off'
    - "{{ not is_state('vacuum.xiaomi_vacuum_cleaner', 'cleaning') }}"
    - "{{ not is_state('climate.study', 'heat') }}"
  action:
    # input_boolean must be changed before actual temperature.
    # otherwise notification (from notification.yaml) will fire
    - service: input_boolean.turn_on
      entity_id: input_boolean.thermostat_study_triggered_by_motion
    - service: climate.set_temperature
      entity_id: climate.study
      data:
        temperature: 22

- alias: Thermostat - Study - Turn off when home office mode off
  trigger:
    platform: state
    entity_id: input_boolean.home_office_mode
    to: 'off'
  condition:
    - condition: state
      entity_id: input_boolean.summer_mode
      state: 'off'
    - condition: state
      entity_id: climate.study
      state: heat
  action:
    - service: climate.set_hvac_mode
      entity_id: climate.study
      data:
        hvac_mode: auto
    - service: input_boolean.turn_off
      entity_id: input_boolean.thermostat_study_triggered_by_motion

- alias: Thermostat - All - Reduce temperature if too high
  trigger:
    - platform: numeric_state
      entity_id: climate.kitchen
      attribute: temperature
      above: 23
      for:
        minutes: 3
    - platform: numeric_state
      entity_id: climate.living_room
      attribute: temperature
      above: 23
      for:
        minutes: 3
    - platform: numeric_state
      entity_id: climate.bedroom
      attribute: temperature
      above: 23
      for:
        minutes: 3
    - platform: numeric_state
      entity_id: climate.study
      attribute: temperature
      above: 23
      for:
        minutes: 3
    - platform: numeric_state
      entity_id: climate.bathroom
      attribute: temperature
      above: 23
      for:
        minutes: 3
    - platform: numeric_state
      entity_id: climate.toilet
      attribute: temperature
      above: 23
      for:
        minutes: 3
  action:
    - service: notify.patrick
      data:
        title: Thermostat
        # yamllint disable-line rule:line-length
        message: "Reducing temperature in {{ trigger.to_state.name }} from {{ state_attr(trigger.entity_id, 'temperature') }} to 23.0°C."
    - service: climate.set_temperature
      data:
        entity_id: "{{ trigger.entity_id }}"
        temperature: 23
