---

- alias: Updater - Notify Update available
  trigger:
    platform: state
    entity_id: binary_sensor.updater
    to: 'on'
  action:
    service: notify.patrick
    data:
      message: >
        Home Assistant update available from {{ states('sensor.current_version') }}
        to {{ state_attr('binary_sensor.updater', 'newest_version') }}.
      data:
        actions:
          - title: Update
            action: 'update_ha'


- alias: Updater - Perform update
  trigger:
    platform: event
    event_type: mobile_app_notification_action
    event_data:
      action: 'update_ha'
  action:
    service: switch.turn_on
    entity_id: switch.updater
