---

- alias: Vacuum - Daily cleanup when Residents not home
  trigger:
    - platform: time
      at: '10:00:00'
    - platform: state
      entity_id: group.residents
      from: home
      to: not_home
      for:
        hours: 1
  condition:
    - condition: time
      after: '07:00:00'
      before: '20:00:00'
    - condition: state
      entity_id: input_boolean.vacuum_ran_today
      state: 'off'
    - condition: state
      entity_id: input_boolean.vacuum_daily_cleanup
      state: 'on'
    - condition: state
      entity_id: group.residents
      state: not_home
  action:
    - service: vacuum.start
      entity_id: vacuum.xiaomi_vacuum_cleaner
    - service: vacuum.set_fan_speed
      data:
        entity_id: vacuum.xiaomi_vacuum_cleaner
        fan_speed: '103'  # medium

- alias: Vacuum - Notify on cleanup finished when not home
  trigger:
    platform: state
    entity_id: vacuum.xiaomi_vacuum_cleaner
    to: returning
  condition:
    condition: state
    entity_id: person.patrick
    state: not_home
  action:
    service: notify.patrick
    data:
      title: Roborock
      message: >
        Roborock finished Cleanup:
        {{ state_attr('vacuum.xiaomi_vacuum_cleaner', 'cleaned_area') }} m²,
        {{ state_attr('vacuum.xiaomi_vacuum_cleaner', 'cleaning_time') }} minutes,
        Battery {{ state_attr('vacuum.xiaomi_vacuum_cleaner', 'battery_level') }} %

- alias: Vacuum - Reset Daily Cleanup Boolean
  trigger:
    platform: time
    at: 00:00
  action:
    service: input_boolean.turn_off
    entity_id: input_boolean.vacuum_ran_today

- alias: Vacuum - Trigger set states on cleanup done
  trigger:
    platform: state
    entity_id: vacuum.xiaomi_vacuum_cleaner
    to: cleaning
    for:
      minutes: 20
  action:
    service: input_boolean.turn_on
    entity_id: input_boolean.vacuum_ran_today

- alias: Vacuum - Notify on error
  trigger:
    platform: state
    entity_id: vacuum.xiaomi_vacuum_cleaner
    to: error
  action:
    service: notify.patrick
    data:
      title: Roborock
      message: >
        Roborock Error: {{ states.vacuum.xiaomi_vacuum_cleaner.attributes.error }}

- alias: Vacuum - Start room cleaup on input select
  trigger:
    platform: state
    entity_id: input_select.vacuum_room_cleanup
  action:
    - service: xiaomi_miio.vacuum_clean_segment
      data:
        entity_id: vacuum.xiaomi_vacuum_cleaner
        segments: >
          {% if states('input_select.vacuum_room_cleanup') == 'Living Room' %}
            20
          {% elif states('input_select.vacuum_room_cleanup') == 'Kitchen' %}
            21
          {% elif states('input_select.vacuum_room_cleanup') == 'Toilet' %}
            17
          {% elif states('input_select.vacuum_room_cleanup') == 'Corridor' %}
            16
          {% elif states('input_select.vacuum_room_cleanup') == 'Bedroom' %}
            19
          {% elif states('input_select.vacuum_room_cleanup') == 'Study' %}
            18
          {% elif states('input_select.vacuum_room_cleanup') == 'Bathroom' %}
            1
          {% endif %}
    - wait_for_trigger:
        platform: state
        entity_id: vacuum.xiaomi_vacuum_cleaner
        from: cleaning
      continue_on_timeout: true
      timeout: '00:30:00'
    - service: input_select.select_option
      entity_id: input_select.vacuum_room_cleanup
      data:
        option: '-'
