---

- alias: Washing Machine - Notify when finished
  initial_state: true
  trigger:
    platform: state
    entity_id: binary_sensor.bathroom_washing_machine_running
    from: 'on'
    to: 'off'
  action:
    service: script.notify
    data:
      message: Washing machine finished
