---

- alias: Windows - Living Room - Notify window still open
  trigger:
    - platform: numeric_state
      entity_id: climate.living_room
      attribute: temperature
      below: 16
    - platform: state
      entity_id: binary_sensor.window_living_room
      to: 'on'
      for:
        minutes: 30
  condition:
    - condition: state
      entity_id: input_boolean.summer_mode
      state: 'off'
    - condition: state
      entity_id: binary_sensor.window_living_room
      state: 'on'
      for:
        minutes: 15
    - condition: numeric_state
      entity_id: climate.living_room
      attribute: temperature
      below: 16
  action:
    service: notify.patrick
    data:
      title: Living Room window open
      message: >
        Window in Living Room is still open. You might want to close it.
        Current temperature: {{ state_attr('climate.living_room', 'temperature') }} °C

- alias: Windows - Kitchen - Notify window still open
  trigger:
    - platform: numeric_state
      entity_id: climate.kitchen
      attribute: temperature
      below: 16
    - platform: state
      entity_id: binary_sensor.window_kitchen
      to: 'on'
      for:
        minutes: 30
  condition:
    - condition: state
      entity_id: input_boolean.summer_mode
      state: 'off'
    - condition: state
      entity_id: binary_sensor.window_kitchen
      state: 'on'
      for:
        minutes: 15
    - condition: numeric_state
      entity_id: climate.kitchen
      attribute: temperature
      below: 16
  action:
    service: notify.patrick
    data:
      title: Kitchen window open
      message: >
        Window in Kitchen is still open. You might want to close it.
        Current temperature: {{ state_attr('climate.kitchen', 'temperature') }} °C

- alias: Windows - Bedroon - Notify window still open
  trigger:
    - platform: numeric_state
      entity_id: climate.bedroom
      attribute: temperature
      below: 16
    - platform: state
      entity_id: binary_sensor.window_bedroom
      to: 'on'
      for:
        minutes: 30
  condition:
    - condition: state
      entity_id: input_boolean.summer_mode
      state: 'off'
    - condition: state
      entity_id: binary_sensor.window_bedroom
      state: 'on'
      for:
        minutes: 15
    - condition: numeric_state
      entity_id: climate.bedroom
      attribute: temperature
      below: 16
  action:
    service: notify.patrick
    data:
      title: Bedroom window open
      message: >
        Window in Bedroom is still open. You might want to close it.
        Current temperature: {{ state_attr('climate.bedroom', 'temperature') }} °C

- alias: Windows - Study - Notify window still open
  trigger:
    - platform: numeric_state
      entity_id: climate.study
      attribute: temperature
      below: 16
    - platform: state
      entity_id: binary_sensor.window_study
      to: 'on'
      for:
        minutes: 30
  condition:
    - condition: state
      entity_id: input_boolean.summer_mode
      state: 'off'
    - condition: state
      entity_id: binary_sensor.window_study
      state: 'on'
      for:
        minutes: 15
    - condition: numeric_state
      entity_id: climate.study
      attribute: temperature
      below: 16
  action:
    service: notify.patrick
    data:
      title: Study window open
      message: >
        Window in Study is still open. You might want to close it.
        Current temperature: {{ state_attr('climate.study', 'temperature') }} °C

- alias: Windows - Bathroom - Notify window still open
  trigger:
    - platform: numeric_state
      entity_id: climate.bathroom
      attribute: temperature
      below: 16
    - platform: state
      entity_id: binary_sensor.window_bathroom
      to: 'on'
      for:
        minutes: 30
  condition:
    - condition: state
      entity_id: input_boolean.summer_mode
      state: 'off'
    - condition: state
      entity_id: binary_sensor.window_bathroom
      state: 'on'
      for:
        minutes: 15
    - condition: numeric_state
      entity_id: climate.bathroom
      attribute: temperature
      below: 16
  action:
    service: notify.patrick
    data:
      title: Bathroom window open
      message: >
        Window in Bathroom is still open. You might want to close it.
        Current temperature: {{ state_attr('climate.bathroom', 'temperature') }} °C
