---

- platform: group
  name: All
  entities:
    - light.bedroom
    - light.living_room
    - light.study

- platform: group
  name: Living Room
  entities:
    - light.tv
    - light.lamp
    # - light.ceiling

- platform: group
  name: Bedroom
  entities:
    - light.lightstrip

- platform: switch
  name: Desk
  entity_id: switch.study_lamp

- platform: group
  name: Study
  entities:
    - light.desk
