---

- platform: group
  name: All
  entities:
    - light.bedroom
    - light.living_room
    - light.study

- platform: group
  name: Ambient
  entities:
    - light.bedroom_wardrobe
    - light.corridor_sideboard
    - light.living_room_lamp
    - light.living_room_tv
    - light.study_shelf

- platform: group
  name: Living Room
  entities:
    - light.living_room_lamp
    - light.living_room_tv

- platform: group
  name: Bedroom
  entities:
    - light.bedroom_wardrobe

- platform: switch
  name: Desk
  entity_id: switch.study_lamp

- platform: group
  name: Study
  entities:
    - light.study_desk
    - light.study_shelf

- platform: group
  name: Corridor
  entities:
    - light.corridor_sideboard
