---

- platform: group
  name: Living Room
  entities:
    - light.living_room_couch
    - light.living_room_lamp
    - light.living_room_tv

- platform: group
  name: Bedroom
  entities:
    - light.bedroom_wardrobe

- platform: group
  name: Study
  entities:
    - light.study_desk
    - light.study_shelf
    - light.study_floor_lamp

- platform: group
  name: Corridor
  entities:
    - light.corridor_sideboard
