---

- platform: group
  name: all
  services:
    - service: mobile_app_iphone
    - service: mobile_app_iphone_von_sandra

- platform: group
  name: patrick
  services:
    - service: mobile_app_iphone

- platform: group
  name: sandra
  services:
    - service: mobile_app_iphone_von_sandra
